; Asteroids Deluxe (astdelux2) - vector ROM, DVG display-list disassembly
; generated by dvgdasm.py - do not hand-edit
;
; Covers only the parts of $4800-$57FF that m6502trace.py proved are
; not 6502 code.  That ROM holds both: TRIROT.MAC is `.ASECT` /
; `.=4800`, so the vector board's ROM carries game code as well as
; pictures.  The 6502 side is in astdelux2_main.asm.
;
; Columns: byte address / DVG word address / raw words / instruction.
; The word address is what a JSRL operand holds: (byte - $4000) / 2.
;
; Shape names come from DSTRD0.MAP, which records them as JSRL
; words - SAUCER appears there as $C734, i.e. byte $4E68.
; Character shapes were named from the VGCHAR table at $56F8.
;
; 'refs:' lines cite where a shape is entered from:
;   6502 $xxxx  - an LXL/LAH address pair in the program, fed to VGJSRL
;   DVG  $xxxx  - a JSRL/JMPL inside this ROM
;

;--------------------------------------------------------------------
; data run $4D80-$57FF  (2688 bytes)
;--------------------------------------------------------------------

EXPPIC: (JSRL $6C0)
;   refs: none found - unreferenced art, reached via a computed word, or entered by fall-through
4D80/6C0:  C715       JSRL   $4E2A   ; -> EXP10
4D82/6C1:  C6FA       JSRL   $4DF4   ; -> EXP12
4D84/6C2:  C6DB       JSRL   $4DB6   ; -> EXP14
4D86/6C3:  C6C4       JSRL   $4D88   ; -> EXP16

EXP16: (JSRL $6C4)
;   refs: DVG  $4D86
4D88/6C4:  F80D       SVEC   u=16  dx=-16   dy=0     z=0
4D8A/6C5:  F878       SVEC   u=16  dx=0     dy=0     z=7
4D8C/6C6:  FD0D       SVEC   u=16  dx=-16   dy=-16   z=0
4D8E/6C7:  F878       SVEC   u=16  dx=0     dy=0     z=7
4D90/6C8:  FD09       SVEC   u=16  dx=16    dy=-16   z=0
4D92/6C9:  F878       SVEC   u=16  dx=0     dy=0     z=7
4D94/6CA:  F10B       SVEC   u=8   dx=24    dy=8     z=0
4D96/6CB:  F878       SVEC   u=16  dx=0     dy=0     z=7
4D98/6CC:  F50A       SVEC   u=8   dx=16    dy=-8    z=0
4D9A/6CD:  F878       SVEC   u=16  dx=0     dy=0     z=7
4D9C/6CE:  F908       SVEC   u=16  dx=0     dy=16    z=0
4D9E/6CF:  F878       SVEC   u=16  dx=0     dy=0     z=7
4DA0/6D0:  F309       SVEC   u=8   dx=8     dy=24    z=0
4DA2/6D1:  F878       SVEC   u=16  dx=0     dy=0     z=7
4DA4/6D2:  F30D       SVEC   u=8   dx=-8    dy=24    z=0
4DA6/6D3:  F878       SVEC   u=16  dx=0     dy=0     z=7
4DA8/6D4:  5480 0600  VCTR   s=5   dx=-32   dy=-8    z=0   [x16]
4DAC/6D6:  F878       SVEC   u=16  dx=0     dy=0     z=7
4DAE/6D7:  F10F       SVEC   u=8   dx=-24   dy=8     z=0
4DB0/6D8:  F878       SVEC   u=16  dx=0     dy=0     z=7
4DB2/6D9:  FE0A       SVEC   u=16  dx=32    dy=-32   z=0
4DB4/6DA:  D000       RTSL

EXP14: (JSRL $6DB)
;   refs: DVG  $4D84
4DB6/6DB:  3000 0780  VCTR   s=3   dx=-14   dy=0     z=0   [x64]
4DBA/6DD:  F878       SVEC   u=16  dx=0     dy=0     z=7
4DBC/6DE:  3780 0780  VCTR   s=3   dx=-14   dy=-14   z=0   [x64]
4DC0/6E0:  F878       SVEC   u=16  dx=0     dy=0     z=7
4DC2/6E1:  3780 0380  VCTR   s=3   dx=14    dy=-14   z=0   [x64]
4DC6/6E3:  F878       SVEC   u=16  dx=0     dy=0     z=7
4DC8/6E4:  40E0 02A0  VCTR   s=4   dx=21    dy=7     z=0   [x32]
4DCC/6E6:  F878       SVEC   u=16  dx=0     dy=0     z=7
4DCE/6E7:  35C0 0380  VCTR   s=3   dx=14    dy=-7    z=0   [x64]
4DD2/6E9:  F878       SVEC   u=16  dx=0     dy=0     z=7
4DD4/6EA:  3380 0000  VCTR   s=3   dx=0     dy=14    z=0   [x64]
4DD8/6EC:  F878       SVEC   u=16  dx=0     dy=0     z=7
4DDA/6ED:  42A0 00E0  VCTR   s=4   dx=7     dy=21    z=0   [x32]
4DDE/6EF:  F878       SVEC   u=16  dx=0     dy=0     z=7
4DE0/6F0:  42A0 04E0  VCTR   s=4   dx=-7    dy=21    z=0   [x32]
4DE4/6F2:  F878       SVEC   u=16  dx=0     dy=0     z=7
4DE6/6F3:  44E0 0780  VCTR   s=4   dx=-28   dy=-7    z=0   [x32]
4DEA/6F5:  F878       SVEC   u=16  dx=0     dy=0     z=7
4DEC/6F6:  40E0 06A0  VCTR   s=4   dx=-21   dy=7     z=0   [x32]
4DF0/6F8:  F878       SVEC   u=16  dx=0     dy=0     z=7
4DF2/6F9:  D000       RTSL

EXP12: (JSRL $6FA)
;   refs: DVG  $4D82
4DF4/6FA:  F807       SVEC   u=4   dx=-12   dy=0     z=0
4DF6/6FB:  F878       SVEC   u=16  dx=0     dy=0     z=7
4DF8/6FC:  FF07       SVEC   u=4   dx=-12   dy=-12   z=0
4DFA/6FD:  F878       SVEC   u=16  dx=0     dy=0     z=7
4DFC/6FE:  FF03       SVEC   u=4   dx=12    dy=-12   z=0
4DFE/6FF:  F878       SVEC   u=16  dx=0     dy=0     z=7
4E00/700:  40C0 0240  VCTR   s=4   dx=18    dy=6     z=0   [x32]
4E04/702:  F878       SVEC   u=16  dx=0     dy=0     z=7
4E06/703:  3580 0300  VCTR   s=3   dx=12    dy=-6    z=0   [x64]
4E0A/705:  F878       SVEC   u=16  dx=0     dy=0     z=7
4E0C/706:  FB00       SVEC   u=4   dx=0     dy=12    z=0
4E0E/707:  F878       SVEC   u=16  dx=0     dy=0     z=7
4E10/708:  4240 00C0  VCTR   s=4   dx=6     dy=18    z=0   [x32]
4E14/70A:  F878       SVEC   u=16  dx=0     dy=0     z=7
4E16/70B:  4240 04C0  VCTR   s=4   dx=-6    dy=18    z=0   [x32]
4E1A/70D:  F878       SVEC   u=16  dx=0     dy=0     z=7
4E1C/70E:  44C0 0700  VCTR   s=4   dx=-24   dy=-6    z=0   [x32]
4E20/710:  F878       SVEC   u=16  dx=0     dy=0     z=7
4E22/711:  40C0 0640  VCTR   s=4   dx=-18   dy=6     z=0   [x32]
4E26/713:  F878       SVEC   u=16  dx=0     dy=0     z=7
4E28/714:  D000       RTSL

EXP10: (JSRL $715)
;   refs: DVG  $4D80
4E2A/715:  3000 0680  VCTR   s=3   dx=-10   dy=0     z=0   [x64]
4E2E/717:  F878       SVEC   u=16  dx=0     dy=0     z=7
4E30/718:  3680 0680  VCTR   s=3   dx=-10   dy=-10   z=0   [x64]
4E34/71A:  F878       SVEC   u=16  dx=0     dy=0     z=7
4E36/71B:  3680 0280  VCTR   s=3   dx=10    dy=-10   z=0   [x64]
4E3A/71D:  F878       SVEC   u=16  dx=0     dy=0     z=7
4E3C/71E:  3140 03C0  VCTR   s=3   dx=15    dy=5     z=0   [x64]
4E40/720:  F878       SVEC   u=16  dx=0     dy=0     z=7
4E42/721:  3540 0280  VCTR   s=3   dx=10    dy=-5    z=0   [x64]
4E46/723:  F878       SVEC   u=16  dx=0     dy=0     z=7
4E48/724:  3280 0000  VCTR   s=3   dx=0     dy=10    z=0   [x64]
4E4C/726:  F878       SVEC   u=16  dx=0     dy=0     z=7
4E4E/727:  33C0 0140  VCTR   s=3   dx=5     dy=15    z=0   [x64]
4E52/729:  F878       SVEC   u=16  dx=0     dy=0     z=7
4E54/72A:  33C0 0540  VCTR   s=3   dx=-5    dy=15    z=0   [x64]
4E58/72C:  F878       SVEC   u=16  dx=0     dy=0     z=7
4E5A/72D:  44A0 0680  VCTR   s=4   dx=-20   dy=-5    z=0   [x32]
4E5E/72F:  F878       SVEC   u=16  dx=0     dy=0     z=7
4E60/730:  3140 07C0  VCTR   s=3   dx=-15   dy=5     z=0   [x64]
4E64/732:  F878       SVEC   u=16  dx=0     dy=0     z=7
4E66/733:  D000       RTSL

SAUCER: (JSRL $734)
;   refs: none found - unreferenced art, reached via a computed word, or entered by fall-through
4E68/734:  F10E       SVEC   u=8   dx=-16   dy=8     z=0
4E6A/735:  F8CA       SVEC   u=16  dx=32    dy=0     z=12
4E6C/736:  F60B       SVEC   u=8   dx=24    dy=-16   z=0
4E6E/737:  6000 D680  VCTR   s=6   dx=-80   dy=0     z=13  [x8]
4E72/739:  F6DB       SVEC   u=8   dx=24    dy=-16   z=13
4E74/73A:  F8CA       SVEC   u=16  dx=32    dy=0     z=12
4E76/73B:  F2DB       SVEC   u=8   dx=24    dy=16    z=13
4E78/73C:  F2DF       SVEC   u=8   dx=-24   dy=16    z=13
4E7A/73D:  F2CD       SVEC   u=8   dx=-8    dy=16    z=12
4E7C/73E:  F8CD       SVEC   u=16  dx=-16   dy=0     z=12
4E7E/73F:  F6CD       SVEC   u=8   dx=-8    dy=-16   z=12
4E80/740:  F6DF       SVEC   u=8   dx=-24   dy=-16   z=13
4E82/741:  D000       RTSL

ROCK0: (JSRL $742)
;   refs: none found - unreferenced art, reached via a computed word, or entered by fall-through
4E84/742:  F009       SVEC   u=8   dx=8     dy=0     z=0
4E86/743:  F17B       SVEC   u=8   dx=24    dy=8     z=7
4E88/744:  F178       SVEC   u=8   dx=0     dy=8     z=7
4E8A/745:  F27F       SVEC   u=8   dx=-24   dy=16    z=7
4E8C/746:  F07F       SVEC   u=8   dx=-24   dy=0     z=7
4E8E/747:  F679       SVEC   u=8   dx=8     dy=-16   z=7
4E90/748:  F87E       SVEC   u=16  dx=-32   dy=0     z=7
4E92/749:  F778       SVEC   u=8   dx=0     dy=-24   z=7
4E94/74A:  F77B       SVEC   u=8   dx=24    dy=-24   z=7
4E96/74B:  F17B       SVEC   u=8   dx=24    dy=8     z=7
4E98/74C:  F579       SVEC   u=8   dx=8     dy=-8    z=7
4E9A/74D:  F979       SVEC   u=16  dx=16    dy=16    z=7
4E9C/74E:  F27F       SVEC   u=8   dx=-24   dy=16    z=7

ROCK1: (JSRL $74F)
;   refs: none found - unreferenced art, reached via a computed word, or entered by fall-through
4E9E/74F:  3080 0200  VCTR   s=3   dx=8     dy=2     z=0   [x64]
4EA2/751:  4180 72C0  VCTR   s=4   dx=22    dy=12    z=7   [x32]
4EA6/753:  3200 7480  VCTR   s=3   dx=-2    dy=8     z=7   [x64]
4EAA/755:  4160 7740  VCTR   s=4   dx=-26   dy=11    z=7   [x32]
4EAE/757:  44A0 7700  VCTR   s=4   dx=-24   dy=-5    z=7   [x32]
4EB2/759:  3780 72C0  VCTR   s=3   dx=11    dy=-14   z=7   [x64]
4EB6/75B:  44C0 77E0  VCTR   s=4   dx=-31   dy=-6    z=7   [x32]
4EBA/75D:  4700 7080  VCTR   s=4   dx=4     dy=-24   z=7   [x32]
4EBE/75F:  4660 73A0  VCTR   s=4   dx=29    dy=-19   z=7   [x32]
4EC2/761:  41A0 72C0  VCTR   s=4   dx=22    dy=13    z=7   [x32]
4EC6/763:  3580 7240  VCTR   s=3   dx=9     dy=-6    z=7   [x64]
4ECA/765:  4260 71A0  VCTR   s=4   dx=13    dy=19    z=7   [x32]
4ECE/767:  4160 7760  VCTR   s=4   dx=-27   dy=11    z=7   [x32]

ROCK2: (JSRL $769)
;   refs: none found - unreferenced art, reached via a computed word, or entered by fall-through
4ED2/769:  2180 0380  VCTR   s=2   dx=7     dy=3     z=0   [x128]
4ED6/76B:  4220 7280  VCTR   s=4   dx=20    dy=17    z=7   [x32]
4EDA/76D:  2380 7600  VCTR   s=2   dx=-4    dy=7     z=7   [x128]
4EDE/76F:  40C0 7780  VCTR   s=4   dx=-28   dy=6     z=7   [x32]
4EE2/771:  4540 76C0  VCTR   s=4   dx=-22   dy=-10   z=7   [x32]
4EE6/773:  36C0 7340  VCTR   s=3   dx=13    dy=-11   z=7   [x64]
4EEA/775:  45A0 77A0  VCTR   s=4   dx=-29   dy=-13   z=7   [x32]
4EEE/777:  46C0 7120  VCTR   s=4   dx=9     dy=-22   z=7   [x32]
4EF2/779:  45A0 73E0  VCTR   s=4   dx=31    dy=-13   z=7   [x32]
4EF6/77B:  4220 7280  VCTR   s=4   dx=20    dy=17    z=7   [x32]
4EFA/77D:  3500 7280  VCTR   s=3   dx=10    dy=-4    z=7   [x64]
4EFE/77F:  4280 7120  VCTR   s=4   dx=9     dy=20    z=7   [x32]
4F02/781:  40C0 77A0  VCTR   s=4   dx=-29   dy=6     z=7   [x32]

ROCK3: (JSRL $783)
;   refs: none found - unreferenced art, reached via a computed word, or entered by fall-through
4F06/783:  2200 0380  VCTR   s=2   dx=7     dy=4     z=0   [x128]
4F0A/785:  4280 71E0  VCTR   s=4   dx=15    dy=20    z=7   [x32]
4F0E/787:  2380 7600  VCTR   s=2   dx=-4    dy=7     z=7   [x128]
4F12/789:  4000 77A0  VCTR   s=4   dx=-29   dy=0     z=7   [x32]
4F16/78B:  45A0 7680  VCTR   s=4   dx=-20   dy=-13   z=7   [x32]
4F1A/78D:  3640 73C0  VCTR   s=3   dx=15    dy=-9    z=7   [x64]
4F1E/78F:  4640 7740  VCTR   s=4   dx=-26   dy=-18   z=7   [x32]
4F22/791:  4680 71A0  VCTR   s=4   dx=13    dy=-20   z=7   [x32]
4F26/793:  5460 7210  VCTR   s=5   dx=33    dy=-6    z=7   [x16]
4F2A/795:  4260 7200  VCTR   s=4   dx=16    dy=19    z=7   [x32]
4F2E/797:  3480 72C0  VCTR   s=3   dx=11    dy=-2    z=7   [x64]
4F32/799:  42C0 7080  VCTR   s=4   dx=4     dy=22    z=7   [x32]
4F36/79B:  4000 7780  VCTR   s=4   dx=-28   dy=0     z=7   [x32]

ROCK4: (JSRL $79D)
;   refs: none found - unreferenced art, reached via a computed word, or entered by fall-through
4F3A/79D:  F303       SVEC   u=2   dx=6     dy=6     z=0
4F3C/79E:  42C0 7160  VCTR   s=4   dx=11    dy=22    z=7   [x32]
4F40/7A0:  F377       SVEC   u=2   dx=-6    dy=6     z=7
4F42/7A1:  44C0 7780  VCTR   s=4   dx=-28   dy=-6    z=7   [x32]
4F46/7A3:  4620 7620  VCTR   s=4   dx=-17   dy=-17   z=7   [x32]
4F4A/7A5:  44A0 7220  VCTR   s=4   dx=17    dy=-5    z=7   [x32]
4F4E/7A7:  46E0 76E0  VCTR   s=4   dx=-23   dy=-23   z=7   [x32]
4F52/7A9:  4620 7220  VCTR   s=4   dx=17    dy=-17   z=7   [x32]
4F56/7AB:  5000 7220  VCTR   s=5   dx=34    dy=0     z=7   [x16]
4F5A/7AD:  42E0 7180  VCTR   s=4   dx=12    dy=23    z=7   [x32]
4F5E/7AF:  3000 72C0  VCTR   s=3   dx=11    dy=0     z=7   [x64]
4F62/7B1:  42C0 7000  VCTR   s=4   dx=0     dy=22    z=7   [x32]
4F66/7B3:  44A0 7780  VCTR   s=4   dx=-28   dy=-5    z=7   [x32]

ROCK5: (JSRL $7B5)
;   refs: none found - unreferenced art, reached via a computed word, or entered by fall-through
4F6A/7B5:  2380 0200  VCTR   s=2   dx=4     dy=7     z=0   [x128]
4F6E/7B7:  4300 70E0  VCTR   s=4   dx=7     dy=24    z=7   [x32]
4F72/7B9:  2200 7780  VCTR   s=2   dx=-7    dy=4     z=7   [x128]
4F76/7BB:  4560 7740  VCTR   s=4   dx=-26   dy=-11   z=7   [x32]
4F7A/7BD:  4680 75A0  VCTR   s=4   dx=-13   dy=-20   z=7   [x32]
4F7E/7BF:  4440 7220  VCTR   s=4   dx=17    dy=-2    z=7   [x32]
4F82/7C1:  4740 7640  VCTR   s=4   dx=-18   dy=-26   z=7   [x32]
4F86/7C3:  45C0 7280  VCTR   s=4   dx=20    dy=-14   z=7   [x32]
4F8A/7C5:  5070 7220  VCTR   s=5   dx=34    dy=7     z=7   [x16]
4F8E/7C7:  4300 70C0  VCTR   s=4   dx=6     dy=24    z=7   [x32]
4F92/7C9:  30C0 72C0  VCTR   s=3   dx=11    dy=3     z=7   [x64]
4F96/7CB:  42C0 7480  VCTR   s=4   dx=-4    dy=22    z=7   [x32]
4F9A/7CD:  4560 7760  VCTR   s=4   dx=-27   dy=-11   z=7   [x32]

ROCK6: (JSRL $7CF)
;   refs: none found - unreferenced art, reached via a computed word, or entered by fall-through
4F9E/7CF:  2380 0180  VCTR   s=2   dx=3     dy=7     z=0   [x128]
4FA2/7D1:  4340 7040  VCTR   s=4   dx=2     dy=26    z=7   [x32]
4FA6/7D3:  30C0 7600  VCTR   s=3   dx=-8    dy=3     z=7   [x64]
4FAA/7D5:  F67F       SVEC   u=8   dx=-24   dy=-16   z=7
4FAC/7D6:  46E0 7520  VCTR   s=4   dx=-9    dy=-23   z=7   [x32]
4FB0/7D8:  4040 7240  VCTR   s=4   dx=18    dy=2     z=7   [x32]
4FB4/7DA:  47C0 7580  VCTR   s=4   dx=-12   dy=-30   z=7   [x32]
4FB8/7DC:  4520 72C0  VCTR   s=4   dx=22    dy=-9    z=7   [x32]
4FBC/7DE:  41A0 73E0  VCTR   s=4   dx=31    dy=13    z=7   [x32]
4FC0/7E0:  4320 7040  VCTR   s=4   dx=2     dy=25    z=7   [x32]
4FC4/7E2:  3140 72C0  VCTR   s=3   dx=11    dy=5     z=7   [x64]
4FC8/7E4:  4280 7520  VCTR   s=4   dx=-9    dy=20    z=7   [x32]
4FCC/7E6:  F67F       SVEC   u=8   dx=-24   dy=-16   z=7

ROCK7: (JSRL $7E7)
;   refs: none found - unreferenced art, reached via a computed word, or entered by fall-through
4FCE/7E7:  3200 0080  VCTR   s=3   dx=2     dy=8     z=0   [x64]
4FD2/7E9:  4320 7480  VCTR   s=4   dx=-4    dy=25    z=7   [x32]
4FD6/7EB:  2100 7780  VCTR   s=2   dx=-7    dy=2     z=7   [x128]
4FDA/7ED:  46A0 76A0  VCTR   s=4   dx=-21   dy=-21   z=7   [x32]
4FDE/7EF:  46E0 74A0  VCTR   s=4   dx=-5    dy=-23   z=7   [x32]
4FE2/7F1:  4080 7240  VCTR   s=4   dx=18    dy=4     z=7   [x32]
4FE6/7F3:  47E0 74C0  VCTR   s=4   dx=-6    dy=-31   z=7   [x32]
4FEA/7F5:  44A0 72E0  VCTR   s=4   dx=23    dy=-5    z=7   [x32]
4FEE/7F7:  4260 7380  VCTR   s=4   dx=28    dy=19    z=7   [x32]
4FF2/7F9:  4320 7460  VCTR   s=4   dx=-3    dy=25    z=7   [x32]
4FF6/7FB:  3180 7280  VCTR   s=3   dx=10    dy=6     z=7   [x64]
4FFA/7FD:  4260 75A0  VCTR   s=4   dx=-13   dy=19    z=7   [x32]
4FFE/7FF:  4680 7680  VCTR   s=4   dx=-20   dy=-20   z=7   [x32]

RSOURC: (JSRL $801)
;   refs: none found - unreferenced art, reached via a computed word, or entered by fall-through
5002/801:  4E84 4E9E  VCTR   s=4   dx=-670  dy=-644  z=4   [raw]
5006/803:  4ED2 4F06  VCTR   s=4   dx=-774  dy=-722  z=4   [raw]
500A/805:  4F3A 4F6A  VCTR   s=4   dx=-874  dy=-826  z=4   [raw]
500E/807:  4F9E 4FCE  VCTR   s=4   dx=-974  dy=-926  z=4   [raw]

SHLDVC: (JSRL $809)
;   refs: 6502 $66AD
5012/809:  5180 0380  VCTR   s=5   dx=56    dy=24    z=0   [x16]
5016/80B:  FA0E       SVEC   u=16  dx=-32   dy=32    z=0
5018/80C:  F80F       SVEC   u=16  dx=-48   dy=0     z=0
501A/80D:  FE0E       SVEC   u=16  dx=-32   dy=-32   z=0
501C/80E:  FF08       SVEC   u=16  dx=0     dy=-48   z=0
501E/80F:  FE0A       SVEC   u=16  dx=32    dy=-32   z=0
5020/810:  F80B       SVEC   u=16  dx=48    dy=0     z=0
5022/811:  FA0A       SVEC   u=16  dx=32    dy=32    z=0
5024/812:  FB08       SVEC   u=16  dx=0     dy=48    z=0
5026/813:  5580 0780  VCTR   s=5   dx=-56   dy=-24   z=0   [x16]

TFPIX: (JSRL $815)
;   refs: none found - unreferenced art, reached via a computed word, or entered by fall-through
502A/815:  C845       JSRL   $508A   ; -> TRI00
502C/816:  C84E       JSRL   $509C   ; -> TRI01
502E/817:  C857       JSRL   $50AE   ; -> TRI02
5030/818:  C860       JSRL   $50C0   ; -> TRI03
5032/819:  C869       JSRL   $50D2   ; -> TRI04
5034/81A:  C872       JSRL   $50E4   ; -> TRI05
5036/81B:  C87B       JSRL   $50F6   ; -> TRI06
5038/81C:  C884       JSRL   $5108   ; -> TRI07
503A/81D:  C88D       JSRL   $511A   ; -> TRI10
503C/81E:  C896       JSRL   $512C   ; -> TRI11
503E/81F:  C89F       JSRL   $513E   ; -> TRI12
5040/820:  C8A8       JSRL   $5150   ; -> TRI13
5042/821:  C8B1       JSRL   $5162   ; -> TRI14
5044/822:  C8BA       JSRL   $5174   ; -> TRI15
5046/823:  C8C3       JSRL   $5186   ; -> TRI16
5048/824:  C8CC       JSRL   $5198   ; -> TRI17
504A/825:  C8D5       JSRL   $51AA   ; -> TRI20
504C/826:  C8DE       JSRL   $51BC   ; -> TRI21
504E/827:  C8E7       JSRL   $51CE   ; -> TRI22
5050/828:  C8F0       JSRL   $51E0   ; -> TRI23
5052/829:  C8F9       JSRL   $51F2   ; -> TRI24
5054/82A:  C902       JSRL   $5204   ; -> TRI25
5056/82B:  C90B       JSRL   $5216   ; -> TRI26
5058/82C:  C914       JSRL   $5228   ; -> TRI27
505A/82D:  C91D       JSRL   $523A   ; -> TRI30
505C/82E:  C926       JSRL   $524C   ; -> TRI31
505E/82F:  C92F       JSRL   $525E   ; -> TRI32
5060/830:  C938       JSRL   $5270   ; -> TRI33
5062/831:  C941       JSRL   $5282   ; -> TRI34
5064/832:  C94A       JSRL   $5294   ; -> TRI35
5066/833:  C953       JSRL   $52A6   ; -> TRI36
5068/834:  C95C       JSRL   $52B8   ; -> TRI37
506A/835:  C965       JSRL   $52CA   ; -> FRM00
506C/836:  C969       JSRL   $52D2   ; -> FRM01
506E/837:  C96F       JSRL   $52DE   ; -> FRM02
5070/838:  C975       JSRL   $52EA   ; -> FRM03
5072/839:  C97B       JSRL   $52F6   ; -> FRM04
5074/83A:  C981       JSRL   $5302   ; -> FRM05
5076/83B:  C987       JSRL   $530E   ; -> FRM06
5078/83C:  C98D       JSRL   $531A   ; -> FRM07
507A/83D:  C993       JSRL   $5326   ; -> FRM10
507C/83E:  C997       JSRL   $532E   ; -> FRM11
507E/83F:  C99D       JSRL   $533A   ; -> FRM12
5080/840:  C9A3       JSRL   $5346   ; -> FRM13
5082/841:  C9A9       JSRL   $5352   ; -> FRM14
5084/842:  C9AF       JSRL   $535E   ; -> FRM15
5086/843:  C9B5       JSRL   $536A   ; -> FRM16
5088/844:  C9BB       JSRL   $5376   ; -> FRM17

TRI00: (JSRL $845)
;   refs: DVG  $502A
;   refs: DVG  $52CC
508A/845:  4380 7600  VCTR   s=4   dx=-16   dy=28    z=7   [x32]
508E/847:  55C0 7300  VCTR   s=5   dx=48    dy=-28   z=7   [x16]
5092/849:  55C0 7700  VCTR   s=5   dx=-48   dy=-28   z=7   [x16]
5096/84B:  4380 7200  VCTR   s=4   dx=16    dy=28    z=7   [x32]
509A/84D:  D000       RTSL

TRI01: (JSRL $84E)
;   refs: DVG  $502C
;   refs: DVG  $52D6
509C/84E:  4300 76A0  VCTR   s=4   dx=-21   dy=24    z=7   [x32]
50A0/850:  5520 7340  VCTR   s=5   dx=52    dy=-18   z=7   [x16]
50A4/852:  5650 7690  VCTR   s=5   dx=-41   dy=-37   z=7   [x16]
50A8/854:  43E0 7140  VCTR   s=4   dx=10    dy=31    z=7   [x32]
50AC/856:  D000       RTSL

TRI02: (JSRL $857)
;   refs: DVG  $502E
;   refs: DVG  $52E2
50AE/857:  4280 7720  VCTR   s=4   dx=-25   dy=20    z=7   [x32]
50B2/859:  5480 7370  VCTR   s=5   dx=55    dy=-8    z=7   [x16]
50B6/85B:  56C0 7620  VCTR   s=5   dx=-34   dy=-44   z=7   [x16]
50BA/85D:  5200 7040  VCTR   s=5   dx=4     dy=32    z=7   [x16]
50BE/85F:  D000       RTSL

TRI03: (JSRL $860)
;   refs: DVG  $5030
;   refs: DVG  $52EE
50C0/860:  41C0 77A0  VCTR   s=4   dx=-29   dy=14    z=7   [x32]
50C4/862:  5040 7380  VCTR   s=5   dx=56    dy=4     z=7   [x16]
50C8/864:  5720 7590  VCTR   s=5   dx=-25   dy=-50   z=7   [x16]
50CC/866:  5200 7420  VCTR   s=5   dx=-2    dy=32    z=7   [x16]
50D0/868:  D000       RTSL

TRI04: (JSRL $869)
;   refs: DVG  $5032
;   refs: DVG  $52FA
50D2/869:  4100 77E0  VCTR   s=4   dx=-31   dy=8     z=7   [x32]
50D6/86B:  50F0 7360  VCTR   s=5   dx=54    dy=15    z=7   [x16]
50DA/86D:  5760 74F0  VCTR   s=5   dx=-15   dy=-54   z=7   [x16]
50DE/86F:  43E0 7500  VCTR   s=4   dx=-8    dy=31    z=7   [x32]
50E2/871:  D000       RTSL

TRI05: (JSRL $872)
;   refs: DVG  $5034
;   refs: DVG  $5306
50E4/872:  5020 7600  VCTR   s=5   dx=-32   dy=2     z=7   [x16]
50E8/874:  5190 7320  VCTR   s=5   dx=50    dy=25    z=7   [x16]
50EC/876:  5780 7440  VCTR   s=5   dx=-4    dy=-56   z=7   [x16]
50F0/878:  43A0 75C0  VCTR   s=4   dx=-14   dy=29    z=7   [x32]
50F4/87A:  D000       RTSL

TRI06: (JSRL $87B)
;   refs: DVG  $5036
;   refs: DVG  $5312
50F6/87B:  5440 7600  VCTR   s=5   dx=-32   dy=-4    z=7   [x16]
50FA/87D:  5220 72C0  VCTR   s=5   dx=44    dy=34    z=7   [x16]
50FE/87F:  5770 7080  VCTR   s=5   dx=8     dy=-55   z=7   [x16]
5102/881:  4320 7680  VCTR   s=4   dx=-20   dy=25    z=7   [x32]
5106/883:  D000       RTSL

TRI07: (JSRL $884)
;   refs: DVG  $5038
;   refs: DVG  $531E
5108/884:  4540 77E0  VCTR   s=4   dx=-31   dy=-10   z=7   [x32]
510C/886:  5290 7250  VCTR   s=5   dx=37    dy=41    z=7   [x16]
5110/888:  5740 7120  VCTR   s=5   dx=18    dy=-52   z=7   [x16]
5114/88A:  42A0 7700  VCTR   s=4   dx=-24   dy=21    z=7   [x32]
5118/88C:  D000       RTSL

TRI10: (JSRL $88D)
;   refs: DVG  $503A
;   refs: DVG  $5328
511A/88D:  4600 7780  VCTR   s=4   dx=-28   dy=-16   z=7   [x32]
511E/88F:  5300 71C0  VCTR   s=5   dx=28    dy=48    z=7   [x16]
5122/891:  5700 71C0  VCTR   s=5   dx=28    dy=-48   z=7   [x16]
5126/893:  4200 7780  VCTR   s=4   dx=-28   dy=16    z=7   [x32]
512A/895:  D000       RTSL

TRI11: (JSRL $896)
;   refs: DVG  $503C
;   refs: DVG  $5332
512C/896:  46A0 7700  VCTR   s=4   dx=-24   dy=-21   z=7   [x32]
5130/898:  5340 7120  VCTR   s=5   dx=18    dy=52    z=7   [x16]
5134/89A:  5690 7250  VCTR   s=5   dx=37    dy=-41   z=7   [x16]
5138/89C:  4140 77E0  VCTR   s=4   dx=-31   dy=10    z=7   [x32]
513C/89E:  D000       RTSL

TRI12: (JSRL $89F)
;   refs: DVG  $503E
;   refs: DVG  $533E
513E/89F:  4720 7680  VCTR   s=4   dx=-20   dy=-25   z=7   [x32]
5142/8A1:  5370 7080  VCTR   s=5   dx=8     dy=55    z=7   [x16]
5146/8A3:  5620 72C0  VCTR   s=5   dx=44    dy=-34   z=7   [x16]
514A/8A5:  5040 7600  VCTR   s=5   dx=-32   dy=4     z=7   [x16]
514E/8A7:  D000       RTSL

TRI13: (JSRL $8A8)
;   refs: DVG  $5040
;   refs: DVG  $534A
5150/8A8:  47A0 75C0  VCTR   s=4   dx=-14   dy=-29   z=7   [x32]
5154/8AA:  5380 7440  VCTR   s=5   dx=-4    dy=56    z=7   [x16]
5158/8AC:  5590 7320  VCTR   s=5   dx=50    dy=-25   z=7   [x16]
515C/8AE:  5420 7600  VCTR   s=5   dx=-32   dy=-2    z=7   [x16]
5160/8B0:  D000       RTSL

TRI14: (JSRL $8B1)
;   refs: DVG  $5042
;   refs: DVG  $5356
5162/8B1:  47E0 7500  VCTR   s=4   dx=-8    dy=-31   z=7   [x32]
5166/8B3:  5360 74F0  VCTR   s=5   dx=-15   dy=54    z=7   [x16]
516A/8B5:  54F0 7360  VCTR   s=5   dx=54    dy=-15   z=7   [x16]
516E/8B7:  4500 77E0  VCTR   s=4   dx=-31   dy=-8    z=7   [x32]
5172/8B9:  D000       RTSL

TRI15: (JSRL $8BA)
;   refs: DVG  $5044
;   refs: DVG  $5362
5174/8BA:  5600 7420  VCTR   s=5   dx=-2    dy=-32   z=7   [x16]
5178/8BC:  5320 7590  VCTR   s=5   dx=-25   dy=50    z=7   [x16]
517C/8BE:  5440 7380  VCTR   s=5   dx=56    dy=-4    z=7   [x16]
5180/8C0:  45C0 77A0  VCTR   s=4   dx=-29   dy=-14   z=7   [x32]
5184/8C2:  D000       RTSL

TRI16: (JSRL $8C3)
;   refs: DVG  $5046
;   refs: DVG  $536E
5186/8C3:  5600 7040  VCTR   s=5   dx=4     dy=-32   z=7   [x16]
518A/8C5:  52C0 7620  VCTR   s=5   dx=-34   dy=44    z=7   [x16]
518E/8C7:  5080 7370  VCTR   s=5   dx=55    dy=8     z=7   [x16]
5192/8C9:  4680 7720  VCTR   s=4   dx=-25   dy=-20   z=7   [x32]
5196/8CB:  D000       RTSL

TRI17: (JSRL $8CC)
;   refs: DVG  $5048
;   refs: DVG  $537A
5198/8CC:  47E0 7140  VCTR   s=4   dx=10    dy=-31   z=7   [x32]
519C/8CE:  5250 7690  VCTR   s=5   dx=-41   dy=37    z=7   [x16]
51A0/8D0:  5120 7340  VCTR   s=5   dx=52    dy=18    z=7   [x16]
51A4/8D2:  4700 76A0  VCTR   s=4   dx=-21   dy=-24   z=7   [x32]
51A8/8D4:  D000       RTSL

TRI20: (JSRL $8D5)
;   refs: DVG  $504A
;   refs: DVG  $52D0
51AA/8D5:  4780 7200  VCTR   s=4   dx=16    dy=-28   z=7   [x32]
51AE/8D7:  51C0 7700  VCTR   s=5   dx=-48   dy=28    z=7   [x16]
51B2/8D9:  51C0 7300  VCTR   s=5   dx=48    dy=28    z=7   [x16]
51B6/8DB:  4780 7600  VCTR   s=4   dx=-16   dy=-28   z=7   [x32]
51BA/8DD:  D000       RTSL

TRI21: (JSRL $8DE)
;   refs: DVG  $504C
;   refs: DVG  $52DC
51BC/8DE:  4700 72A0  VCTR   s=4   dx=21    dy=-24   z=7   [x32]
51C0/8E0:  5120 7740  VCTR   s=5   dx=-52   dy=18    z=7   [x16]
51C4/8E2:  5250 7290  VCTR   s=5   dx=41    dy=37    z=7   [x16]
51C8/8E4:  47E0 7540  VCTR   s=4   dx=-10   dy=-31   z=7   [x32]
51CC/8E6:  D000       RTSL

TRI22: (JSRL $8E7)
;   refs: DVG  $504E
;   refs: DVG  $52E8
51CE/8E7:  4680 7320  VCTR   s=4   dx=25    dy=-20   z=7   [x32]
51D2/8E9:  5080 7770  VCTR   s=5   dx=-55   dy=8     z=7   [x16]
51D6/8EB:  52C0 7220  VCTR   s=5   dx=34    dy=44    z=7   [x16]
51DA/8ED:  5600 7440  VCTR   s=5   dx=-4    dy=-32   z=7   [x16]
51DE/8EF:  D000       RTSL

TRI23: (JSRL $8F0)
;   refs: DVG  $5050
;   refs: DVG  $52F4
51E0/8F0:  45C0 73A0  VCTR   s=4   dx=29    dy=-14   z=7   [x32]
51E4/8F2:  5440 7780  VCTR   s=5   dx=-56   dy=-4    z=7   [x16]
51E8/8F4:  5320 7190  VCTR   s=5   dx=25    dy=50    z=7   [x16]
51EC/8F6:  5600 7020  VCTR   s=5   dx=2     dy=-32   z=7   [x16]
51F0/8F8:  D000       RTSL

TRI24: (JSRL $8F9)
;   refs: DVG  $5052
;   refs: DVG  $5300
51F2/8F9:  4500 73E0  VCTR   s=4   dx=31    dy=-8    z=7   [x32]
51F6/8FB:  54F0 7760  VCTR   s=5   dx=-54   dy=-15   z=7   [x16]
51FA/8FD:  5360 70F0  VCTR   s=5   dx=15    dy=54    z=7   [x16]
51FE/8FF:  47E0 7100  VCTR   s=4   dx=8     dy=-31   z=7   [x32]
5202/901:  D000       RTSL

TRI25: (JSRL $902)
;   refs: DVG  $5054
;   refs: DVG  $530C
5204/902:  5420 7200  VCTR   s=5   dx=32    dy=-2    z=7   [x16]
5208/904:  5590 7720  VCTR   s=5   dx=-50   dy=-25   z=7   [x16]
520C/906:  5380 7040  VCTR   s=5   dx=4     dy=56    z=7   [x16]
5210/908:  47A0 71C0  VCTR   s=4   dx=14    dy=-29   z=7   [x32]
5214/90A:  D000       RTSL

TRI26: (JSRL $90B)
;   refs: DVG  $5056
;   refs: DVG  $5318
5216/90B:  5040 7200  VCTR   s=5   dx=32    dy=4     z=7   [x16]
521A/90D:  5620 76C0  VCTR   s=5   dx=-44   dy=-34   z=7   [x16]
521E/90F:  5370 7480  VCTR   s=5   dx=-8    dy=55    z=7   [x16]
5222/911:  4720 7280  VCTR   s=4   dx=20    dy=-25   z=7   [x32]
5226/913:  D000       RTSL

TRI27: (JSRL $914)
;   refs: DVG  $5058
;   refs: DVG  $5324
5228/914:  4140 73E0  VCTR   s=4   dx=31    dy=10    z=7   [x32]
522C/916:  5690 7650  VCTR   s=5   dx=-37   dy=-41   z=7   [x16]
5230/918:  5340 7520  VCTR   s=5   dx=-18   dy=52    z=7   [x16]
5234/91A:  46A0 7300  VCTR   s=4   dx=24    dy=-21   z=7   [x32]
5238/91C:  D000       RTSL

TRI30: (JSRL $91D)
;   refs: DVG  $505A
;   refs: DVG  $532C
523A/91D:  4200 7380  VCTR   s=4   dx=28    dy=16    z=7   [x32]
523E/91F:  5700 75C0  VCTR   s=5   dx=-28   dy=-48   z=7   [x16]
5242/921:  5300 75C0  VCTR   s=5   dx=-28   dy=48    z=7   [x16]
5246/923:  4600 7380  VCTR   s=4   dx=28    dy=-16   z=7   [x32]
524A/925:  D000       RTSL

TRI31: (JSRL $926)
;   refs: DVG  $505C
;   refs: DVG  $5338
524C/926:  42A0 7300  VCTR   s=4   dx=24    dy=21    z=7   [x32]
5250/928:  5740 7520  VCTR   s=5   dx=-18   dy=-52   z=7   [x16]
5254/92A:  5290 7650  VCTR   s=5   dx=-37   dy=41    z=7   [x16]
5258/92C:  4540 73E0  VCTR   s=4   dx=31    dy=-10   z=7   [x32]
525C/92E:  D000       RTSL

TRI32: (JSRL $92F)
;   refs: DVG  $505E
;   refs: DVG  $5344
525E/92F:  4320 7280  VCTR   s=4   dx=20    dy=25    z=7   [x32]
5262/931:  5770 7480  VCTR   s=5   dx=-8    dy=-55   z=7   [x16]
5266/933:  5220 76C0  VCTR   s=5   dx=-44   dy=34    z=7   [x16]
526A/935:  5440 7200  VCTR   s=5   dx=32    dy=-4    z=7   [x16]
526E/937:  D000       RTSL

TRI33: (JSRL $938)
;   refs: DVG  $5060
;   refs: DVG  $5350
5270/938:  43A0 71C0  VCTR   s=4   dx=14    dy=29    z=7   [x32]
5274/93A:  5780 7040  VCTR   s=5   dx=4     dy=-56   z=7   [x16]
5278/93C:  5190 7720  VCTR   s=5   dx=-50   dy=25    z=7   [x16]
527C/93E:  5020 7200  VCTR   s=5   dx=32    dy=2     z=7   [x16]
5280/940:  D000       RTSL

TRI34: (JSRL $941)
;   refs: DVG  $5062
;   refs: DVG  $535C
5282/941:  43E0 7100  VCTR   s=4   dx=8     dy=31    z=7   [x32]
5286/943:  5760 70F0  VCTR   s=5   dx=15    dy=-54   z=7   [x16]
528A/945:  50F0 7760  VCTR   s=5   dx=-54   dy=15    z=7   [x16]
528E/947:  4100 73E0  VCTR   s=4   dx=31    dy=8     z=7   [x32]
5292/949:  D000       RTSL

TRI35: (JSRL $94A)
;   refs: DVG  $5064
;   refs: DVG  $5368
5294/94A:  5200 7020  VCTR   s=5   dx=2     dy=32    z=7   [x16]
5298/94C:  5720 7190  VCTR   s=5   dx=25    dy=-50   z=7   [x16]
529C/94E:  5040 7780  VCTR   s=5   dx=-56   dy=4     z=7   [x16]
52A0/950:  41C0 73A0  VCTR   s=4   dx=29    dy=14    z=7   [x32]
52A4/952:  D000       RTSL

TRI36: (JSRL $953)
;   refs: DVG  $5066
;   refs: DVG  $5374
52A6/953:  5200 7440  VCTR   s=5   dx=-4    dy=32    z=7   [x16]
52AA/955:  56C0 7220  VCTR   s=5   dx=34    dy=-44   z=7   [x16]
52AE/957:  5480 7770  VCTR   s=5   dx=-55   dy=-8    z=7   [x16]
52B2/959:  4280 7320  VCTR   s=4   dx=25    dy=20    z=7   [x32]
52B6/95B:  D000       RTSL

TRI37: (JSRL $95C)
;   refs: DVG  $5068
;   refs: DVG  $5380
52B8/95C:  43E0 7540  VCTR   s=4   dx=-10   dy=31    z=7   [x32]
52BC/95E:  5650 7290  VCTR   s=5   dx=41    dy=-37   z=7   [x16]
52C0/960:  5520 7740  VCTR   s=5   dx=-52   dy=-18   z=7   [x16]
52C4/962:  4300 72A0  VCTR   s=4   dx=21    dy=24    z=7   [x32]
52C8/964:  D000       RTSL

FRM00: (JSRL $965)
;   refs: DVG  $506A
52CA/965:  F809       SVEC   u=16  dx=16    dy=0     z=0
52CC/966:  C845       JSRL   $508A   ; -> TRI00
52CE/967:  F80E       SVEC   u=16  dx=-32   dy=0     z=0
52D0/968:  E8D5       JMPL   $51AA   ; -> TRI20

FRM01: (JSRL $969)
;   refs: DVG  $506C
52D2/969:  4060 0200  VCTR   s=4   dx=16    dy=3     z=0   [x32]
52D6/96B:  C84E       JSRL   $509C   ; -> TRI01
52D8/96C:  5460 0600  VCTR   s=5   dx=-32   dy=-6    z=0   [x16]
52DC/96E:  E8DE       JMPL   $51BC   ; -> TRI21

FRM02: (JSRL $96F)
;   refs: DVG  $506E
52DE/96F:  3180 03C0  VCTR   s=3   dx=15    dy=6     z=0   [x64]
52E2/971:  C857       JSRL   $50AE   ; -> TRI02
52E4/972:  4580 07C0  VCTR   s=4   dx=-30   dy=-12   z=0   [x32]
52E8/974:  E8E7       JMPL   $51CE   ; -> TRI22

FRM03: (JSRL $975)
;   refs: DVG  $5070
52EA/975:  3240 0340  VCTR   s=3   dx=13    dy=9     z=0   [x64]
52EE/977:  C860       JSRL   $50C0   ; -> TRI03
52F0/978:  4640 0740  VCTR   s=4   dx=-26   dy=-18   z=0   [x32]
52F4/97A:  E8F0       JMPL   $51E0   ; -> TRI23

FRM04: (JSRL $97B)
;   refs: DVG  $5072
52F6/97B:  32C0 02C0  VCTR   s=3   dx=11    dy=11    z=0   [x64]
52FA/97D:  C869       JSRL   $50D2   ; -> TRI04
52FC/97E:  46C0 06C0  VCTR   s=4   dx=-22   dy=-22   z=0   [x32]
5300/980:  E8F9       JMPL   $51F2   ; -> TRI24

FRM05: (JSRL $981)
;   refs: DVG  $5074
5302/981:  3340 0240  VCTR   s=3   dx=9     dy=13    z=0   [x64]
5306/983:  C872       JSRL   $50E4   ; -> TRI05
5308/984:  4740 0640  VCTR   s=4   dx=-18   dy=-26   z=0   [x32]
530C/986:  E902       JMPL   $5204   ; -> TRI25

FRM06: (JSRL $987)
;   refs: DVG  $5076
530E/987:  33C0 0180  VCTR   s=3   dx=6     dy=15    z=0   [x64]
5312/989:  C87B       JSRL   $50F6   ; -> TRI06
5314/98A:  47C0 0580  VCTR   s=4   dx=-12   dy=-30   z=0   [x32]
5318/98C:  E90B       JMPL   $5216   ; -> TRI26

FRM07: (JSRL $98D)
;   refs: DVG  $5078
531A/98D:  4200 0060  VCTR   s=4   dx=3     dy=16    z=0   [x32]
531E/98F:  C884       JSRL   $5108   ; -> TRI07
5320/990:  5600 0460  VCTR   s=5   dx=-6    dy=-32   z=0   [x16]
5324/992:  E914       JMPL   $5228   ; -> TRI27

FRM10: (JSRL $993)
;   refs: DVG  $507A
5326/993:  F908       SVEC   u=16  dx=0     dy=16    z=0
5328/994:  C88D       JSRL   $511A   ; -> TRI10
532A/995:  FE08       SVEC   u=16  dx=0     dy=-32   z=0
532C/996:  E91D       JMPL   $523A   ; -> TRI30

FRM11: (JSRL $997)
;   refs: DVG  $507C
532E/997:  4200 0460  VCTR   s=4   dx=-3    dy=16    z=0   [x32]
5332/999:  C896       JSRL   $512C   ; -> TRI11
5334/99A:  5600 0060  VCTR   s=5   dx=6     dy=-32   z=0   [x16]
5338/99C:  E926       JMPL   $524C   ; -> TRI31

FRM12: (JSRL $99D)
;   refs: DVG  $507E
533A/99D:  33C0 0580  VCTR   s=3   dx=-6    dy=15    z=0   [x64]
533E/99F:  C89F       JSRL   $513E   ; -> TRI12
5340/9A0:  47C0 0180  VCTR   s=4   dx=12    dy=-30   z=0   [x32]
5344/9A2:  E92F       JMPL   $525E   ; -> TRI32

FRM13: (JSRL $9A3)
;   refs: DVG  $5080
5346/9A3:  3340 0640  VCTR   s=3   dx=-9    dy=13    z=0   [x64]
534A/9A5:  C8A8       JSRL   $5150   ; -> TRI13
534C/9A6:  4740 0240  VCTR   s=4   dx=18    dy=-26   z=0   [x32]
5350/9A8:  E938       JMPL   $5270   ; -> TRI33

FRM14: (JSRL $9A9)
;   refs: DVG  $5082
5352/9A9:  32C0 06C0  VCTR   s=3   dx=-11   dy=11    z=0   [x64]
5356/9AB:  C8B1       JSRL   $5162   ; -> TRI14
5358/9AC:  46C0 02C0  VCTR   s=4   dx=22    dy=-22   z=0   [x32]
535C/9AE:  E941       JMPL   $5282   ; -> TRI34

FRM15: (JSRL $9AF)
;   refs: DVG  $5084
535E/9AF:  3240 0740  VCTR   s=3   dx=-13   dy=9     z=0   [x64]
5362/9B1:  C8BA       JSRL   $5174   ; -> TRI15
5364/9B2:  4640 0340  VCTR   s=4   dx=26    dy=-18   z=0   [x32]
5368/9B4:  E94A       JMPL   $5294   ; -> TRI35

FRM16: (JSRL $9B5)
;   refs: DVG  $5086
536A/9B5:  3180 07C0  VCTR   s=3   dx=-15   dy=6     z=0   [x64]
536E/9B7:  C8C3       JSRL   $5186   ; -> TRI16
5370/9B8:  4580 03C0  VCTR   s=4   dx=30    dy=-12   z=0   [x32]
5374/9BA:  E953       JMPL   $52A6   ; -> TRI36

FRM17: (JSRL $9BB)
;   refs: DVG  $5088
5376/9BB:  4060 0600  VCTR   s=4   dx=-16   dy=3     z=0   [x32]
537A/9BD:  C8CC       JSRL   $5198   ; -> TRI17
537C/9BE:  5460 0200  VCTR   s=5   dx=32    dy=-6    z=0   [x16]
5380/9C0:  E95C       JMPL   $52B8   ; -> TRI37

CPMGL: (JSRL $9C1)
;   refs: none found - unreferenced art, reached via a computed word, or entered by fall-through
5382/9C1:  A080 01A0  LABS   size=0   x=416  y=128 
5386/9C3:  7000 0000  WAIT   t=7                  z=0

ASTMSG: (JSRL $9C5)
;   refs: none found - unreferenced art, reached via a computed word, or entered by fall-through
538A/9C5:  C9D7       JSRL   $53AE   ; -> CIRCL
538C/9C6:  3180 0200  VCTR   s=3   dx=8     dy=6     z=0   [x64]
5390/9C8:  F875       SVEC   u=4   dx=-4    dy=0     z=7
5392/9C9:  FD70       SVEC   u=4   dx=0     dy=-4    z=7
5394/9CA:  F871       SVEC   u=4   dx=4     dy=0     z=7
5396/9CB:  3480 0200  VCTR   s=3   dx=8     dy=-2    z=0   [x64]
539A/9CD:  C9D7       JSRL   $53AE   ; -> CIRCL
539C/9CE:  F901       SVEC   u=4   dx=4     dy=4     z=0
539E/9CF:  F871       SVEC   u=4   dx=4     dy=0     z=7
53A0/9D0:  1300 7000  VCTR   s=1   dx=0     dy=3     z=7   [x256]
53A4/9D2:  F875       SVEC   u=4   dx=-4    dy=0     z=7
53A6/9D3:  F770       SVEC   u=2   dx=0     dy=-6    z=7
53A8/9D4:  34C0 0300  VCTR   s=3   dx=12    dy=-3    z=0   [x64]
53AC/9D6:  D000       RTSL

CIRCL: (JSRL $9D7)
;   refs: DVG  $538A
;   refs: DVG  $539A
53AE/9D7:  F573       SVEC   u=2   dx=6     dy=-2    z=7
53B0/9D8:  F173       SVEC   u=2   dx=6     dy=2     z=7
53B2/9D9:  F178       SVEC   u=8   dx=0     dy=8     z=7
53B4/9DA:  F177       SVEC   u=2   dx=-6    dy=2     z=7
53B6/9DB:  F577       SVEC   u=2   dx=-6    dy=-2    z=7
53B8/9DC:  F578       SVEC   u=8   dx=0     dy=-8    z=7
53BA/9DD:  D000       RTSL

SHIPS: (JSRL $9DE)
;   refs: none found - unreferenced art, reached via a computed word, or entered by fall-through
53BC/9DE:  1200 3E28  VCTR   s=1   dx=-552  dy=512   z=3   [raw]
53C0/9E0:  6954 957F  VCTR   s=6   dx=-383  dy=340   z=9   [raw]
53C4/9E2:  B4AB       HALT

SHIPSV: (JSRL $9E3)
;   refs: none found - unreferenced art, reached via a computed word, or entered by fall-through
53C6/9E3:  5600 0580  VCTR   s=5   dx=-24   dy=-32   z=0   [x16]
53CA/9E5:  5080 0380  VCTR   s=5   dx=56    dy=8     z=0   [x16]
53CE/9E7:  F909       SVEC   u=16  dx=16    dy=16    z=0
53D0/9E8:  5180 0700  VCTR   s=5   dx=-48   dy=24    z=0   [x16]
53D4/9EA:  5580 0700  VCTR   s=5   dx=-48   dy=-24   z=0   [x16]
53D8/9EC:  FD09       SVEC   u=16  dx=16    dy=-16   z=0
53DA/9ED:  5480 0380  VCTR   s=5   dx=56    dy=-8    z=0   [x16]
53DE/9EF:  6300 04C0  VCTR   s=6   dx=-24   dy=96    z=0   [x8]
53E2/9F1:  6700 04C0  VCTR   s=6   dx=-24   dy=-96   z=0   [x8]
53E6/9F3:  F60B       SVEC   u=8   dx=24    dy=-16   z=0
53E8/9F4:  F20B       SVEC   u=8   dx=24    dy=16    z=0

SHIP01: (JSRL $9F5)
;   refs: none found - unreferenced art, reached via a computed word, or entered by fall-through
53EA/9F5:  5620 0550  VCTR   s=5   dx=-21   dy=-34   z=0   [x16]
53EE/9F7:  50D0 0370  VCTR   s=5   dx=55    dy=13    z=0   [x16]
53F2/9F9:  4240 01E0  VCTR   s=4   dx=15    dy=18    z=0   [x32]
53F6/9FB:  5130 0730  VCTR   s=5   dx=-51   dy=19    z=0   [x16]
53FA/9FD:  55D0 06D0  VCTR   s=5   dx=-45   dy=-29   z=0   [x16]
53FE/9FF:  45C0 0240  VCTR   s=4   dx=18    dy=-14   z=0   [x32]
5402/A01:  5420 0380  VCTR   s=5   dx=56    dy=-2    z=0   [x16]
5406/A03:  62E8 0508  VCTR   s=6   dx=-33   dy=93    z=0   [x8]
540A/A05:  6710 0478  VCTR   s=6   dx=-15   dy=-98   z=0   [x8]
540E/A07:  45C0 0340  VCTR   s=4   dx=26    dy=-14   z=0   [x32]
5412/A09:  4260 02C0  VCTR   s=4   dx=22    dy=19    z=0   [x32]

SHIP02: (JSRL $A0B)
;   refs: none found - unreferenced art, reached via a computed word, or entered by fall-through
5416/A0B:  5640 0510  VCTR   s=5   dx=-17   dy=-36   z=0   [x16]
541A/A0D:  5130 0350  VCTR   s=5   dx=53    dy=19    z=0   [x16]
541E/A0F:  4260 01A0  VCTR   s=4   dx=13    dy=19    z=0   [x32]
5422/A11:  50E0 0740  VCTR   s=5   dx=-52   dy=14    z=0   [x16]
5426/A13:  5610 06B0  VCTR   s=5   dx=-43   dy=-33   z=0   [x16]
542A/A15:  45A0 0260  VCTR   s=4   dx=19    dy=-13   z=0   [x32]
542E/A17:  5030 0390  VCTR   s=5   dx=57    dy=3     z=0   [x16]
5432/A19:  62D0 0550  VCTR   s=6   dx=-42   dy=90    z=0   [x8]
5436/A1B:  6718 0428  VCTR   s=6   dx=-5    dy=-99   z=0   [x8]
543A/A1D:  4560 0340  VCTR   s=4   dx=26    dy=-11   z=0   [x32]
543E/A1F:  4280 02A0  VCTR   s=4   dx=21    dy=20    z=0   [x32]

SHIP03: (JSRL $A21)
;   refs: none found - unreferenced art, reached via a computed word, or entered by fall-through
5442/A21:  5660 04E0  VCTR   s=5   dx=-14   dy=-38   z=0   [x16]
5446/A23:  5180 0340  VCTR   s=5   dx=52    dy=24    z=0   [x16]
544A/A25:  4280 0140  VCTR   s=4   dx=10    dy=20    z=0   [x32]
544E/A27:  5090 0750  VCTR   s=5   dx=-53   dy=9     z=0   [x16]
5452/A29:  5650 0670  VCTR   s=5   dx=-39   dy=-37   z=0   [x16]
5456/A2B:  4540 0280  VCTR   s=4   dx=20    dy=-10   z=0   [x32]
545A/A2D:  5080 0380  VCTR   s=5   dx=56    dy=8     z=0   [x16]
545E/A2F:  62A8 0598  VCTR   s=6   dx=-51   dy=85    z=0   [x8]
5462/A31:  6718 0028  VCTR   s=6   dx=5     dy=-99   z=0   [x8]
5466/A33:  4500 0380  VCTR   s=4   dx=28    dy=-8    z=0   [x32]
546A/A35:  42C0 0240  VCTR   s=4   dx=18    dy=22    z=0   [x32]

SHIP04: (JSRL $A37)
;   refs: none found - unreferenced art, reached via a computed word, or entered by fall-through
546E/A37:  5670 04A0  VCTR   s=5   dx=-10   dy=-39   z=0   [x16]
5472/A39:  51D0 0310  VCTR   s=5   dx=49    dy=29    z=0   [x16]
5476/A3B:  42A0 0100  VCTR   s=4   dx=8     dy=21    z=0   [x32]
547A/A3D:  5040 0750  VCTR   s=5   dx=-53   dy=4     z=0   [x16]
547E/A3F:  5690 0630  VCTR   s=5   dx=-35   dy=-41   z=0   [x16]
5482/A41:  4500 02A0  VCTR   s=4   dx=21    dy=-8    z=0   [x32]
5486/A43:  50E0 0360  VCTR   s=5   dx=54    dy=14    z=0   [x16]
548A/A45:  6278 05D0  VCTR   s=6   dx=-58   dy=79    z=0   [x8]
548E/A47:  6710 0070  VCTR   s=6   dx=14    dy=-98   z=0   [x8]
5492/A49:  44A0 0380  VCTR   s=4   dx=28    dy=-5    z=0   [x32]
5496/A4B:  F30A       SVEC   u=8   dx=16    dy=24    z=0

SHIP05: (JSRL $A4C)
;   refs: none found - unreferenced art, reached via a computed word, or entered by fall-through
5498/A4C:  5680 0460  VCTR   s=5   dx=-6    dy=-40   z=0   [x16]
549C/A4E:  5220 02E0  VCTR   s=5   dx=46    dy=34    z=0   [x16]
54A0/A50:  42C0 00C0  VCTR   s=4   dx=6     dy=22    z=0   [x32]
54A4/A52:  5420 0760  VCTR   s=5   dx=-54   dy=-2    z=0   [x16]
54A8/A54:  56C0 05F0  VCTR   s=5   dx=-31   dy=-44   z=0   [x16]
54AC/A56:  44C0 02C0  VCTR   s=4   dx=22    dy=-6    z=0   [x32]
54B0/A58:  5130 0350  VCTR   s=5   dx=53    dy=19    z=0   [x16]
54B4/A5A:  6248 0610  VCTR   s=6   dx=-66   dy=73    z=0   [x8]
54B8/A5C:  6700 00C0  VCTR   s=6   dx=24    dy=-96   z=0   [x8]
54BC/A5E:  4440 03A0  VCTR   s=4   dx=29    dy=-2    z=0   [x32]
54C0/A60:  4320 01A0  VCTR   s=4   dx=13    dy=25    z=0   [x32]

SHIP06: (JSRL $A62)
;   refs: none found - unreferenced art, reached via a computed word, or entered by fall-through
54C4/A62:  5680 0420  VCTR   s=5   dx=-2    dy=-40   z=0   [x16]
54C8/A64:  5260 02A0  VCTR   s=5   dx=42    dy=38    z=0   [x16]
54CC/A66:  42C0 0080  VCTR   s=4   dx=4     dy=22    z=0   [x32]
54D0/A68:  5470 0750  VCTR   s=5   dx=-53   dy=-7    z=0   [x16]
54D4/A6A:  56E0 05A0  VCTR   s=5   dx=-26   dy=-46   z=0   [x16]
54D8/A6C:  44A0 02C0  VCTR   s=4   dx=22    dy=-5    z=0   [x32]
54DC/A6E:  5190 0330  VCTR   s=5   dx=51    dy=25    z=0   [x16]
54E0/A70:  6210 0650  VCTR   s=6   dx=-74   dy=66    z=0   [x8]
54E4/A72:  66E8 0110  VCTR   s=6   dx=34    dy=-93   z=0   [x8]
54E8/A74:  4000 03A0  VCTR   s=4   dx=29    dy=0     z=0   [x32]
54EC/A76:  4360 0160  VCTR   s=4   dx=11    dy=27    z=0   [x32]

SHIP07: (JSRL $A78)
;   refs: none found - unreferenced art, reached via a computed word, or entered by fall-through
54F0/A78:  5680 0020  VCTR   s=5   dx=2     dy=-40   z=0   [x16]
54F4/A7A:  52A0 0260  VCTR   s=5   dx=38    dy=42    z=0   [x16]
54F8/A7C:  42C0 0040  VCTR   s=4   dx=2     dy=22    z=0   [x32]
54FC/A7E:  54C0 0740  VCTR   s=5   dx=-52   dy=-12   z=0   [x16]
5500/A80:  5710 0560  VCTR   s=5   dx=-22   dy=-49   z=0   [x16]
5504/A82:  4440 02C0  VCTR   s=4   dx=22    dy=-2    z=0   [x32]
5508/A84:  51D0 0310  VCTR   s=5   dx=49    dy=29    z=0   [x16]
550C/A86:  61D8 0680  VCTR   s=6   dx=-80   dy=59    z=0   [x8]
5510/A88:  66C8 0158  VCTR   s=6   dx=43    dy=-89   z=0   [x8]
5514/A8A:  4060 0380  VCTR   s=4   dx=28    dy=3     z=0   [x32]
5518/A8C:  4360 0120  VCTR   s=4   dx=9     dy=27    z=0   [x32]

SHIP10: (JSRL $A8E)
;   refs: none found - unreferenced art, reached via a computed word, or entered by fall-through
551C/A8E:  5680 0060  VCTR   s=5   dx=6     dy=-40   z=0   [x16]
5520/A90:  52E0 0220  VCTR   s=5   dx=34    dy=46    z=0   [x16]
5524/A92:  42C0 0000  VCTR   s=4   dx=0     dy=22    z=0   [x32]
5528/A94:  5510 0730  VCTR   s=5   dx=-51   dy=-17   z=0   [x16]
552C/A96:  5730 0510  VCTR   s=5   dx=-17   dy=-51   z=0   [x16]
5530/A98:  4000 02C0  VCTR   s=4   dx=22    dy=0     z=0   [x32]
5534/A9A:  5220 02E0  VCTR   s=5   dx=46    dy=34    z=0   [x16]
5538/A9C:  6198 06A8  VCTR   s=6   dx=-85   dy=51    z=0   [x8]
553C/A9E:  66A8 0198  VCTR   s=6   dx=51    dy=-85   z=0   [x8]
5540/AA0:  40C0 0380  VCTR   s=4   dx=28    dy=6     z=0   [x32]
5544/AA2:  4380 00C0  VCTR   s=4   dx=6     dy=28    z=0   [x32]

SHIP17: (JSRL $AA4)
;   refs: none found - unreferenced art, reached via a computed word, or entered by fall-through
5548/AA4:  5600 0580  VCTR   s=5   dx=-24   dy=-32   z=0   [x16]
554C/AA6:  5080 7380  VCTR   s=5   dx=56    dy=8     z=7   [x16]
5550/AA8:  F979       SVEC   u=16  dx=16    dy=16    z=7
5552/AA9:  5180 7700  VCTR   s=5   dx=-48   dy=24    z=7   [x16]
5556/AAB:  5580 7700  VCTR   s=5   dx=-48   dy=-24   z=7   [x16]
555A/AAD:  FD79       SVEC   u=16  dx=16    dy=-16   z=7
555C/AAE:  5480 7380  VCTR   s=5   dx=56    dy=-8    z=7   [x16]
5560/AB0:  6300 74C0  VCTR   s=6   dx=-24   dy=96    z=7   [x8]
5564/AB2:  6700 74C0  VCTR   s=6   dx=-24   dy=-96   z=7   [x8]
5568/AB4:  7080 0220  VCTR   s=7   dx=136   dy=32    z=0   [x4]
556C/AB6:  D000       RTSL

CHAR_A: (JSRL $AB7)
;   also CHAR.A in the linker map
;   refs: DVG  $570E
;   refs: DVG  $57D6
;   refs: DVG  $57F6
556E/AB7:  FA70       SVEC   u=4   dx=0     dy=8     z=7
5570/AB8:  F272       SVEC   u=2   dx=4     dy=4     z=7
5572/AB9:  F672       SVEC   u=2   dx=4     dy=-4    z=7
5574/ABA:  FE70       SVEC   u=4   dx=0     dy=-8    z=7
5576/ABB:  F906       SVEC   u=4   dx=-8    dy=4     z=0
5578/ABC:  F872       SVEC   u=4   dx=8     dy=0     z=7
557A/ABD:  F602       SVEC   u=2   dx=4     dy=-4    z=0
557C/ABE:  D000       RTSL

CHAR_B: (JSRL $ABF)
;   also CHAR.B in the linker map
;   refs: DVG  $5710
;   refs: DVG  $57D4
557E/ABF:  FB70       SVEC   u=4   dx=0     dy=12    z=7
5580/AC0:  F073       SVEC   u=2   dx=6     dy=0     z=7
5582/AC1:  F571       SVEC   u=2   dx=2     dy=-2    z=7
5584/AC2:  F570       SVEC   u=2   dx=0     dy=-2    z=7
5586/AC3:  F575       SVEC   u=2   dx=-2    dy=-2    z=7
5588/AC4:  F077       SVEC   u=2   dx=-6    dy=0     z=7
558A/AC5:  F003       SVEC   u=2   dx=6     dy=0     z=0
558C/AC6:  F571       SVEC   u=2   dx=2     dy=-2    z=7
558E/AC7:  F570       SVEC   u=2   dx=0     dy=-2    z=7
5590/AC8:  F575       SVEC   u=2   dx=-2    dy=-2    z=7
5592/AC9:  F077       SVEC   u=2   dx=-6    dy=0     z=7
5594/ACA:  EB0A       JMPL   $5614   ; -> CHAR_SPACE

CHAR_C: (JSRL $ACB)
;   also CHAR.C in the linker map
;   refs: DVG  $5712
5596/ACB:  FB70       SVEC   u=4   dx=0     dy=12    z=7
5598/ACC:  F872       SVEC   u=4   dx=8     dy=0     z=7
559A/ACD:  FF06       SVEC   u=4   dx=-8    dy=-12   z=0
559C/ACE:  EB58       JMPL   $56B0   ; -> UNDERL

CHAR_D: (JSRL $ACF)
;   also CHAR.D in the linker map
;   refs: DVG  $5714
559E/ACF:  FB70       SVEC   u=4   dx=0     dy=12    z=7
55A0/AD0:  F072       SVEC   u=2   dx=4     dy=0     z=7
55A2/AD1:  F672       SVEC   u=2   dx=4     dy=-4    z=7
55A4/AD2:  F670       SVEC   u=2   dx=0     dy=-4    z=7
55A6/AD3:  F676       SVEC   u=2   dx=-4    dy=-4    z=7
55A8/AD4:  F076       SVEC   u=2   dx=-4    dy=0     z=7
55AA/AD5:  EB0A       JMPL   $5614   ; -> CHAR_SPACE

CHAR_E: (JSRL $AD6)
;   also CHAR.E in the linker map
;   refs: DVG  $5716
;   refs: DVG  $57DE
;   refs: DVG  $57F2
55AC/AD6:  F872       SVEC   u=4   dx=8     dy=0     z=7
55AE/AD7:  F806       SVEC   u=4   dx=-8    dy=0     z=0

CHAR_F: (JSRL $AD8)
;   also CHAR.F in the linker map
;   refs: DVG  $5718
55B0/AD8:  FB70       SVEC   u=4   dx=0     dy=12    z=7
55B2/AD9:  F872       SVEC   u=4   dx=8     dy=0     z=7
55B4/ADA:  F705       SVEC   u=2   dx=-2    dy=-6    z=0
55B6/ADB:  F077       SVEC   u=2   dx=-6    dy=0     z=7

CHARF1: (JSRL $ADC)
;   refs: DVG  $5620
55B8/ADC:  F700       SVEC   u=2   dx=0     dy=-6    z=0
55BA/ADD:  F803       SVEC   u=4   dx=12    dy=0     z=0
55BC/ADE:  D000       RTSL

CHAR_G: (JSRL $ADF)
;   also CHAR.G in the linker map
;   refs: DVG  $571A
;   refs: DVG  $57FE
55BE/ADF:  FB70       SVEC   u=4   dx=0     dy=12    z=7
55C0/AE0:  F872       SVEC   u=4   dx=8     dy=0     z=7
55C2/AE1:  F670       SVEC   u=2   dx=0     dy=-4    z=7
55C4/AE2:  F606       SVEC   u=2   dx=-4    dy=-4    z=0
55C6/AE3:  F072       SVEC   u=2   dx=4     dy=0     z=7
55C8/AE4:  F670       SVEC   u=2   dx=0     dy=-4    z=7
55CA/AE5:  EB09       JMPL   $5612   ; -> CHAR01

CHAR_H: (JSRL $AE6)
;   also CHAR.H in the linker map
;   refs: DVG  $571C
55CC/AE6:  FB70       SVEC   u=4   dx=0     dy=12    z=7
55CE/AE7:  F700       SVEC   u=2   dx=0     dy=-6    z=0
55D0/AE8:  F872       SVEC   u=4   dx=8     dy=0     z=7
55D2/AE9:  F300       SVEC   u=2   dx=0     dy=6     z=0
55D4/AEA:  EB71       JMPL   $56E2   ; -> CHAR72

CHAR_I: (JSRL $AEB)
;   also CHAR.I in the linker map
;   refs: DVG  $571E
;   refs: DVG  $57FA
55D6/AEB:  F872       SVEC   u=4   dx=8     dy=0     z=7
55D8/AEC:  FB06       SVEC   u=4   dx=-8    dy=12    z=0

CHARI1: (JSRL $AED)
;   refs: DVG  $5664
55DA/AED:  F872       SVEC   u=4   dx=8     dy=0     z=7
55DC/AEE:  F006       SVEC   u=2   dx=-4    dy=0     z=0

CHARI2: (JSRL $AEF)
;   refs: DVG  $56A4
55DE/AEF:  FF70       SVEC   u=4   dx=0     dy=-12   z=7
55E0/AF0:  F802       SVEC   u=4   dx=8     dy=0     z=0
55E2/AF1:  D000       RTSL

CHAR_J: (JSRL $AF2)
;   also CHAR.J in the linker map
;   refs: DVG  $5720
55E4/AF2:  F200       SVEC   u=2   dx=0     dy=4     z=0
55E6/AF3:  F672       SVEC   u=2   dx=4     dy=-4    z=7
55E8/AF4:  F072       SVEC   u=2   dx=4     dy=0     z=7
55EA/AF5:  EB36       JMPL   $566C   ; -> CHARU1

CHAR_K: (JSRL $AF6)
;   also CHAR.K in the linker map
;   refs: DVG  $5722
;   refs: DVG  $57DA
55EC/AF6:  FB70       SVEC   u=4   dx=0     dy=12    z=7
55EE/AF7:  F003       SVEC   u=2   dx=6     dy=0     z=0
55F0/AF8:  F777       SVEC   u=2   dx=-6    dy=-6    z=7
55F2/AF9:  F773       SVEC   u=2   dx=6     dy=-6    z=7
55F4/AFA:  F003       SVEC   u=2   dx=6     dy=0     z=0
55F6/AFB:  D000       RTSL

CHAR_L: (JSRL $AFC)
;   also CHAR.L in the linker map
;   refs: DVG  $5724
55F8/AFC:  FB00       SVEC   u=4   dx=0     dy=12    z=0
55FA/AFD:  FF70       SVEC   u=4   dx=0     dy=-12   z=7
55FC/AFE:  EB58       JMPL   $56B0   ; -> UNDERL

CHAR_M: (JSRL $AFF)
;   also CHAR.M in the linker map
;   refs: DVG  $5726
55FE/AFF:  FB70       SVEC   u=4   dx=0     dy=12    z=7
5600/B00:  F672       SVEC   u=2   dx=4     dy=-4    z=7
5602/B01:  F272       SVEC   u=2   dx=4     dy=4     z=7
5604/B02:  EB71       JMPL   $56E2   ; -> CHAR72

CHAR_N: (JSRL $B03)
;   also CHAR.N in the linker map
;   refs: DVG  $5728
;   refs: DVG  $57D8
;   refs: DVG  $57FC
5606/B03:  FB70       SVEC   u=4   dx=0     dy=12    z=7
5608/B04:  FF72       SVEC   u=4   dx=8     dy=-12   z=7
560A/B05:  EB36       JMPL   $566C   ; -> CHARU1

CHAR_O: (JSRL $B06)
;   also CHAR.O in the linker map
;   glyph shared with '0'
;   refs: DVG  $56FA
;   refs: DVG  $572A
;   refs: DVG  $57E4
560C/B06:  FB70       SVEC   u=4   dx=0     dy=12    z=7
560E/B07:  F872       SVEC   u=4   dx=8     dy=0     z=7
5610/B08:  FF70       SVEC   u=4   dx=0     dy=-12   z=7

CHAR01: (JSRL $B09)
;   refs: DVG  $55CA
5612/B09:  F876       SVEC   u=4   dx=-8    dy=0     z=7

CHAR_SPACE: (JSRL $B0A)
;   also CHAR. in the linker map
;   refs: DVG  $5594
;   refs: DVG  $55AA
;   refs: DVG  $56F8
;   refs: DVG  $57DC
5614/B0A:  F803       SVEC   u=4   dx=12    dy=0     z=0
5616/B0B:  D000       RTSL

CHAR_P: (JSRL $B0C)
;   also CHAR.P in the linker map
;   refs: DVG  $572C
5618/B0C:  FB70       SVEC   u=4   dx=0     dy=12    z=7
561A/B0D:  F872       SVEC   u=4   dx=8     dy=0     z=7
561C/B0E:  F770       SVEC   u=2   dx=0     dy=-6    z=7
561E/B0F:  F876       SVEC   u=4   dx=-8    dy=0     z=7
5620/B10:  EADC       JMPL   $55B8   ; -> CHARF1

CHAR_Q: (JSRL $B11)
;   also CHAR.Q in the linker map
;   refs: DVG  $572E
5622/B11:  FB70       SVEC   u=4   dx=0     dy=12    z=7
5624/B12:  F872       SVEC   u=4   dx=8     dy=0     z=7
5626/B13:  FE70       SVEC   u=4   dx=0     dy=-8    z=7
5628/B14:  F676       SVEC   u=2   dx=-4    dy=-4    z=7
562A/B15:  F076       SVEC   u=2   dx=-4    dy=0     z=7
562C/B16:  F202       SVEC   u=2   dx=4     dy=4     z=0
562E/B17:  F672       SVEC   u=2   dx=4     dy=-4    z=7
5630/B18:  EB59       JMPL   $56B2   ; -> CHAR21

CHAR_R: (JSRL $B19)
;   also CHAR.R in the linker map
;   refs: DVG  $5730
;   refs: DVG  $57E0
;   refs: DVG  $57E2
;   refs: DVG  $57E6
;   refs: DVG  $57F4
5632/B19:  FB70       SVEC   u=4   dx=0     dy=12    z=7
5634/B1A:  F872       SVEC   u=4   dx=8     dy=0     z=7
5636/B1B:  F770       SVEC   u=2   dx=0     dy=-6    z=7
5638/B1C:  F876       SVEC   u=4   dx=-8    dy=0     z=7
563A/B1D:  F001       SVEC   u=2   dx=2     dy=0     z=0
563C/B1E:  F773       SVEC   u=2   dx=6     dy=-6    z=7
563E/B1F:  EB59       JMPL   $56B2   ; -> CHAR21

Z.5: (JSRL $B20)
;   refs: none found - unreferenced art, reached via a computed word, or entered by fall-through
5640/B20:  F200       SVEC   u=2   dx=0     dy=4     z=0
5642/B21:  FA73       SVEC   u=4   dx=12    dy=8     z=7
5644/B22:  F906       SVEC   u=4   dx=-8    dy=4     z=0
5646/B23:  FE70       SVEC   u=4   dx=0     dy=-8    z=7
5648/B24:  F601       SVEC   u=2   dx=2     dy=-4    z=0
564A/B25:  F072       SVEC   u=2   dx=4     dy=0     z=7
564C/B26:  F670       SVEC   u=2   dx=0     dy=-4    z=7
564E/B27:  F076       SVEC   u=2   dx=-4    dy=0     z=7
5650/B28:  F670       SVEC   u=2   dx=0     dy=-4    z=7
5652/B29:  F072       SVEC   u=2   dx=4     dy=0     z=7
5654/B2A:  D000       RTSL

CHAR_S: (JSRL $B2B)
;   also CHAR.S in the linker map
;   glyph shared with '5'
;   refs: DVG  $5704
;   refs: DVG  $5732
;   refs: DVG  $57F8
5656/B2B:  F872       SVEC   u=4   dx=8     dy=0     z=7
5658/B2C:  F370       SVEC   u=2   dx=0     dy=6     z=7
565A/B2D:  F876       SVEC   u=4   dx=-8    dy=0     z=7
565C/B2E:  F370       SVEC   u=2   dx=0     dy=6     z=7
565E/B2F:  F872       SVEC   u=4   dx=8     dy=0     z=7
5660/B30:  EB37       JMPL   $566E   ; -> CHARU2

CHAR_T: (JSRL $B31)
;   also CHAR.T in the linker map
;   refs: DVG  $5734
5662/B31:  FB00       SVEC   u=4   dx=0     dy=12    z=0
5664/B32:  EAED       JMPL   $55DA   ; -> CHARI1

CHAR_U: (JSRL $B33)
;   also CHAR.U in the linker map
;   refs: DVG  $5736
5666/B33:  FB00       SVEC   u=4   dx=0     dy=12    z=0
5668/B34:  FF70       SVEC   u=4   dx=0     dy=-12   z=7
566A/B35:  F872       SVEC   u=4   dx=8     dy=0     z=7

CHARU1: (JSRL $B36)
;   refs: DVG  $55EA
;   refs: DVG  $560A
;   refs: DVG  $5682
566C/B36:  FB70       SVEC   u=4   dx=0     dy=12    z=7

CHARU2: (JSRL $B37)
;   refs: DVG  $5660
;   refs: DVG  $5678
566E/B37:  FF01       SVEC   u=4   dx=4     dy=-12   z=0
5670/B38:  D000       RTSL

CHAR_V: (JSRL $B39)
;   also CHAR.V in the linker map
;   refs: DVG  $5738
5672/B39:  FB00       SVEC   u=4   dx=0     dy=12    z=0
5674/B3A:  FF71       SVEC   u=4   dx=4     dy=-12   z=7
5676/B3B:  FB71       SVEC   u=4   dx=4     dy=12    z=7
5678/B3C:  EB37       JMPL   $566E   ; -> CHARU2

CHAR_W: (JSRL $B3D)
;   also CHAR.W in the linker map
;   refs: DVG  $573A
567A/B3D:  FB00       SVEC   u=4   dx=0     dy=12    z=0
567C/B3E:  FF70       SVEC   u=4   dx=0     dy=-12   z=7
567E/B3F:  F272       SVEC   u=2   dx=4     dy=4     z=7
5680/B40:  F672       SVEC   u=2   dx=4     dy=-4    z=7
5682/B41:  EB36       JMPL   $566C   ; -> CHARU1

CHAR_X: (JSRL $B42)
;   also CHAR.X in the linker map
;   refs: DVG  $573C
5684/B42:  FB72       SVEC   u=4   dx=8     dy=12    z=7
5686/B43:  F806       SVEC   u=4   dx=-8    dy=0     z=0
5688/B44:  FF72       SVEC   u=4   dx=8     dy=-12   z=7
568A/B45:  EB72       JMPL   $56E4   ; -> CHAR73

CHAR_Y: (JSRL $B46)
;   also CHAR.Y in the linker map
;   refs: DVG  $573E
568C/B46:  F002       SVEC   u=2   dx=4     dy=0     z=0
568E/B47:  FA70       SVEC   u=4   dx=0     dy=8     z=7
5690/B48:  F276       SVEC   u=2   dx=-4    dy=4     z=7
5692/B49:  F802       SVEC   u=4   dx=8     dy=0     z=0
5694/B4A:  F676       SVEC   u=2   dx=-4    dy=-4    z=7
5696/B4B:  FE02       SVEC   u=4   dx=8     dy=-8    z=0
5698/B4C:  D000       RTSL

CHAR_Z: (JSRL $B4D)
;   also CHAR.Z in the linker map
;   refs: DVG  $5740
569A/B4D:  FB00       SVEC   u=4   dx=0     dy=12    z=0
569C/B4E:  F872       SVEC   u=4   dx=8     dy=0     z=7
569E/B4F:  FF76       SVEC   u=4   dx=-8    dy=-12   z=7
56A0/B50:  EB58       JMPL   $56B0   ; -> UNDERL

CHAR_1: (JSRL $B51)
;   also CHAR.1 in the linker map
;   refs: DVG  $56FC
56A2/B51:  FB01       SVEC   u=4   dx=4     dy=12    z=0
56A4/B52:  EAEF       JMPL   $55DE   ; -> CHARI2

CHAR_2: (JSRL $B53)
;   also CHAR.2 in the linker map
;   refs: DVG  $56FE
56A6/B53:  FB00       SVEC   u=4   dx=0     dy=12    z=0
56A8/B54:  F872       SVEC   u=4   dx=8     dy=0     z=7
56AA/B55:  F770       SVEC   u=2   dx=0     dy=-6    z=7
56AC/B56:  F876       SVEC   u=4   dx=-8    dy=0     z=7
56AE/B57:  F770       SVEC   u=2   dx=0     dy=-6    z=7

UNDERL: (JSRL $B58)
;   refs: 6502 $66EE
;   refs: DVG  $559C
;   refs: DVG  $55FC
;   refs: DVG  $56A0
56B0/B58:  F872       SVEC   u=4   dx=8     dy=0     z=7

CHAR21: (JSRL $B59)
;   refs: DVG  $5630
;   refs: DVG  $563E
56B2/B59:  F002       SVEC   u=2   dx=4     dy=0     z=0
56B4/B5A:  D000       RTSL

CHAR_3: (JSRL $B5B)
;   also CHAR.3 in the linker map
;   refs: DVG  $5700
56B6/B5B:  FB00       SVEC   u=4   dx=0     dy=12    z=0

CHAR31: (JSRL $B5C)
;   refs: DVG  $56EC
56B8/B5C:  F872       SVEC   u=4   dx=8     dy=0     z=7
56BA/B5D:  FF70       SVEC   u=4   dx=0     dy=-12   z=7
56BC/B5E:  F876       SVEC   u=4   dx=-8    dy=0     z=7
56BE/B5F:  F300       SVEC   u=2   dx=0     dy=6     z=0
56C0/B60:  F872       SVEC   u=4   dx=8     dy=0     z=7
56C2/B61:  F702       SVEC   u=2   dx=4     dy=-6    z=0
56C4/B62:  D000       RTSL

CHAR_4: (JSRL $B63)
;   also CHAR.4 in the linker map
;   refs: DVG  $5702
56C6/B63:  FB00       SVEC   u=4   dx=0     dy=12    z=0
56C8/B64:  F770       SVEC   u=2   dx=0     dy=-6    z=7
56CA/B65:  F872       SVEC   u=4   dx=8     dy=0     z=7
56CC/B66:  F300       SVEC   u=2   dx=0     dy=6     z=0
56CE/B67:  EB71       JMPL   $56E2   ; -> CHAR72

CHAR_6: (JSRL $B68)
;   also CHAR.6 in the linker map
;   refs: DVG  $5706
56D0/B68:  F300       SVEC   u=2   dx=0     dy=6     z=0
56D2/B69:  F872       SVEC   u=4   dx=8     dy=0     z=7
56D4/B6A:  F770       SVEC   u=2   dx=0     dy=-6    z=7
56D6/B6B:  F876       SVEC   u=4   dx=-8    dy=0     z=7
56D8/B6C:  FB70       SVEC   u=4   dx=0     dy=12    z=7
56DA/B6D:  FF03       SVEC   u=4   dx=12    dy=-12   z=0
56DC/B6E:  D000       RTSL

CHAR_7: (JSRL $B6F)
;   also CHAR.7 in the linker map
;   refs: DVG  $5708
56DE/B6F:  FB00       SVEC   u=4   dx=0     dy=12    z=0

CHAR71: (JSRL $B70)
;   refs: DVG  $56F6
56E0/B70:  F872       SVEC   u=4   dx=8     dy=0     z=7

CHAR72: (JSRL $B71)
;   refs: DVG  $55D4
;   refs: DVG  $5604
;   refs: DVG  $56CE
56E2/B71:  FF70       SVEC   u=4   dx=0     dy=-12   z=7

CHAR73: (JSRL $B72)
;   refs: DVG  $568A
56E4/B72:  F002       SVEC   u=2   dx=4     dy=0     z=0
56E6/B73:  D000       RTSL

JJ98: (JSRL $B74)
;   refs: DVG  $5742
56E8/B74:  CB77       JSRL   $56EE   ; -> CHAR_9

CHAR_8: (JSRL $B75)
;   also CHAR.8 in the linker map
;   refs: DVG  $570A
56EA/B75:  FB70       SVEC   u=4   dx=0     dy=12    z=7
56EC/B76:  EB5C       JMPL   $56B8   ; -> CHAR31

CHAR_9: (JSRL $B77)
;   also CHAR.9 in the linker map
;   refs: DVG  $56E8
;   refs: DVG  $570C
56EE/B77:  F802       SVEC   u=4   dx=8     dy=0     z=0
56F0/B78:  F300       SVEC   u=2   dx=0     dy=6     z=0
56F2/B79:  F876       SVEC   u=4   dx=-8    dy=0     z=7
56F4/B7A:  F370       SVEC   u=2   dx=0     dy=6     z=7
56F6/B7B:  EB70       JMPL   $56E0   ; -> CHAR71

VGMSGA: (JSRL $B7C)
;   draws: " O1234S6789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
;   refs: none found - unreferenced art, reached via a computed word, or entered by fall-through
56F8/B7C:  CB0A       JSRL   $5614   ; -> CHAR_SPACE
56FA/B7D:  CB06       JSRL   $560C   ; -> CHAR_O
56FC/B7E:  CB51       JSRL   $56A2   ; -> CHAR_1
56FE/B7F:  CB53       JSRL   $56A6   ; -> CHAR_2
5700/B80:  CB5B       JSRL   $56B6   ; -> CHAR_3
5702/B81:  CB63       JSRL   $56C6   ; -> CHAR_4
5704/B82:  CB2B       JSRL   $5656   ; -> CHAR_S
5706/B83:  CB68       JSRL   $56D0   ; -> CHAR_6
5708/B84:  CB6F       JSRL   $56DE   ; -> CHAR_7
570A/B85:  CB75       JSRL   $56EA   ; -> CHAR_8
570C/B86:  CB77       JSRL   $56EE   ; -> CHAR_9
570E/B87:  CAB7       JSRL   $556E   ; -> CHAR_A
5710/B88:  CABF       JSRL   $557E   ; -> CHAR_B
5712/B89:  CACB       JSRL   $5596   ; -> CHAR_C
5714/B8A:  CACF       JSRL   $559E   ; -> CHAR_D
5716/B8B:  CAD6       JSRL   $55AC   ; -> CHAR_E
5718/B8C:  CAD8       JSRL   $55B0   ; -> CHAR_F
571A/B8D:  CADF       JSRL   $55BE   ; -> CHAR_G
571C/B8E:  CAE6       JSRL   $55CC   ; -> CHAR_H
571E/B8F:  CAEB       JSRL   $55D6   ; -> CHAR_I
5720/B90:  CAF2       JSRL   $55E4   ; -> CHAR_J
5722/B91:  CAF6       JSRL   $55EC   ; -> CHAR_K
5724/B92:  CAFC       JSRL   $55F8   ; -> CHAR_L
5726/B93:  CAFF       JSRL   $55FE   ; -> CHAR_M
5728/B94:  CB03       JSRL   $5606   ; -> CHAR_N
572A/B95:  CB06       JSRL   $560C   ; -> CHAR_O
572C/B96:  CB0C       JSRL   $5618   ; -> CHAR_P
572E/B97:  CB11       JSRL   $5622   ; -> CHAR_Q
5730/B98:  CB19       JSRL   $5632   ; -> CHAR_R
5732/B99:  CB2B       JSRL   $5656   ; -> CHAR_S
5734/B9A:  CB31       JSRL   $5662   ; -> CHAR_T
5736/B9B:  CB33       JSRL   $5666   ; -> CHAR_U
5738/B9C:  CB39       JSRL   $5672   ; -> CHAR_V
573A/B9D:  CB3D       JSRL   $567A   ; -> CHAR_W
573C/B9E:  CB42       JSRL   $5684   ; -> CHAR_X
573E/B9F:  CB46       JSRL   $568C   ; -> CHAR_Y
5740/BA0:  CB4D       JSRL   $569A   ; -> CHAR_Z
5742/BA1:  CB74       JSRL   $56E8   ; -> JJ98

TEST1: (JSRL $BA2)
;   refs: 6502 $7EA5
5744/BA2:  A080 0000  LABS   size=0   x=0    y=128 
5748/BA4:  7000 0000  WAIT   t=7                  z=0
574C/BA6:  9000 73FF  VCTR   s=9   dx=1023  dy=0     z=7   [x1]
5750/BA8:  92FF 7000  VCTR   s=9   dx=0     dy=767   z=7   [x1]
5754/BAA:  9000 77FF  VCTR   s=9   dx=-1023 dy=0     z=7   [x1]
5758/BAC:  96FF 7000  VCTR   s=9   dx=0     dy=-767  z=7   [x1]
575C/BAE:  92FF 72FF  VCTR   s=9   dx=767   dy=767   z=7   [x1]
5760/BB0:  8600 7200  VCTR   s=8   dx=256   dy=-256  z=7   [x2]
5764/BB2:  87FE 77FE  VCTR   s=8   dx=-511  dy=-511  z=7   [x2]
5768/BB4:  9200 7600  VCTR   s=9   dx=-512  dy=512   z=7   [x1]
576C/BB6:  81FE 7200  VCTR   s=8   dx=256   dy=255   z=7   [x2]
5770/BB8:  96FF 72FF  VCTR   s=9   dx=767   dy=-767  z=7   [x1]
5774/BBA:  A37F 03FF  LABS   size=0   x=1023 y=895 
5778/BBC:  7000 0000  WAIT   t=7                  z=0
577C/BBE:  96FF 76FF  VCTR   s=9   dx=-767  dy=-767  z=7   [x1]
5780/BC0:  81FE 7600  VCTR   s=8   dx=-256  dy=255   z=7   [x2]
5784/BC2:  9200 7200  VCTR   s=9   dx=512   dy=512   z=7   [x1]
5788/BC4:  87FE 73FE  VCTR   s=8   dx=511   dy=-511  z=7   [x2]
578C/BC6:  8600 7600  VCTR   s=8   dx=-256  dy=-256  z=7   [x2]
5790/BC8:  92FF 76FF  VCTR   s=9   dx=-767  dy=767   z=7   [x1]
5794/BCA:  A1FC 01F4  LABS   size=0   x=500  y=508 
5798/BCC:  7000 0000  WAIT   t=7                  z=0
579C/BCE:  F0DB       SVEC   u=8   dx=24    dy=0     z=13
579E/BCF:  F900       SVEC   u=4   dx=0     dy=4     z=0
57A0/BD0:  F0CF       SVEC   u=8   dx=-24   dy=0     z=12
57A2/BD1:  F900       SVEC   u=4   dx=0     dy=4     z=0
57A4/BD2:  F0BB       SVEC   u=8   dx=24    dy=0     z=11
57A6/BD3:  F900       SVEC   u=4   dx=0     dy=4     z=0
57A8/BD4:  F0AF       SVEC   u=8   dx=-24   dy=0     z=10
57AA/BD5:  F900       SVEC   u=4   dx=0     dy=4     z=0
57AC/BD6:  F09B       SVEC   u=8   dx=24    dy=0     z=9
57AE/BD7:  F900       SVEC   u=4   dx=0     dy=4     z=0
57B0/BD8:  F08F       SVEC   u=8   dx=-24   dy=0     z=8
57B2/BD9:  F900       SVEC   u=4   dx=0     dy=4     z=0
57B4/BDA:  F07B       SVEC   u=8   dx=24    dy=0     z=7
57B6/BDB:  F900       SVEC   u=4   dx=0     dy=4     z=0
57B8/BDC:  F06F       SVEC   u=8   dx=-24   dy=0     z=6
57BA/BDD:  F900       SVEC   u=4   dx=0     dy=4     z=0
57BC/BDE:  F05B       SVEC   u=8   dx=24    dy=0     z=5
57BE/BDF:  F900       SVEC   u=4   dx=0     dy=4     z=0
57C0/BE0:  F04F       SVEC   u=8   dx=-24   dy=0     z=4
57C2/BE1:  F900       SVEC   u=4   dx=0     dy=4     z=0
57C4/BE2:  F03B       SVEC   u=8   dx=24    dy=0     z=3
57C6/BE3:  F900       SVEC   u=4   dx=0     dy=4     z=0
57C8/BE4:  F02F       SVEC   u=8   dx=-24   dy=0     z=2
57CA/BE5:  D000       RTSL

BNKERR: (JSRL $BE6)
;   refs: 6502 $7E70
57CC/BE6:  A0E4 115E  LABS   size=1   x=350  y=228 
57D0/BE8:  7000 0000  WAIT   t=7                  z=0
57D4/BEA:  CABF       JSRL   $557E   ; -> CHAR_B
57D6/BEB:  CAB7       JSRL   $556E   ; -> CHAR_A
57D8/BEC:  CB03       JSRL   $5606   ; -> CHAR_N
57DA/BED:  CAF6       JSRL   $55EC   ; -> CHAR_K
57DC/BEE:  CB0A       JSRL   $5614   ; -> CHAR_SPACE

ERM: (JSRL $BEF)
;   draws: "ERRO"
;   refs: DVG  $57F0
57DE/BEF:  CAD6       JSRL   $55AC   ; -> CHAR_E
57E0/BF0:  CB19       JSRL   $5632   ; -> CHAR_R
57E2/BF1:  CB19       JSRL   $5632   ; -> CHAR_R
57E4/BF2:  CB06       JSRL   $560C   ; -> CHAR_O
57E6/BF3:  EB19       JMPL   $5632   ; -> CHAR_R

PKYERR: (JSRL $BF4)
;   refs: none found - unreferenced art, reached via a computed word, or entered by fall-through
57E8/BF4:  A0C0 119A  LABS   size=1   x=410  y=192 
57EC/BF6:  7000 0000  WAIT   t=7                  z=0
57F0/BF8:  EBEF       JMPL   $57DE   ; -> ERM

ERASE: (JSRL $BF9)
;   draws: "ERASIN"
;   refs: 6502 $7F56
57F2/BF9:  CAD6       JSRL   $55AC   ; -> CHAR_E
57F4/BFA:  CB19       JSRL   $5632   ; -> CHAR_R
57F6/BFB:  CAB7       JSRL   $556E   ; -> CHAR_A
57F8/BFC:  CB2B       JSRL   $5656   ; -> CHAR_S
57FA/BFD:  CAEB       JSRL   $55D6   ; -> CHAR_I
57FC/BFE:  CB03       JSRL   $5606   ; -> CHAR_N
57FE/BFF:  EADF       JMPL   $55BE   ; -> CHAR_G

;====================================================================
; NOT DECODED - 6502 data below DVSTRT ($4D80)
;====================================================================
;
; Tables TRIROT indexes, not vector art.  Decoding them as a
; display list would invent shapes the game never draws.
; They are named and typed in astdelux2_main.asm.

; $499C-$49A3      8 bytes
; $4B2B-$4B3C     18 bytes
; $4B51-$4B91     65 bytes
