; Asteroids Deluxe - memory map and symbol glossary
; GENERATED by mkdefines.py from the original Atari source archive.
;
; Names are the real ones: they come from DSTDEC.MAC, EAROM.MAC,
; PG0123.MAC and the LINKM load map DSTRD0.MAP, all written by the
; game's own authors.  The archive is the rev 2 build (MAME
; `astdelux2`) - DSTRD0.MAP's NMI $785C / PWRON $7CD7 are exactly the
; vectors in 036433-02.  Rev 3 moves page zero down by 7 bytes, so
; RAM addresses below apply to rev 2 only; the hardware block applies
; to every revision.
;
; The original assembler allowed '$' inside identifiers.  '$' is the
; hex prefix in this listing, so names like $INTCT are written INTCT
; here; the original spelling is noted in the comment.
;
; Address space (from the DSTRD0.MAC header):
;     0000-00FF  page 0   scratch / globals
;     0100-01FF  page 1   6502 stack (shares the page with SXP* cells)
;     0200-02FF  page 2   player 1 object state   } swapped by BNKSEL
;     0300-03FF  page 3   player 2 object state   } ($3C04 bit 7)
;     2000-3FFF  I/O
;     4000-47FF  vector RAM (2K) - the display list the DVG reads
;     4800-57FF  vector board ROM (4K) - 6502 code AND DVG data
;     6000-7FFF  program ROM (8K)
;     FFFA-FFFF  vectors, mirrored from 7FFA-7FFF

;--------------------------------------------------------------------
; HARDWARE / I/O  (all revisions)
;--------------------------------------------------------------------
THRKHZ     = $2001        ; 3KHZ SIGNAL
HALT       = $2002        ; D7=0 FOR HALTED
HYPSW      = $2003        ; HYPERSPACE SWITCH (D7=1) FOR ON
FIRESW     = $2004        ; FIRE BUTTON (D7=1 FOR ON)
DIAGSW     = $2005        ; DIGNOSTIC STEP SWITCH
LAM        = $2006        ; orig. $LAM.  SLAM SWITCH
STSTSW     = $2007        ; SELF TEST SWITCH (D7=1 FOR ON)
COINA      = $2400        ; orig. $COINA.  COIN SWITCHES (LEFT TO RIGHT, OFFSET=1)
STRT1      = $2403        ; 1 PLAYER START SWITCH (D7=1 FOR ON)
STRT2      = $2404        ; 2 PLAYER START SWITCH (D7=1 FOR ON)
THRUST     = $2405        ; THRUST (D7=1 FOR ON)
ROTR       = $2406        ; ROTATE RIGHT (D7=1 FOR ON)
ROTL       = $2407        ; ROTATE LEFT (D7=1 FOR ON)
OPTN1      = $2800        ; OPTION SWITCH 8=D1, SW7=D0, 0=ON (BONUS LEVEL)
OPTN2      = $2801        ; D1=SW6, D0=SW5
OPTN3      = $2802        ; D1=SW4, D0=SW3 (LIVES)
OPTN4      = $2803        ; D1=SW2, D0=SW1 (LANGUAGE)
POKEY      = $2C00        ; POKEY PORT (16 ADDRESSES)
OPTN5      = $2C08        ; D7=SW8,...,D0=SW1 (GAME PRICE)
RANDOM     = $2C0A        ; RANDOM NUMBER PORT
EAIN       = $2C40        ; EA READ PORT
GOADD      = $3000        ; RESTART VECTOR GEN
EADAL      = $3200        ; LATCH ADDR/DATA
WTDOG      = $3400        ; WATCH DOG
EXPSND     = $3600        ; EXPLOSION SOUND  D6-D7=PITCH,D2-D5=VOLUME
VGRESET    = $3800        ; VECTOR GEN RESET
EACTL      = $3A00        ; EA CONTROL LATCH
SLMP1      = $3C00        ; START LAMP 1(BIT 7)
SLMP2      = $3C01        ; START LAMP 2(BIT 7)
SPTEN      = $3C03        ; SHIP THRUST ENABLE
BNKSEL     = $3C04        ; BANK SELECT(80=PLAYER 2)
CCLFT      = $3C05        ; COIN COUNTER LEFT
CCMID      = $3C06        ; COIN COUNTER MIDDLE
CCRIT      = $3C07        ; COIN COUNTER RIGHT
NRESET     = $3E00        ; NOISE RESET
VECRAM     = $4000        ; VECTOR RAM

;--------------------------------------------------------------------
; CONSTANTS  (bit masks, not addresses)
;--------------------------------------------------------------------
DAST       = $01          ; orig. $DAST
DTHST      = $00          ; orig. $DTHST
LMBIT      = $80          ; orig. $LMBIT.  D7=1 FOR ON
DEVSYS     = $00          ; .NE. FOR DEV SYS INTERFACE
EAC1       = $04          ; C1(INVERTED TO CHIP)
EAC2       = $02          ; C2
EACE       = $08          ; CHIP SELECT
EACK       = $01          ; CLOCK BIT

;--------------------------------------------------------------------
; PAGE 0  (rev 2 addresses)
;--------------------------------------------------------------------
VGSIZE     = $01          ; SCALING SIZE (0,10,20,...,F0)
VGBRIT     = $02          ; VECTOR BRIGHTNESS (0=OFF, F0=MAX, 10INC)
VGLIST     = $03          ; VECTOR LIST POINTER
XCOMP      = $05          ; X COMPONENT FOR VECTORS
TEMP1      = $09          ; SCRATCH-3 BYTES USED BY SELF-TEST
TEMP2      = $0C          
TEMP3      = $0E          ; 8 CKSUMS IN SELF TEST
R0         = $10          
R1         = $11          
R2         = $12          
R3         = $13          
R4         = $14          
R5         = $15          
R6         = $16          
R7         = $17          
R8         = $18          
R9         = $19          
XT         = $1A          ; STORAGE FOR X REGISTER
TEMP4      = $1B          
PLAYR      = $1E          ; PLAYER NUMBER (0 OR 1)
PLAYR2     = $1F          ; PLAYER NUMBER *2 (0 OR 2)
PLAYR3     = $20          ; PLAYER NUMBER *3 (0 OR 3)
LPLAYR     = $21          ; THE VALUE OF NPLAYR FOR LAST GAME
NPLAYR     = $22          ; NUMBER OF PLAYERS (1 OR 2)(0=END OF GAME)(-1=UPDATE HIGH SCORES)
HSCORE     = $23          ; HIGH SCORES (LSB,MSB)
UPDINT     = $41          ; 0,1, OR 2 TO INDICATE WHICH INITIAL IS BEING SELECTED
UPDFLG     = $42          ; POSITIVE MEANS THIS PLAYER HAS SET NEW HIGH SCORE
INITL      = $44          ; INITIALS FOR HIGH SCORE (FIRST,SECOND,THRID)
SCORE      = $62          ; PLAYER 1 AND 2 SCORES (LSB1,MSB1,LSB2,MSB2)
PLATEU     = $68          ; BONUS LEVEL ACCUMULATORS
NHITS      = $6E          ; STARTING NUMBER OF HITS PER PLAYER
HITS       = $6F          ; LIFE COUNTERS (PLAYER 1 / PLAYER 2)
CHIST      = $71          ; COLLISION HISTORY REGISTERS
SHDON      = $73          
GDELAY     = $74          ; DELAY BEFORE STARTING GAME
SYNC       = $75          ; FRAME COUNTER SYNC
FRAME      = $76          ; FRAME COUNTER
INTCT      = $78          ; orig. $INTCT.  INTERRUPT COUNTER
ANGLE      = $79          ; ANGLE OF ROTATIONS
LASTSW     = $7B          ; LAST SWITCH READING
XINCL      = $7C          ; SHIPS LSB FOR X INCREMENT
YINCL      = $7D          ; SHIPS LSB FOR Y INCREMENT
SND3       = $7E          ; SOUND FLAGS
LEXPSND    = $7F          ; LAST VALUE FOR EXPLOSION SOUND (SEE EXPSND)
LSND1      = $80          ; LAST VALUE FOR SHIP FIRE SOUND (SEE SHPFIR)
LSND2      = $81          ; LAST VALUE FOR SAUCER FIRE SOUND (SEE SCRFIR)
LTHUMP     = $82          ; LAST VALUE FOR THUMP SOUND (SEE THUMP)
THUMP1     = $83          ; LENGTH OF THUMP SOUNDS
THUMP2     = $84          ; LENGTH BETWEEN THUMP SOUNDS
LOUT1      = $85          ; LAST VALUE OF OUTPUT LATCH
ASTERS     = $86          ; ASTERIOD ORIENTATIONS
PROT       = $8A          
TWOCM      = $8E          
SBTL       = $8F          ; SHIP BACK TO LIFE INTENSITY FLAG
CPMTST     = $90          ; COPYRIGHT MESSAGE TEST FLAG
CRMERR     = $91          ; COPYRIGHT MESSAGE ERROR
HOLE       = $92          ; FLAG FOR COPYRIGHT TEST
CRDT       = $93          ; orig. $$CRDT.  COIN ROUTINE DEFINITION (SEE COIN65.MAC)
CMODE      = $94          ; orig. $CMODE
LMTIM      = $95          ; orig. $LMTIM
CNCT       = $96          ; orig. $CNCT
CCTIM      = $97          ; orig. $CCTIM
PSTSL      = $9A          ; orig. $PSTSL
CNSTT      = $9D          ; orig. $CNSTT
BCCNT      = $A0          ; orig. $BCCNT
BC         = $A1          ; orig. $BC
POINT      = $A2          ; POINTER OFFSET INTO DATA TABLES
CURRENT    = $AA          ; OUTPUT VALUE
FRAMES     = $B2          ; FRAMES UNTIL NEXT CHANGE
COUNT      = $BA          ; COUNT OF TOTAL CHANGES
MCOUNT     = $C2          ; BACKGROUND NOISE
MPNTR      = $CA          
EAX        = $D2          ; EA ACCESS INDEX
EABC       = $D3          ; BYTE COUNTER
EAFLG      = $D4          ; EA ACTIVITY FLAG
EAHSX      = $D5          ; HI-SCORE ENTRY TO WRITE
EACS       = $D6          ; CHECKSUM
EABAD      = $D7          ; BAD ENTRY FLAG.
TRILE      = $D8          ; DIAMOND LAUNCH ENABLE
BINSCR     = $DA          ; BINARY SCORE
PERR       = $DB          ; POKEY ERROR(S)
CKERR      = $E0          ; SOMEBODY STOLE THIS PGM IF.NE
RVELP      = $E1          ; MINIMUM ROCK VELOCITY+
RVELM      = $E2          ; MINIMUM ROCK VELOCITY-
HSSND      = $E3          ; HI-SCORE TABLE REACHED FLAG
SBTLT      = $E4          ; SHIP BACK TO LIFE TIMER
EXPDX      = $E5          ; X VEL OF EXPLOSION PIECE
EXPDY      = $ED          ; Y VEL OF EXPLOSION PIECE
EXPANG     = $F5          ; ORIENTATION OF PIECE
BONSCR     = $FD          ; BONUS SCORE @

;--------------------------------------------------------------------
; PAGE 1  (rev 2 addresses)
; The 6502 stack lives in this page; these cells sit above it.
;--------------------------------------------------------------------
SXPXL      = $0100        ; SHIP EXPLOSION CONTROLS. XL,YL,XH,YH
SXPYL      = $0108        
SXPXH      = $0110        
SXPYH      = $0118        
EXPTMB     = $0120        ; ORIENTATION VELOCITY

;--------------------------------------------------------------------
; PAGES 2/3  per-player object state  (rev 2 addresses)
; BNKSEL ($3C04) bit 7 swaps page 2 and page 3, so the same
; addresses address whichever player is up.
;--------------------------------------------------------------------
OBJ        = $0200        ; ROCK PIX SEL 0=NOT ACTIVE ELSE PIC #
SHPPIX     = $0219        ; SHIP PIX SEL, BIT 7=1 IF EXPLODING
SAUPIX     = $021A        ; SAUCER
SAUTP      = $021B        ; SAUCER TORPEDOES(=TIME OF FLIGHT)
SHPTP      = $021D        ; SHIP TORPEDOES(=TIME OF FLIGHT)
XINC       = $0221        ; ROCKS
SHPXI      = $023A        ; SHIP
SAUXI      = $023B        ; SAUCER
SAUTXI     = $023C        ; SAUCER TORPEDOES
SHPTXI     = $023E        ; SHIP TORPEDOES
YINC       = $0242        ; ROCKS
SHPYI      = $025B        ; SHIP
SAUYI      = $025C        ; SAUCER
SAUTYI     = $025D        ; SAUCER TORPEDOES
SHPTYI     = $025F        ; SHIP TORPEDOES
OBJXH      = $0263        ; ROCKS
SHPXH      = $027C        ; SHIP
SAUXH      = $027D        ; SAUCER
SAUTXH     = $027E        ; SAUCER TORPEDOES
SHPTXH     = $0280        ; SHIP TORPEDOES
OBJYH      = $0284        
SHPYH      = $029D        
SAUYH      = $029E        
SAUTYH     = $029F        
SHPTYH     = $02A1        
OBJXL      = $02A5        ; ROCKS
SHPXL      = $02BE        ; SHIP
SAUXL      = $02BF        ; SAUCER
SAUTXL     = $02C0        ; SAUCER TORPEDOES
SHPTXL     = $02C2        ; SHIP TORPEDOES
OBJYL      = $02C6        
SHPYL      = $02DF        
SAUYL      = $02E0        
SAUTYL     = $02E1        
SHPTYL     = $02E3        
NROCKS     = $02E7        ; CURRENT NUMBER OF ROCKS
EDELAY     = $02E8        ; DELAY BEFORE ENEMY ENTRY OR FIRING
SEDLAY     = $02E9        ; STARTING ENEMY DELAY
RTIMER     = $02EA        ; ROCK TIME - IF 0 SEND IN SAUCER ANYWAY
SDELAY     = $02EB        ; DELAY COUNT BEFORE ADDING SHIP (80=SHIP JUST DESTROYED)
RDELAY     = $02EC        ; DELAY COUNT BEFORE ADDING ROCKS
THUMP3     = $02ED        ; STARTING VALUE FOR THUMP2
DIFCTY     = $02EE        ; DIFFICULTY VALUE FOR STARTING SAUCERS
SHLDS      = $02EF        ; SHIELDS VALUE
SROCKS     = $02F0        
SRANG      = $02F1        ; ORIENTATIN
SRTIME     = $02F8        ; CONTROL
SPROCK     = $02FF        ; NUMBER OF SPECIAL ROCKS

;--------------------------------------------------------------------
; VECTOR BOARD ROM entry points  $4800-$57FF  (rev 2)
; Glossary only - commented out.  These are LABELS in the plain-form
; listings (astdelux2_vector_rom.asm / astdelux2_program_rom.asm),
; which .include this file; equating them here too would define
; each of them twice.
;--------------------------------------------------------------------
; SPLTTP     = $4800      
; ATTACK     = $48BE      
; CKSUM0     = $49A3      
; DIASND     = $49A4      
; MULT       = $49B3      
; RANGE      = $49DF      
; CPUTD      = $4A1A      
; SCALER     = $4A2A      
; TRIPIX     = $4A6D      
; SETTIP     = $4A96      
; SINCOS     = $4B51      
; ROTAST     = $4B92      
; EXPPIC     = $4D80      
; EXP16      = $4D88      
; RSOURC     = $5002      
; SHLDVC     = $5012      
; TFPIX      = $502A      
; ASTMSG     = $538A      
; SHIPS      = $53BC      
; CKSUM1     = $53C5      
; SHIPSV     = $53C6      
; UNDERL     = $56B0      
; VGMSGA     = $56F8      
; TEST1      = $5744      
; BNKERR     = $57CC      
; ERASE      = $57F2      

;--------------------------------------------------------------------
; PROGRAM ROM entry points  $6000-$7FFF  (rev 2)
; Glossary only - commented out.  These are LABELS in the plain-form
; listings (astdelux2_vector_rom.asm / astdelux2_program_rom.asm),
; which .include this file; equating them here too would define
; each of them twice.
;--------------------------------------------------------------------
; START      = $6000      
; CKSUM2     = $6101      
; CPYPOS     = $6210      
; CPYVEC     = $6246      
; BLOUP      = $62FC      
; CKSUM3     = $6920      
; MOVE2      = $6921      
; RNDPOS     = $6A03      
; NEWVE1     = $6A7E      
; POINTS     = $6C60      
; SEARCH     = $6D6C      
; SEARC1     = $6D6E      
; CPXROT     = $6EE2      
; ATAN       = $70D4      
; COMP       = $70EC      
; CKSUM4     = $7120      
; DIVIDE     = $7121      
; COS        = $7134      
; SIN        = $7137      
; DSTMSG     = $714E      
; CPYRS      = $717E      
; VGMSG      = $718F      
; VGME       = $7198      
; BOUNC      = $752C      
; ASTM       = $7603      
; DASOUN     = $760D      
; SNDOFF     = $7752      
; SNDPON     = $7758      
; SNDON      = $775B      
; SNDOO      = $775C      
; CSOUND     = $7787      
; RADDR      = $77DE      
; ROCKSA     = $77E2      
; MODULO     = $77EA      
; FILL       = $77F2      
; ASTMTS     = $77F5      
; ASTMT      = $7845      
; ST1        = $784F      
; DSTNMI     = $785C      
; MOOLAH     = $78A9      
; DSTCUT     = $79E8      
; VGHALT     = $79EC      
; VGHEXZ     = $79F7      
; VGHEX      = $79FD      
; VGCHAR     = $7A0A      
; VGJMPL     = $7A19      
; VGJSRL     = $7A2A      
; VGSABS     = $7A31      
; VGLABS     = $7A4A      
; VGADD      = $7A67      
; VGVCTR     = $7A72      
; VGAWT      = $7AF7      
; VGWAIT     = $7AFC      
; VGDOT      = $7AFE      
; EAROM      = $7B11      
; STEARO     = $7BD9      
; CASTST     = $7BF5      
; SINIT      = $7C37      
; LIVESS     = $7C74      
; BONDSP     = $7C93      
; DIGITS     = $7C98      
; DSTTST     = $7CC5      
; VGADD2     = $7CCC      
; PWRON      = $7CD7      
; CKSUM5     = $7D81      
; PKYTST     = $7FC1      

;--------------------------------------------------------------------
; DVG SHAPES  (named in the map as JSRL words; byte = 4000 + 2*word)
; Glossary only - commented out.  These are LABELS in the plain-form
; listings (astdelux2_vector_rom.asm / astdelux2_program_rom.asm),
; which .include this file; equating them here too would define
; each of them twice.
;--------------------------------------------------------------------
; CPMGV      = $4702      ; JSRL $381
; SAUCER     = $4E68      ; JSRL $734
; CPMGL      = $5382      ; JSRL $9C1
; CPMG       = $538A      ; JSRL $9C5
; SHIP17     = $5548      ; JSRL $AA4
; VGSPAC     = $5614      ; JSRL $B0A
; Z_5        = $5640      ; orig. Z.5.  JSRL $B20
; PKYERR     = $57E8      ; JSRL $BF4

