; Asteroids Deluxe (astdelux) - vector-board ROM ($4800-$57FF), plain assembler-style listing
; GENERATED by mkplain.py from astdelux_dump.bin - do not hand-edit.
;
; Subroutine and variable names are Atari's own, taken from the released
; rev 2 Asteroids Deluxe source archive
; (github.com/historicalsource/asteroids-deluxe) and placed on this ROM
; by matching instruction sequences (nameroutines.py) - nothing here is
; invented.  Comments to the right of an instruction, the blocks above a
; routine, and the ruled section banners are the ORIGINAL Atari comments,
; carried across the same way.  Lines marked '[note]' are this project's
; own descriptions, added where the source's comments are thin or absent
; (ROUTINE_NOTES in astdelux_config.py) - everything else is Atari's.
;
; Reading the names: NAME is a routine or data label from the source.
; NAME_20 is that routine's local label 20$ - a branch target inside it,
; kept under its owner's name.  RTS_n and NAME_RTS_n are the source's
; shared RTS labels (RTS.n there; '.' is not legal to the assembler).
; Lxxxx is an address the source does not name, and every line carries
; one so any byte can be referred to.  Packed message text is decoded
; in the comment as "TEXT" (msgtext.py).
;
; Memory map (see astdelux_defines.asm for the full glossary):
;     0000-00FF  page 0   scratch / globals
;     0100-01FF  page 1   6502 stack
;     0200-03FF  pages 2/3 player object state (bank-switched)
;     2000-3FFF  I/O
;     4000-47FF  vector RAM (2K) - the display list the DVG reads
;     4800-57FF  vector board ROM (4K) - 6502 code AND DVG picture
;                data, interleaved: TRIROT.MAC is `.ASECT` / `.=4800`,
;                so this ROM is not all display-list data.  Which bytes
;                are DVG opcodes (`.word`) and which are 6502 (decoded
;                as instructions) comes from the traced code/data map
;                (m6502trace.py), not a guess.
;     6000-7FFF  program ROM (8K)
;
; NOTE: the source archive documents rev 2 (astdelux2), not astdelux.
; Only hardware names - board wiring, revision-independent - apply here;
; RAM/ROM names would be wrong (rev 3 moves page zero by 7 bytes).  Run
; with --set astdelux2 for the fully named listing.
;
; Round-trip check: this file assembles back to the ROM bytes with ca65.
;     python mkplain.py --set astdelux --check
;
.include "astdelux_defines.asm"

.org $4800

;-------------------------------[ Program ROM Forward Declarations ]--------------------------------

L60D0      = $60D0
L60DB      = $60DB
L60EB      = $60EB
L61EB      = $61EB
L6221      = $6221
L6300      = $6300
L67EB      = $67EB
L6957      = $6957
L6958      = $6958
L6959      = $6959
L69E7      = $69E7
L6A1B      = $6A1B
L6C44      = $6C44
L6D50      = $6D50
L6D52      = $6D52
L6EC6      = $6EC6
L709E      = $709E
L70B6      = $70B6
L70FE      = $70FE
L7101      = $7101
L7159      = $7159
L7716      = $7716
L779D      = $779D
L779E      = $779E
L79D6      = $79D6
L7BE3      = $7BE3
L7C95      = $7C95
L7CD5      = $7CD5

;-----------------------------------[ Start Of Vector Board ROM ]-----------------------------------
L4800:  LDA $0200,Y
L4803:  AND #$3C
L4805:  LSR A
L4806:  LSR A
L4807:  TAX
L4808:  LDA $02F8,X
L480B:  BPL L483E
L480D:  STX $1A
L480F:  LDA #$05
L4811:  JSR L48B2
L4814:  JSR L6D50
L4817:  INC $02E7
L481A:  LDA $0200,Y
L481D:  PHA
L481E:  JSR L61EB
L4821:  PLA
L4822:  STA $0200,X
L4825:  LDA #$00
L4827:  STA $0200,Y
L482A:  LDX $1A
L482C:  LDA $02F8,X
L482F:  BPL L484E
L4831:  PHA
L4832:  LDA #$7F
L4834:  STA $02F8,X
L4837:  PLA
L4838:  LSR A
L4839:  AND #$0F
L483B:  TAX
L483C:  BPL L482C
L483E:  LSR A
L483F:  BCS L4851
L4841:  LDA #$00
L4843:  STA $02F8,X
L4846:  LDA #$20
L4848:  JSR L48B2
L484B:  JSR L49AC
L484E:  LDX $0E
L4850:  RTS
L4851:  LDA #$10
L4853:  STX $1A
L4855:  JSR L48B2
L4858:  JSR L6D50
L485B:  JSR L61EB
L485E:  INC $02E7
L4861:  INC $02FF
L4864:  LDA $1A
L4866:  ASL A
L4867:  ASL A
L4868:  ORA #$42
L486A:  STA $0200,X
L486D:  STX $10
L486F:  LDX $1A
L4871:  LDA #$7E
L4873:  STA $02F8,X
L4876:  LDA $79
L4878:  ADC #$20
L487A:  STA $02F1,X
L487D:  JSR L48A7
L4880:  STX $1A
L4882:  LDX $10
L4884:  JSR L6D52
L4887:  JSR L61EB
L488A:  INC $02E7
L488D:  LDA $1A
L488F:  ASL A
L4890:  ASL A
L4891:  ORA #$42
L4893:  STA $0200,X
L4896:  LDX $1A
L4898:  LDA #$7E
L489A:  STA $02F8,X
L489D:  LDA $79
L489F:  SBC #$20
L48A1:  STA $02F1,X
L48A4:  LDX $0E
L48A6:  RTS
L48A7:  LDX #$06
L48A9:  LDA $02F8,X
L48AC:  BEQ L48B1
L48AE:  DEX
L48AF:  BPL L48A9
L48B1:  RTS
L48B2:  LDX $0E
L48B4:  BEQ L48BA
L48B6:  CPX #$04
L48B8:  BCC L48B1
L48BA:  CLC
L48BB:  JMP L6C44
L48BE:  STX $10
L48C0:  LDY #$19
L48C2:  STY $11
L48C4:  INC $19
L48C6:  LDA $0200,X
L48C9:  LSR A
L48CA:  LSR A
L48CB:  AND #$0F
L48CD:  TAX
L48CE:  LDY $02F8,X
L48D1:  CPY #$04
L48D3:  BCC L48F1
L48D5:  LDA $76
L48D7:  AND #$0F
L48D9:  BNE L48E2
L48DB:  TYA
L48DC:  SEC
L48DD:  SBC #$02
L48DF:  STA $02F8,X
L48E2:  LDA $0219
L48E5:  BEQ L48E9
L48E7:  BPL L48F3
L48E9:  TYA
L48EA:  AND #$01
L48EC:  ORA #$02
L48EE:  STA $02F8,X
L48F1:  INC $11
L48F3:  LDY $11
L48F5:  STX $1A
L48F7:  LDX $10
L48F9:  JSR L4A22
L48FC:  JSR L49FD
L48FF:  STA $13
L4901:  LDA $0C
L4903:  STA $12
L4905:  LDA $11
L4907:  CLC
L4908:  ADC #$21
L490A:  TAY
L490B:  TXA
L490C:  ADC #$21
L490E:  TAX
L490F:  JSR L4A22
L4912:  JSR L49FD
L4915:  JSR L4A32
L4918:  LDX $1A
L491A:  STA $12
L491C:  LDY #$19
L491E:  CPY $11
L4920:  BNE L493B
L4922:  EOR #$80
L4924:  SBC $79
L4926:  BPL L492A
L4928:  EOR #$FF
L492A:  CMP #$10
L492C:  BCS L493B
L492E:  LDA $12
L4930:  SBC $02F1,X
L4933:  BPL L4937
L4935:  EOR #$FF
L4937:  CMP #$40
L4939:  BCC L496C
L493B:  LDA $12
L493D:  SEC
L493E:  SBC $02F1,X
L4941:  STA $12
L4943:  BPL L4947
L4945:  EOR #$FF
L4947:  CMP #$08
L4949:  BCC L496C
L494B:  LDA #$01
L494D:  LDY #$19
L494F:  CPY $11
L4951:  BNE L4960
L4953:  LDX $19
L4955:  CPX #$07
L4957:  BCC L495B
L4959:  LDX #$00
L495B:  LDA L49A4,X
L495E:  LDX $1A
L4960:  ASL $12
L4962:  BCC L4966
L4964:  EOR #$FF
L4966:  ADC $02F1,X
L4969:  STA $02F1,X
L496C:  LDA $02F0
L496F:  LSR A
L4970:  CLC
L4971:  ADC $D3
L4973:  ASL A
L4974:  CMP L6957
L4977:  BCC L497C
L4979:  LDA L6957
L497C:  ADC L6958
L497F:  STA $11
L4981:  PHA
L4982:  LDA $02F1,X
L4985:  JSR L70FE
L4988:  JSR L49BB
L498B:  LDX $10
L498D:  STA $0221,X
L4990:  PLA
L4991:  STA $11
L4993:  LDX $1A
L4995:  LDA $02F1,X
L4998:  JSR L7101
L499B:  JSR L49BB
L499E:  LDX $10
L49A0:  STA $0242,X
L49A3:  RTS
L49A4:  .byte $01, $02, $03, $03, $03, $04, $04, $11 ;........
L49AC:  DEC $02FF
L49AF:  BNE L49BA
L49B1:  TYA
L49B2:  PHA
L49B3:  LDY #$3F
L49B5:  JSR L7716
L49B8:  PLA
L49B9:  TAY
L49BA:  RTS
L49BB:  TAY
L49BC:  BPL L49C3
L49BE:  EOR #$FF
L49C0:  CLC
L49C1:  ADC #$01
L49C3:  STA $12
L49C5:  LDA #$00
L49C7:  STA $13
L49C9:  ASL $11
L49CB:  BCS L49DA
L49CD:  BNE L49E1
L49CF:  LDA $13
L49D1:  CPY #$00
L49D3:  BPL L49D9
L49D5:  EOR #$FF
L49D7:  ADC #$00
L49D9:  RTS
L49DA:  LDA $13
L49DC:  CLC
L49DD:  ADC $12
L49DF:  STA $13
L49E1:  LSR $12
L49E3:  BNE L49C9
L49E5:  BEQ L49CF
L49E7:  CMP #$10
L49E9:  BCC L49FC
L49EB:  CMP #$F0
L49ED:  BCS L49FC
L49EF:  STA $15
L49F1:  LDA #$00
L49F3:  SEC
L49F4:  SBC $0C
L49F6:  STA $0C
L49F8:  LDA #$00
L49FA:  SBC $15
L49FC:  RTS
L49FD:  CMP #$04
L49FF:  BCC L49FC
L4A01:  CMP #$FC
L4A03:  BCS L49FC
L4A05:  LDY $D3
L4A07:  CPY #$05
L4A09:  BCC L49E7
L4A0B:  LDY $19
L4A0D:  CPY #$03
L4A0F:  BCC L49E7
L4A11:  STA $15
L4A13:  TXA
L4A14:  CPX #$21
L4A16:  BCS L4A19
L4A18:  LSR A
L4A19:  LSR A
L4A1A:  ROR A
L4A1B:  EOR $15
L4A1D:  BMI L49F1
L4A1F:  LDA $15
L4A21:  RTS
L4A22:  LDA $02A5,Y
L4A25:  SEC
L4A26:  SBC $02A5,X
L4A29:  STA $0C
L4A2B:  LDA $0263,Y
L4A2E:  SBC $0263,X
L4A31:  RTS
L4A32:  STA $14
L4A34:  BPL L4A39
L4A36:  JSR L70B6
L4A39:  STA $15
L4A3B:  LDA $13
L4A3D:  BPL L4A42
L4A3F:  JSR L70B6
L4A42:  ORA $15
L4A44:  LDX #$07
L4A46:  ASL A
L4A47:  BMI L4A4C
L4A49:  DEX
L4A4A:  BNE L4A46
L4A4C:  CPX #$04
L4A4E:  BCS L4A62
L4A50:  LSR $13
L4A52:  ROR $12
L4A54:  LSR $14
L4A56:  ROR $0C
L4A58:  DEX
L4A59:  BPL L4A50
L4A5B:  LDX $12
L4A5D:  LDY $0C
L4A5F:  JMP L709E
L4A62:  ASL $12
L4A64:  ROL $13
L4A66:  ASL $0C
L4A68:  ROL $14
L4A6A:  INX
L4A6B:  CPX #$07
L4A6D:  BCC L4A62
L4A6F:  LDX $13
L4A71:  LDY $14
L4A73:  BCS L4A5F
L4A75:  LSR A
L4A76:  LSR A
L4A77:  LSR A
L4A78:  AND #$0F
L4A7A:  TAX
L4A7B:  LDA $02F8,X
L4A7E:  LSR A
L4A7F:  LDA #$00
L4A81:  ROR A
L4A82:  ROR A
L4A83:  STA $11
L4A85:  LDA $02F1,X
L4A88:  LSR A
L4A89:  LSR A
L4A8A:  BIT $11
L4A8C:  BVC L4A90
L4A8E:  AND #$1E
L4A90:  AND #$3E
L4A92:  ORA $11
L4A94:  TAY
L4A95:  LDX L502B,Y
L4A98:  LDA L502A,Y
L4A9B:  JMP L7CD5
L4A9E:  LDA $02F0
L4AA1:  BEQ L4AB6
L4AA3:  CLC
L4AA4:  LDX #$02
L4AA6:  ADC #$02
L4AA8:  CMP #$05
L4AAA:  BCC L4AAF
L4AAC:  INX
L4AAD:  LDA #$05
L4AAF:  STX $11
L4AB1:  CMP $02E7
L4AB4:  BCS L4AB7
L4AB6:  RTS
L4AB7:  LDX $02FF
L4ABA:  BNE L4AB6
L4ABC:  LDY $02E7
L4ABF:  LDA $0200,X
L4AC2:  BNE L4AC6
L4AC4:  STX $10
L4AC6:  BPL L4AC9
L4AC8:  DEY
L4AC9:  INX
L4ACA:  CPX #$19
L4ACC:  BCC L4ABF
L4ACE:  LDX $1E
L4AD0:  LDA $D1,X
L4AD2:  BEQ L4AD8
L4AD4:  CPY $11
L4AD6:  BCC L4AB6
L4AD8:  LDY #$1A
L4ADA:  STY $D1,X
L4ADC:  LDX $10
L4ADE:  JSR L69E7
L4AE1:  JSR L4B4D
L4AE4:  LDY #$02
L4AE6:  STY $DD
L4AE8:  TYA
L4AE9:  ASL A
L4AEA:  ASL A
L4AEB:  ORA #$42
L4AED:  STA $0200,X
L4AF0:  INC $02E7
L4AF3:  INC $02FF
L4AF6:  LDA L4B47,Y
L4AF9:  STA $02F8,Y
L4AFC:  LDA L4B4A,Y
L4AFF:  STA $02F1,Y
L4B02:  LDA L4B3B,Y
L4B05:  CLC
L4B06:  ADC $02A5,X
L4B09:  STA $02A5,X
L4B0C:  LDA L4B3E,Y
L4B0F:  ADC $0263,X
L4B12:  STA $0263,X
L4B15:  LDA L4B41,Y
L4B18:  CLC
L4B19:  ADC $02C6,X
L4B1C:  STA $02C6,X
L4B1F:  LDA L4B44,Y
L4B22:  ADC $0284,X
L4B25:  STA $0284,X
L4B28:  DEY
L4B29:  BMI L4AB6
L4B2B:  STX $10
L4B2D:  JSR L6D52
L4B30:  STY $11
L4B32:  LDY $10
L4B34:  JSR L61EB
L4B37:  LDY $11
L4B39:  BPL L4AE8
L4B3B:  BRK
L4B3C:  .byte $58, $70          ;Xp
L4B3E:  .byte $00, $FF, $00     ;...
L4B41:  .byte $40, $50, $00     ;@P.
L4B44:  .byte $FF, $00, $00     ;...
L4B47:  .byte $83, $85, $81     ;...
L4B4A:  .byte $F0, $98, $40     ;..@
L4B4D:  JSR L4B53
L4B50:  STA $0221,X
L4B53:  LDY #$06
L4B55:  LDA RANDOM
L4B58:  BPL L4B5C
L4B5A:  LDY #$FA
L4B5C:  TYA
L4B5D:  STA $0242,X
L4B60:  RTS
L4B61:  .byte $00, $03, $06, $09, $0C, $10, $13, $16 ;........
L4B69:  .byte $19, $1C, $1F, $22, $25, $28, $2B, $2E ;..."%(+.
L4B71:  .byte $31, $33, $36, $39, $3C, $3F, $41, $44 ;1369<?AD
L4B79:  .byte $47, $49, $4C, $4E, $51, $53, $55, $58 ;GILNQSUX
L4B81:  .byte $5A, $5C, $5E, $60, $62, $64, $66, $68 ;Z\^`bdfh
L4B89:  .byte $6A, $6B, $6D, $6F, $70, $71, $73, $74 ;jkmopqst
L4B91:  .byte $75, $76, $78, $79, $7A, $7A, $7B, $7C ;uvxyzz{|
L4B99:  .byte $7D, $7D, $7E, $7E, $7E, $7F, $7F, $7F ;}}~~~...
L4BA1:  .byte $7F               ;.
L4BA2:  LDA $76
L4BA4:  AND #$03
L4BA6:  TAX
L4BA7:  CLC
L4BA8:  ADC #$FE
L4BAA:  ADC $86,X
L4BAC:  STA $86,X
L4BAE:  AND #$F0
L4BB0:  CLC
L4BB1:  ADC $86,X
L4BB3:  ASL A
L4BB4:  JSR L6EC6
L4BB7:  LDA L5002,Y
L4BBA:  STA $10
L4BBC:  LDA L5003,Y
L4BBF:  STA $11
L4BC1:  TXA
L4BC2:  ASL A
L4BC3:  TAX
L4BC4:  ASL A
L4BC5:  AND #$04
L4BC7:  EOR $09
L4BC9:  STA $09
L4BCB:  LDA L779D,X
L4BCE:  ASL A
L4BCF:  STA $03
L4BD1:  LDA L779E,X
L4BD4:  ROL A
L4BD5:  EOR #$C0
L4BD7:  STA $04
L4BD9:  LDX #$0C
L4BDB:  JSR L6221
L4BDE:  JMP L79D6
L4BE1:  LDA $22
L4BE3:  BEQ L4BF3
L4BE5:  LDA $74
L4BE7:  BNE L4BEC
L4BE9:  JMP L4CF6
L4BEC:  DEC $74
L4BEE:  JSR L60EB
L4BF1:  CLC
L4BF2:  RTS
L4BF3:  STA $13
L4BF5:  LDA $8D
L4BF7:  AND #$03
L4BF9:  BNE L4C01
L4BFB:  LDA #$02
L4BFD:  STA $8C
L4BFF:  BNE L4C57
L4C01:  CLC
L4C02:  ADC #$07
L4C04:  TAY
L4C05:  LDA $42
L4C07:  AND $43
L4C09:  BPL L4C57
L4C0B:  JSR L7159
L4C0E:  LDA $8C
L4C10:  CMP #$40
L4C12:  BCS L4C12
L4C14:  STA $10
L4C16:  LDY #$0B
L4C18:  JSR L7159
L4C1B:  LDX #$00
L4C1D:  STX $11
L4C1F:  INX
L4C20:  STX $12
L4C22:  SED
L4C23:  LSR $10
L4C25:  BCC L4C2E
L4C27:  LDA $11
L4C29:  CLC
L4C2A:  ADC $12
L4C2C:  STA $11
L4C2E:  BEQ L4C38
L4C30:  LDA $12
L4C32:  ADC $12
L4C34:  STA $12
L4C36:  BCC L4C23
L4C38:  CLD
L4C39:  LDX #$00
L4C3B:  LDY #$01
L4C3D:  LDA #$11
L4C3F:  SEC
L4C40:  JSR L7C95
L4C43:  LDA $8D
L4C45:  AND #$03
L4C47:  CMP #$03
L4C49:  BNE L4C57
L4C4B:  LDA $8F
L4C4D:  LSR A
L4C4E:  BCC L4C57
L4C50:  LDA #$20
L4C52:  LDX #$CB
L4C54:  JSR L7CD5
L4C57:  LDY #$06
L4C59:  LDX $8C
L4C5B:  BNE L4C5F
L4C5D:  STX $8A
L4C5F:  LDA OPTN2
L4C62:  LSR A
L4C63:  BCC L4C75
L4C65:  BIT $8A
L4C67:  BMI L4C75
L4C69:  CPX #$01
L4C6B:  BCC L4C71
L4C6D:  BNE L4C75
L4C6F:  ROR $13
L4C71:  LDY #$0C
L4C73:  BNE L4C7D
L4C75:  LDA #$FF
L4C77:  STA $8A
L4C79:  CPY #$0C
L4C7B:  BNE L4C86
L4C7D:  JSR L60DB
L4C80:  CLC
L4C81:  LDA #$00
L4C83:  STA $85
L4C85:  RTS
L4C86:  TXA
L4C87:  BEQ L4C80
L4C89:  JSR L60DB
L4C8C:  LDY $8C
L4C8E:  LDX #$01
L4C90:  LDA STRT1
L4C93:  BMI L4CB5
L4C95:  CPY #$02
L4C97:  BCC L4CE2
L4C99:  LDA STRT2
L4C9C:  BPL L4CE2
L4C9E:  STA BNKSEL
L4CA1:  JSR L60D0
L4CA4:  JSR L7BE3
L4CA7:  JSR L6959
L4CAA:  JSR L6A1B
L4CAD:  LDA $6E
L4CAF:  STA $70
L4CB1:  LDX #$02
L4CB3:  DEC $8C
L4CB5:  STX $22
L4CB7:  DEC $8C
L4CB9:  STX BNKSEL
L4CBC:  STX $85
L4CBE:  JSR L60D0
L4CC1:  JSR L7BE3
L4CC4:  JSR L6A1B
L4CC7:  LDA #$80
L4CC9:  STA $74
L4CCB:  ASL A
L4CCC:  STA $1E
L4CCE:  STA $1F
L4CD0:  STA $20
L4CD2:  STA $9A
L4CD4:  STA $99
L4CD6:  LDA $6E
L4CD8:  STA $6F
L4CDA:  LDA #$04
L4CDC:  STA $84
L4CDE:  STA NRESET
L4CE1:  RTS
L4CE2:  LDA $76
L4CE4:  AND #$0F
L4CE6:  BNE L4CF4
L4CE8:  LDA #$01
L4CEA:  CMP $8C
L4CEC:  BEQ L4CF0
L4CEE:  LDA #$03
L4CF0:  EOR $85
L4CF2:  STA $85
L4CF4:  CLC
L4CF5:  RTS
L4CF6:  LDA $76
L4CF8:  AND #$3F
L4CFA:  BNE L4D06
L4CFC:  LDA $02ED
L4CFF:  CMP #$08
L4D01:  BEQ L4D06
L4D03:  DEC $02ED
L4D06:  LDX $1E
L4D08:  LDA $6F,X
L4D0A:  BNE L4D28
L4D0C:  LDA $021D
L4D0F:  ORA $021E
L4D12:  ORA $021F
L4D15:  ORA $0220
L4D18:  BNE L4D28
L4D1A:  LDY #$07
L4D1C:  JSR L7159
L4D1F:  LDA $22
L4D21:  CMP #$02
L4D23:  BCC L4D28
L4D25:  JSR L60EB
L4D28:  LDA $0219
L4D2B:  BNE L4D64
L4D2D:  LDA $02EB
L4D30:  CMP #$80
L4D32:  BNE L4D64
L4D34:  LDA #$10
L4D36:  JSR L6300
L4D39:  LDX $22
L4D3B:  LDA $6F
L4D3D:  ORA $70
L4D3F:  BEQ L4D66
L4D41:  JSR L67EB
L4D44:  DEX
L4D45:  BEQ L4D64
L4D47:  LDA #$80
L4D49:  STA $74
L4D4B:  LDA $1E
L4D4D:  EOR #$01
L4D4F:  TAX
L4D50:  LDA $6F,X
L4D52:  BEQ L4D64
L4D54:  STX $1E
L4D56:  TXA
L4D57:  ROR A
L4D58:  ROR A
L4D59:  STA BNKSEL
L4D5C:  TXA
L4D5D:  ASL A
L4D5E:  STA $1F
L4D60:  ORA $1E
L4D62:  STA $20
L4D64:  CLC
L4D65:  RTS
L4D66:  STX $21
L4D68:  LDA #$FF
L4D6A:  STA $22
L4D6C:  LDA #$03
L4D6E:  STA $85
L4D70:  STA BNKSEL
L4D73:  BNE L4D64
L4D75:  .byte $10, $05, $02, $FF, $FF, $FF, $FF, $FF ;........
L4D7D:  .byte $FF, $FF, $FF     ;...
L4D80:  .byte $15               ;.
L4D81:  .byte $C7               ;.
L4D82:  .word $C6FA             ;JSRL L4DF4 ($4DF4)
L4D84:  .word $C6DB             ;JSRL L4DB6 ($4DB6)
L4D86:  .word $C6C4             ;JSRL L4D88 ($4D88)
L4D88:  .word $F80D             ;SVEC u=16 dx=-16 dy=0 z=0
L4D8A:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4D8C:  .word $FD0D             ;SVEC u=16 dx=-16 dy=-16 z=0
L4D8E:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4D90:  .word $FD09             ;SVEC u=16 dx=16 dy=-16 z=0
L4D92:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4D94:  .word $F10B             ;SVEC u=8 dx=24 dy=8 z=0
L4D96:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4D98:  .word $F50A             ;SVEC u=8 dx=16 dy=-8 z=0
L4D9A:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4D9C:  .word $F908             ;SVEC u=16 dx=0 dy=16 z=0
L4D9E:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4DA0:  .word $F309             ;SVEC u=8 dx=8 dy=24 z=0
L4DA2:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4DA4:  .word $F30D             ;SVEC u=8 dx=-8 dy=24 z=0
L4DA6:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4DA8:  .word $5480, $0600      ;VCTR s=5 dx=-32 dy=-8 z=0 [x16]
L4DAC:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4DAE:  .word $F10F             ;SVEC u=8 dx=-24 dy=8 z=0
L4DB0:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4DB2:  .word $FE0A             ;SVEC u=16 dx=32 dy=-32 z=0
L4DB4:  .word $D000             ;RTSL
L4DB6:  .word $3000, $0780      ;VCTR s=3 dx=-14 dy=0 z=0 [x64]
L4DBA:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4DBC:  .word $3780, $0780      ;VCTR s=3 dx=-14 dy=-14 z=0 [x64]
L4DC0:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4DC2:  .word $3780, $0380      ;VCTR s=3 dx=14 dy=-14 z=0 [x64]
L4DC6:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4DC8:  .word $40E0, $02A0      ;VCTR s=4 dx=21 dy=7 z=0 [x32]
L4DCC:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4DCE:  .word $35C0, $0380      ;VCTR s=3 dx=14 dy=-7 z=0 [x64]
L4DD2:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4DD4:  .word $3380, $0000      ;VCTR s=3 dx=0 dy=14 z=0 [x64]
L4DD8:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4DDA:  .word $42A0, $00E0      ;VCTR s=4 dx=7 dy=21 z=0 [x32]
L4DDE:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4DE0:  .word $42A0, $04E0      ;VCTR s=4 dx=-7 dy=21 z=0 [x32]
L4DE4:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4DE6:  .word $44E0, $0780      ;VCTR s=4 dx=-28 dy=-7 z=0 [x32]
L4DEA:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4DEC:  .word $40E0, $06A0      ;VCTR s=4 dx=-21 dy=7 z=0 [x32]
L4DF0:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4DF2:  .word $D000             ;RTSL
L4DF4:  .word $F807             ;SVEC u=4 dx=-12 dy=0 z=0
L4DF6:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4DF8:  .word $FF07             ;SVEC u=4 dx=-12 dy=-12 z=0
L4DFA:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4DFC:  .word $FF03             ;SVEC u=4 dx=12 dy=-12 z=0
L4DFE:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4E00:  .word $40C0, $0240      ;VCTR s=4 dx=18 dy=6 z=0 [x32]
L4E04:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4E06:  .word $3580, $0300      ;VCTR s=3 dx=12 dy=-6 z=0 [x64]
L4E0A:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4E0C:  .word $FB00             ;SVEC u=4 dx=0 dy=12 z=0
L4E0E:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4E10:  .word $4240, $00C0      ;VCTR s=4 dx=6 dy=18 z=0 [x32]
L4E14:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4E16:  .word $4240, $04C0      ;VCTR s=4 dx=-6 dy=18 z=0 [x32]
L4E1A:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4E1C:  .word $44C0, $0700      ;VCTR s=4 dx=-24 dy=-6 z=0 [x32]
L4E20:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4E22:  .word $40C0, $0640      ;VCTR s=4 dx=-18 dy=6 z=0 [x32]
L4E26:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4E28:  .word $D000             ;RTSL
L4E2A:  .word $3000, $0680      ;VCTR s=3 dx=-10 dy=0 z=0 [x64]
L4E2E:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4E30:  .word $3680, $0680      ;VCTR s=3 dx=-10 dy=-10 z=0 [x64]
L4E34:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4E36:  .word $3680, $0280      ;VCTR s=3 dx=10 dy=-10 z=0 [x64]
L4E3A:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4E3C:  .word $3140, $03C0      ;VCTR s=3 dx=15 dy=5 z=0 [x64]
L4E40:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4E42:  .word $3540, $0280      ;VCTR s=3 dx=10 dy=-5 z=0 [x64]
L4E46:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4E48:  .word $3280, $0000      ;VCTR s=3 dx=0 dy=10 z=0 [x64]
L4E4C:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4E4E:  .word $33C0, $0140      ;VCTR s=3 dx=5 dy=15 z=0 [x64]
L4E52:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4E54:  .word $33C0, $0540      ;VCTR s=3 dx=-5 dy=15 z=0 [x64]
L4E58:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4E5A:  .word $44A0, $0680      ;VCTR s=4 dx=-20 dy=-5 z=0 [x32]
L4E5E:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4E60:  .word $3140, $07C0      ;VCTR s=3 dx=-15 dy=5 z=0 [x64]
L4E64:  .word $F878             ;SVEC u=16 dx=0 dy=0 z=7
L4E66:  .word $D000             ;RTSL
L4E68:  .word $F10E             ;SVEC u=8 dx=-16 dy=8 z=0
L4E6A:  .word $F8CA             ;SVEC u=16 dx=32 dy=0 z=12
L4E6C:  .word $F60B             ;SVEC u=8 dx=24 dy=-16 z=0
L4E6E:  .word $6000, $D680      ;VCTR s=6 dx=-80 dy=0 z=13 [x8]
L4E72:  .word $F6DB             ;SVEC u=8 dx=24 dy=-16 z=13
L4E74:  .word $F8CA             ;SVEC u=16 dx=32 dy=0 z=12
L4E76:  .word $F2DB             ;SVEC u=8 dx=24 dy=16 z=13
L4E78:  .word $F2DF             ;SVEC u=8 dx=-24 dy=16 z=13
L4E7A:  .word $F2CD             ;SVEC u=8 dx=-8 dy=16 z=12
L4E7C:  .word $F8CD             ;SVEC u=16 dx=-16 dy=0 z=12
L4E7E:  .word $F6CD             ;SVEC u=8 dx=-8 dy=-16 z=12
L4E80:  .word $F6DF             ;SVEC u=8 dx=-24 dy=-16 z=13
L4E82:  .word $D000             ;RTSL
L4E84:  .word $F009             ;SVEC u=8 dx=8 dy=0 z=0
L4E86:  .word $F17B             ;SVEC u=8 dx=24 dy=8 z=7
L4E88:  .word $F178             ;SVEC u=8 dx=0 dy=8 z=7
L4E8A:  .word $F27F             ;SVEC u=8 dx=-24 dy=16 z=7
L4E8C:  .word $F07F             ;SVEC u=8 dx=-24 dy=0 z=7
L4E8E:  .word $F679             ;SVEC u=8 dx=8 dy=-16 z=7
L4E90:  .word $F87E             ;SVEC u=16 dx=-32 dy=0 z=7
L4E92:  .word $F778             ;SVEC u=8 dx=0 dy=-24 z=7
L4E94:  .word $F77B             ;SVEC u=8 dx=24 dy=-24 z=7
L4E96:  .word $F17B             ;SVEC u=8 dx=24 dy=8 z=7
L4E98:  .word $F579             ;SVEC u=8 dx=8 dy=-8 z=7
L4E9A:  .word $F979             ;SVEC u=16 dx=16 dy=16 z=7
L4E9C:  .word $F27F             ;SVEC u=8 dx=-24 dy=16 z=7
L4E9E:  .word $3080, $0200      ;VCTR s=3 dx=8 dy=2 z=0 [x64]
L4EA2:  .word $4180, $72C0      ;VCTR s=4 dx=22 dy=12 z=7 [x32]
L4EA6:  .word $3200, $7480      ;VCTR s=3 dx=-2 dy=8 z=7 [x64]
L4EAA:  .word $4160, $7740      ;VCTR s=4 dx=-26 dy=11 z=7 [x32]
L4EAE:  .word $44A0, $7700      ;VCTR s=4 dx=-24 dy=-5 z=7 [x32]
L4EB2:  .word $3780, $72C0      ;VCTR s=3 dx=11 dy=-14 z=7 [x64]
L4EB6:  .word $44C0, $77E0      ;VCTR s=4 dx=-31 dy=-6 z=7 [x32]
L4EBA:  .word $4700, $7080      ;VCTR s=4 dx=4 dy=-24 z=7 [x32]
L4EBE:  .word $4660, $73A0      ;VCTR s=4 dx=29 dy=-19 z=7 [x32]
L4EC2:  .word $41A0, $72C0      ;VCTR s=4 dx=22 dy=13 z=7 [x32]
L4EC6:  .word $3580, $7240      ;VCTR s=3 dx=9 dy=-6 z=7 [x64]
L4ECA:  .word $4260, $71A0      ;VCTR s=4 dx=13 dy=19 z=7 [x32]
L4ECE:  .word $4160, $7760      ;VCTR s=4 dx=-27 dy=11 z=7 [x32]
L4ED2:  .word $2180, $0380      ;VCTR s=2 dx=7 dy=3 z=0 [x128]
L4ED6:  .word $4220, $7280      ;VCTR s=4 dx=20 dy=17 z=7 [x32]
L4EDA:  .word $2380, $7600      ;VCTR s=2 dx=-4 dy=7 z=7 [x128]
L4EDE:  .word $40C0, $7780      ;VCTR s=4 dx=-28 dy=6 z=7 [x32]
L4EE2:  .word $4540, $76C0      ;VCTR s=4 dx=-22 dy=-10 z=7 [x32]
L4EE6:  .word $36C0, $7340      ;VCTR s=3 dx=13 dy=-11 z=7 [x64]
L4EEA:  .word $45A0, $77A0      ;VCTR s=4 dx=-29 dy=-13 z=7 [x32]
L4EEE:  .word $46C0, $7120      ;VCTR s=4 dx=9 dy=-22 z=7 [x32]
L4EF2:  .word $45A0, $73E0      ;VCTR s=4 dx=31 dy=-13 z=7 [x32]
L4EF6:  .word $4220, $7280      ;VCTR s=4 dx=20 dy=17 z=7 [x32]
L4EFA:  .word $3500, $7280      ;VCTR s=3 dx=10 dy=-4 z=7 [x64]
L4EFE:  .word $4280, $7120      ;VCTR s=4 dx=9 dy=20 z=7 [x32]
L4F02:  .word $40C0, $77A0      ;VCTR s=4 dx=-29 dy=6 z=7 [x32]
L4F06:  .word $2200, $0380      ;VCTR s=2 dx=7 dy=4 z=0 [x128]
L4F0A:  .word $4280, $71E0      ;VCTR s=4 dx=15 dy=20 z=7 [x32]
L4F0E:  .word $2380, $7600      ;VCTR s=2 dx=-4 dy=7 z=7 [x128]
L4F12:  .word $4000, $77A0      ;VCTR s=4 dx=-29 dy=0 z=7 [x32]
L4F16:  .word $45A0, $7680      ;VCTR s=4 dx=-20 dy=-13 z=7 [x32]
L4F1A:  .word $3640, $73C0      ;VCTR s=3 dx=15 dy=-9 z=7 [x64]
L4F1E:  .word $4640, $7740      ;VCTR s=4 dx=-26 dy=-18 z=7 [x32]
L4F22:  .word $4680, $71A0      ;VCTR s=4 dx=13 dy=-20 z=7 [x32]
L4F26:  .word $5460, $7210      ;VCTR s=5 dx=33 dy=-6 z=7 [x16]
L4F2A:  .word $4260, $7200      ;VCTR s=4 dx=16 dy=19 z=7 [x32]
L4F2E:  .word $3480, $72C0      ;VCTR s=3 dx=11 dy=-2 z=7 [x64]
L4F32:  .word $42C0, $7080      ;VCTR s=4 dx=4 dy=22 z=7 [x32]
L4F36:  .word $4000, $7780      ;VCTR s=4 dx=-28 dy=0 z=7 [x32]
L4F3A:  .word $F303             ;SVEC u=2 dx=6 dy=6 z=0
L4F3C:  .word $42C0, $7160      ;VCTR s=4 dx=11 dy=22 z=7 [x32]
L4F40:  .word $F377             ;SVEC u=2 dx=-6 dy=6 z=7
L4F42:  .word $44C0, $7780      ;VCTR s=4 dx=-28 dy=-6 z=7 [x32]
L4F46:  .word $4620, $7620      ;VCTR s=4 dx=-17 dy=-17 z=7 [x32]
L4F4A:  .word $44A0, $7220      ;VCTR s=4 dx=17 dy=-5 z=7 [x32]
L4F4E:  .word $46E0, $76E0      ;VCTR s=4 dx=-23 dy=-23 z=7 [x32]
L4F52:  .word $4620, $7220      ;VCTR s=4 dx=17 dy=-17 z=7 [x32]
L4F56:  .word $5000, $7220      ;VCTR s=5 dx=34 dy=0 z=7 [x16]
L4F5A:  .word $42E0, $7180      ;VCTR s=4 dx=12 dy=23 z=7 [x32]
L4F5E:  .word $3000, $72C0      ;VCTR s=3 dx=11 dy=0 z=7 [x64]
L4F62:  .word $42C0, $7000      ;VCTR s=4 dx=0 dy=22 z=7 [x32]
L4F66:  .word $44A0, $7780      ;VCTR s=4 dx=-28 dy=-5 z=7 [x32]
L4F6A:  .word $2380, $0200      ;VCTR s=2 dx=4 dy=7 z=0 [x128]
L4F6E:  .word $4300, $70E0      ;VCTR s=4 dx=7 dy=24 z=7 [x32]
L4F72:  .word $2200, $7780      ;VCTR s=2 dx=-7 dy=4 z=7 [x128]
L4F76:  .word $4560, $7740      ;VCTR s=4 dx=-26 dy=-11 z=7 [x32]
L4F7A:  .word $4680, $75A0      ;VCTR s=4 dx=-13 dy=-20 z=7 [x32]
L4F7E:  .word $4440, $7220      ;VCTR s=4 dx=17 dy=-2 z=7 [x32]
L4F82:  .word $4740, $7640      ;VCTR s=4 dx=-18 dy=-26 z=7 [x32]
L4F86:  .word $45C0, $7280      ;VCTR s=4 dx=20 dy=-14 z=7 [x32]
L4F8A:  .word $5070, $7220      ;VCTR s=5 dx=34 dy=7 z=7 [x16]
L4F8E:  .word $4300, $70C0      ;VCTR s=4 dx=6 dy=24 z=7 [x32]
L4F92:  .word $30C0, $72C0      ;VCTR s=3 dx=11 dy=3 z=7 [x64]
L4F96:  .word $42C0, $7480      ;VCTR s=4 dx=-4 dy=22 z=7 [x32]
L4F9A:  .word $4560, $7760      ;VCTR s=4 dx=-27 dy=-11 z=7 [x32]
L4F9E:  .word $2380, $0180      ;VCTR s=2 dx=3 dy=7 z=0 [x128]
L4FA2:  .word $4340, $7040      ;VCTR s=4 dx=2 dy=26 z=7 [x32]
L4FA6:  .word $30C0, $7600      ;VCTR s=3 dx=-8 dy=3 z=7 [x64]
L4FAA:  .word $F67F             ;SVEC u=8 dx=-24 dy=-16 z=7
L4FAC:  .word $46E0, $7520      ;VCTR s=4 dx=-9 dy=-23 z=7 [x32]
L4FB0:  .word $4040, $7240      ;VCTR s=4 dx=18 dy=2 z=7 [x32]
L4FB4:  .word $47C0, $7580      ;VCTR s=4 dx=-12 dy=-30 z=7 [x32]
L4FB8:  .word $4520, $72C0      ;VCTR s=4 dx=22 dy=-9 z=7 [x32]
L4FBC:  .word $41A0, $73E0      ;VCTR s=4 dx=31 dy=13 z=7 [x32]
L4FC0:  .word $4320, $7040      ;VCTR s=4 dx=2 dy=25 z=7 [x32]
L4FC4:  .word $3140, $72C0      ;VCTR s=3 dx=11 dy=5 z=7 [x64]
L4FC8:  .word $4280, $7520      ;VCTR s=4 dx=-9 dy=20 z=7 [x32]
L4FCC:  .word $F67F             ;SVEC u=8 dx=-24 dy=-16 z=7
L4FCE:  .word $3200, $0080      ;VCTR s=3 dx=2 dy=8 z=0 [x64]
L4FD2:  .word $4320, $7480      ;VCTR s=4 dx=-4 dy=25 z=7 [x32]
L4FD6:  .word $2100, $7780      ;VCTR s=2 dx=-7 dy=2 z=7 [x128]
L4FDA:  .word $46A0, $76A0      ;VCTR s=4 dx=-21 dy=-21 z=7 [x32]
L4FDE:  .word $46E0, $74A0      ;VCTR s=4 dx=-5 dy=-23 z=7 [x32]
L4FE2:  .word $4080, $7240      ;VCTR s=4 dx=18 dy=4 z=7 [x32]
L4FE6:  .word $47E0, $74C0      ;VCTR s=4 dx=-6 dy=-31 z=7 [x32]
L4FEA:  .word $44A0, $72E0      ;VCTR s=4 dx=23 dy=-5 z=7 [x32]
L4FEE:  .word $4260, $7380      ;VCTR s=4 dx=28 dy=19 z=7 [x32]
L4FF2:  .word $4320, $7460      ;VCTR s=4 dx=-3 dy=25 z=7 [x32]
L4FF6:  .word $3180, $7280      ;VCTR s=3 dx=10 dy=6 z=7 [x64]
L4FFA:  .word $4260, $75A0      ;VCTR s=4 dx=-13 dy=19 z=7 [x32]
L4FFE:  .word $4680, $7680      ;VCTR s=4 dx=-20 dy=-20 z=7 [x32]
L5002:  .byte $84               ;.
L5003:  .byte $4E               ;N
L5004:  .word $4E9E, $4ED2      ;VCTR s=4 dx=-722 dy=-670 z=4 [raw]
L5008:  .word $4F06, $4F3A      ;VCTR s=4 dx=-826 dy=-774 z=4 [raw]
L500C:  .word $4F6A, $4F9E      ;VCTR s=4 dx=-926 dy=-874 z=4 [raw]
L5010:  .byte $CE, $4F          ;.O
L5012:  .word $5180, $0380      ;VCTR s=5 dx=56 dy=24 z=0 [x16]
L5016:  .word $FA0E             ;SVEC u=16 dx=-32 dy=32 z=0
L5018:  .word $F80F             ;SVEC u=16 dx=-48 dy=0 z=0
L501A:  .word $FE0E             ;SVEC u=16 dx=-32 dy=-32 z=0
L501C:  .word $FF08             ;SVEC u=16 dx=0 dy=-48 z=0
L501E:  .word $FE0A             ;SVEC u=16 dx=32 dy=-32 z=0
L5020:  .word $F80B             ;SVEC u=16 dx=48 dy=0 z=0
L5022:  .word $FA0A             ;SVEC u=16 dx=32 dy=32 z=0
L5024:  .word $FB08             ;SVEC u=16 dx=0 dy=48 z=0
L5026:  .word $5580, $0780      ;VCTR s=5 dx=-56 dy=-24 z=0 [x16]
L502A:  .byte $45               ;E
L502B:  .byte $C8               ;.
L502C:  .word $C84E             ;JSRL L509C ($509C)
L502E:  .word $C857             ;JSRL L50AE ($50AE)
L5030:  .word $C860             ;JSRL L50C0 ($50C0)
L5032:  .word $C869             ;JSRL L50D2 ($50D2)
L5034:  .word $C872             ;JSRL L50E4 ($50E4)
L5036:  .word $C87B             ;JSRL L50F6 ($50F6)
L5038:  .word $C884             ;JSRL L5108 ($5108)
L503A:  .word $C88D             ;JSRL L511A ($511A)
L503C:  .word $C896             ;JSRL L512C ($512C)
L503E:  .word $C89F             ;JSRL L513E ($513E)
L5040:  .word $C8A8             ;JSRL L5150 ($5150)
L5042:  .word $C8B1             ;JSRL L5162 ($5162)
L5044:  .word $C8BA             ;JSRL L5174 ($5174)
L5046:  .word $C8C3             ;JSRL L5186 ($5186)
L5048:  .word $C8CC             ;JSRL L5198 ($5198)
L504A:  .word $C8D5             ;JSRL L51AA ($51AA)
L504C:  .word $C8DE             ;JSRL L51BC ($51BC)
L504E:  .word $C8E7             ;JSRL L51CE ($51CE)
L5050:  .word $C8F0             ;JSRL L51E0 ($51E0)
L5052:  .word $C8F9             ;JSRL L51F2 ($51F2)
L5054:  .word $C902             ;JSRL L5204 ($5204)
L5056:  .word $C90B             ;JSRL L5216 ($5216)
L5058:  .word $C914             ;JSRL L5228 ($5228)
L505A:  .word $C91D             ;JSRL L523A ($523A)
L505C:  .word $C926             ;JSRL L524C ($524C)
L505E:  .word $C92F             ;JSRL L525E ($525E)
L5060:  .word $C938             ;JSRL L5270 ($5270)
L5062:  .word $C941             ;JSRL L5282 ($5282)
L5064:  .word $C94A             ;JSRL L5294 ($5294)
L5066:  .word $C953             ;JSRL L52A6 ($52A6)
L5068:  .word $C95C             ;JSRL L52B8 ($52B8)
L506A:  .byte $65               ;e
L506B:  .byte $C9               ;.
L506C:  .word $C969             ;JSRL L52D2 ($52D2)
L506E:  .word $C96F             ;JSRL L52DE ($52DE)
L5070:  .word $C975             ;JSRL L52EA ($52EA)
L5072:  .word $C97B             ;JSRL L52F6 ($52F6)
L5074:  .word $C981             ;JSRL L5302 ($5302)
L5076:  .word $C987             ;JSRL L530E ($530E)
L5078:  .word $C98D             ;JSRL L531A ($531A)
L507A:  .word $C993             ;JSRL L5326 ($5326)
L507C:  .word $C997             ;JSRL L532E ($532E)
L507E:  .word $C99D             ;JSRL L533A ($533A)
L5080:  .word $C9A3             ;JSRL L5346 ($5346)
L5082:  .word $C9A9             ;JSRL L5352 ($5352)
L5084:  .word $C9AF             ;JSRL L535E ($535E)
L5086:  .word $C9B5             ;JSRL L536A ($536A)
L5088:  .word $C9BB             ;JSRL L5376 ($5376)
L508A:  .word $4380, $7600      ;VCTR s=4 dx=-16 dy=28 z=7 [x32]
L508E:  .word $55C0, $7300      ;VCTR s=5 dx=48 dy=-28 z=7 [x16]
L5092:  .word $55C0, $7700      ;VCTR s=5 dx=-48 dy=-28 z=7 [x16]
L5096:  .word $4380, $7200      ;VCTR s=4 dx=16 dy=28 z=7 [x32]
L509A:  .word $D000             ;RTSL
L509C:  .word $4300, $76A0      ;VCTR s=4 dx=-21 dy=24 z=7 [x32]
L50A0:  .word $5520, $7340      ;VCTR s=5 dx=52 dy=-18 z=7 [x16]
L50A4:  .word $5650, $7690      ;VCTR s=5 dx=-41 dy=-37 z=7 [x16]
L50A8:  .word $43E0, $7140      ;VCTR s=4 dx=10 dy=31 z=7 [x32]
L50AC:  .word $D000             ;RTSL
L50AE:  .word $4280, $7720      ;VCTR s=4 dx=-25 dy=20 z=7 [x32]
L50B2:  .word $5480, $7370      ;VCTR s=5 dx=55 dy=-8 z=7 [x16]
L50B6:  .word $56C0, $7620      ;VCTR s=5 dx=-34 dy=-44 z=7 [x16]
L50BA:  .word $5200, $7040      ;VCTR s=5 dx=4 dy=32 z=7 [x16]
L50BE:  .word $D000             ;RTSL
L50C0:  .word $41C0, $77A0      ;VCTR s=4 dx=-29 dy=14 z=7 [x32]
L50C4:  .word $5040, $7380      ;VCTR s=5 dx=56 dy=4 z=7 [x16]
L50C8:  .word $5720, $7590      ;VCTR s=5 dx=-25 dy=-50 z=7 [x16]
L50CC:  .word $5200, $7420      ;VCTR s=5 dx=-2 dy=32 z=7 [x16]
L50D0:  .word $D000             ;RTSL
L50D2:  .word $4100, $77E0      ;VCTR s=4 dx=-31 dy=8 z=7 [x32]
L50D6:  .word $50F0, $7360      ;VCTR s=5 dx=54 dy=15 z=7 [x16]
L50DA:  .word $5760, $74F0      ;VCTR s=5 dx=-15 dy=-54 z=7 [x16]
L50DE:  .word $43E0, $7500      ;VCTR s=4 dx=-8 dy=31 z=7 [x32]
L50E2:  .word $D000             ;RTSL
L50E4:  .word $5020, $7600      ;VCTR s=5 dx=-32 dy=2 z=7 [x16]
L50E8:  .word $5190, $7320      ;VCTR s=5 dx=50 dy=25 z=7 [x16]
L50EC:  .word $5780, $7440      ;VCTR s=5 dx=-4 dy=-56 z=7 [x16]
L50F0:  .word $43A0, $75C0      ;VCTR s=4 dx=-14 dy=29 z=7 [x32]
L50F4:  .word $D000             ;RTSL
L50F6:  .word $5440, $7600      ;VCTR s=5 dx=-32 dy=-4 z=7 [x16]
L50FA:  .word $5220, $72C0      ;VCTR s=5 dx=44 dy=34 z=7 [x16]
L50FE:  .word $5770, $7080      ;VCTR s=5 dx=8 dy=-55 z=7 [x16]
L5102:  .word $4320, $7680      ;VCTR s=4 dx=-20 dy=25 z=7 [x32]
L5106:  .word $D000             ;RTSL
L5108:  .word $4540, $77E0      ;VCTR s=4 dx=-31 dy=-10 z=7 [x32]
L510C:  .word $5290, $7250      ;VCTR s=5 dx=37 dy=41 z=7 [x16]
L5110:  .word $5740, $7120      ;VCTR s=5 dx=18 dy=-52 z=7 [x16]
L5114:  .word $42A0, $7700      ;VCTR s=4 dx=-24 dy=21 z=7 [x32]
L5118:  .word $D000             ;RTSL
L511A:  .word $4600, $7780      ;VCTR s=4 dx=-28 dy=-16 z=7 [x32]
L511E:  .word $5300, $71C0      ;VCTR s=5 dx=28 dy=48 z=7 [x16]
L5122:  .word $5700, $71C0      ;VCTR s=5 dx=28 dy=-48 z=7 [x16]
L5126:  .word $4200, $7780      ;VCTR s=4 dx=-28 dy=16 z=7 [x32]
L512A:  .word $D000             ;RTSL
L512C:  .word $46A0, $7700      ;VCTR s=4 dx=-24 dy=-21 z=7 [x32]
L5130:  .word $5340, $7120      ;VCTR s=5 dx=18 dy=52 z=7 [x16]
L5134:  .word $5690, $7250      ;VCTR s=5 dx=37 dy=-41 z=7 [x16]
L5138:  .word $4140, $77E0      ;VCTR s=4 dx=-31 dy=10 z=7 [x32]
L513C:  .word $D000             ;RTSL
L513E:  .word $4720, $7680      ;VCTR s=4 dx=-20 dy=-25 z=7 [x32]
L5142:  .word $5370, $7080      ;VCTR s=5 dx=8 dy=55 z=7 [x16]
L5146:  .word $5620, $72C0      ;VCTR s=5 dx=44 dy=-34 z=7 [x16]
L514A:  .word $5040, $7600      ;VCTR s=5 dx=-32 dy=4 z=7 [x16]
L514E:  .word $D000             ;RTSL
L5150:  .word $47A0, $75C0      ;VCTR s=4 dx=-14 dy=-29 z=7 [x32]
L5154:  .word $5380, $7440      ;VCTR s=5 dx=-4 dy=56 z=7 [x16]
L5158:  .word $5590, $7320      ;VCTR s=5 dx=50 dy=-25 z=7 [x16]
L515C:  .word $5420, $7600      ;VCTR s=5 dx=-32 dy=-2 z=7 [x16]
L5160:  .word $D000             ;RTSL
L5162:  .word $47E0, $7500      ;VCTR s=4 dx=-8 dy=-31 z=7 [x32]
L5166:  .word $5360, $74F0      ;VCTR s=5 dx=-15 dy=54 z=7 [x16]
L516A:  .word $54F0, $7360      ;VCTR s=5 dx=54 dy=-15 z=7 [x16]
L516E:  .word $4500, $77E0      ;VCTR s=4 dx=-31 dy=-8 z=7 [x32]
L5172:  .word $D000             ;RTSL
L5174:  .word $5600, $7420      ;VCTR s=5 dx=-2 dy=-32 z=7 [x16]
L5178:  .word $5320, $7590      ;VCTR s=5 dx=-25 dy=50 z=7 [x16]
L517C:  .word $5440, $7380      ;VCTR s=5 dx=56 dy=-4 z=7 [x16]
L5180:  .word $45C0, $77A0      ;VCTR s=4 dx=-29 dy=-14 z=7 [x32]
L5184:  .word $D000             ;RTSL
L5186:  .word $5600, $7040      ;VCTR s=5 dx=4 dy=-32 z=7 [x16]
L518A:  .word $52C0, $7620      ;VCTR s=5 dx=-34 dy=44 z=7 [x16]
L518E:  .word $5080, $7370      ;VCTR s=5 dx=55 dy=8 z=7 [x16]
L5192:  .word $4680, $7720      ;VCTR s=4 dx=-25 dy=-20 z=7 [x32]
L5196:  .word $D000             ;RTSL
L5198:  .word $47E0, $7140      ;VCTR s=4 dx=10 dy=-31 z=7 [x32]
L519C:  .word $5250, $7690      ;VCTR s=5 dx=-41 dy=37 z=7 [x16]
L51A0:  .word $5120, $7340      ;VCTR s=5 dx=52 dy=18 z=7 [x16]
L51A4:  .word $4700, $76A0      ;VCTR s=4 dx=-21 dy=-24 z=7 [x32]
L51A8:  .word $D000             ;RTSL
L51AA:  .word $4780, $7200      ;VCTR s=4 dx=16 dy=-28 z=7 [x32]
L51AE:  .word $51C0, $7700      ;VCTR s=5 dx=-48 dy=28 z=7 [x16]
L51B2:  .word $51C0, $7300      ;VCTR s=5 dx=48 dy=28 z=7 [x16]
L51B6:  .word $4780, $7600      ;VCTR s=4 dx=-16 dy=-28 z=7 [x32]
L51BA:  .word $D000             ;RTSL
L51BC:  .word $4700, $72A0      ;VCTR s=4 dx=21 dy=-24 z=7 [x32]
L51C0:  .word $5120, $7740      ;VCTR s=5 dx=-52 dy=18 z=7 [x16]
L51C4:  .word $5250, $7290      ;VCTR s=5 dx=41 dy=37 z=7 [x16]
L51C8:  .word $47E0, $7540      ;VCTR s=4 dx=-10 dy=-31 z=7 [x32]
L51CC:  .word $D000             ;RTSL
L51CE:  .word $4680, $7320      ;VCTR s=4 dx=25 dy=-20 z=7 [x32]
L51D2:  .word $5080, $7770      ;VCTR s=5 dx=-55 dy=8 z=7 [x16]
L51D6:  .word $52C0, $7220      ;VCTR s=5 dx=34 dy=44 z=7 [x16]
L51DA:  .word $5600, $7440      ;VCTR s=5 dx=-4 dy=-32 z=7 [x16]
L51DE:  .word $D000             ;RTSL
L51E0:  .word $45C0, $73A0      ;VCTR s=4 dx=29 dy=-14 z=7 [x32]
L51E4:  .word $5440, $7780      ;VCTR s=5 dx=-56 dy=-4 z=7 [x16]
L51E8:  .word $5320, $7190      ;VCTR s=5 dx=25 dy=50 z=7 [x16]
L51EC:  .word $5600, $7020      ;VCTR s=5 dx=2 dy=-32 z=7 [x16]
L51F0:  .word $D000             ;RTSL
L51F2:  .word $4500, $73E0      ;VCTR s=4 dx=31 dy=-8 z=7 [x32]
L51F6:  .word $54F0, $7760      ;VCTR s=5 dx=-54 dy=-15 z=7 [x16]
L51FA:  .word $5360, $70F0      ;VCTR s=5 dx=15 dy=54 z=7 [x16]
L51FE:  .word $47E0, $7100      ;VCTR s=4 dx=8 dy=-31 z=7 [x32]
L5202:  .word $D000             ;RTSL
L5204:  .word $5420, $7200      ;VCTR s=5 dx=32 dy=-2 z=7 [x16]
L5208:  .word $5590, $7720      ;VCTR s=5 dx=-50 dy=-25 z=7 [x16]
L520C:  .word $5380, $7040      ;VCTR s=5 dx=4 dy=56 z=7 [x16]
L5210:  .word $47A0, $71C0      ;VCTR s=4 dx=14 dy=-29 z=7 [x32]
L5214:  .word $D000             ;RTSL
L5216:  .word $5040, $7200      ;VCTR s=5 dx=32 dy=4 z=7 [x16]
L521A:  .word $5620, $76C0      ;VCTR s=5 dx=-44 dy=-34 z=7 [x16]
L521E:  .word $5370, $7480      ;VCTR s=5 dx=-8 dy=55 z=7 [x16]
L5222:  .word $4720, $7280      ;VCTR s=4 dx=20 dy=-25 z=7 [x32]
L5226:  .word $D000             ;RTSL
L5228:  .word $4140, $73E0      ;VCTR s=4 dx=31 dy=10 z=7 [x32]
L522C:  .word $5690, $7650      ;VCTR s=5 dx=-37 dy=-41 z=7 [x16]
L5230:  .word $5340, $7520      ;VCTR s=5 dx=-18 dy=52 z=7 [x16]
L5234:  .word $46A0, $7300      ;VCTR s=4 dx=24 dy=-21 z=7 [x32]
L5238:  .word $D000             ;RTSL
L523A:  .word $4200, $7380      ;VCTR s=4 dx=28 dy=16 z=7 [x32]
L523E:  .word $5700, $75C0      ;VCTR s=5 dx=-28 dy=-48 z=7 [x16]
L5242:  .word $5300, $75C0      ;VCTR s=5 dx=-28 dy=48 z=7 [x16]
L5246:  .word $4600, $7380      ;VCTR s=4 dx=28 dy=-16 z=7 [x32]
L524A:  .word $D000             ;RTSL
L524C:  .word $42A0, $7300      ;VCTR s=4 dx=24 dy=21 z=7 [x32]
L5250:  .word $5740, $7520      ;VCTR s=5 dx=-18 dy=-52 z=7 [x16]
L5254:  .word $5290, $7650      ;VCTR s=5 dx=-37 dy=41 z=7 [x16]
L5258:  .word $4540, $73E0      ;VCTR s=4 dx=31 dy=-10 z=7 [x32]
L525C:  .word $D000             ;RTSL
L525E:  .word $4320, $7280      ;VCTR s=4 dx=20 dy=25 z=7 [x32]
L5262:  .word $5770, $7480      ;VCTR s=5 dx=-8 dy=-55 z=7 [x16]
L5266:  .word $5220, $76C0      ;VCTR s=5 dx=-44 dy=34 z=7 [x16]
L526A:  .word $5440, $7200      ;VCTR s=5 dx=32 dy=-4 z=7 [x16]
L526E:  .word $D000             ;RTSL
L5270:  .word $43A0, $71C0      ;VCTR s=4 dx=14 dy=29 z=7 [x32]
L5274:  .word $5780, $7040      ;VCTR s=5 dx=4 dy=-56 z=7 [x16]
L5278:  .word $5190, $7720      ;VCTR s=5 dx=-50 dy=25 z=7 [x16]
L527C:  .word $5020, $7200      ;VCTR s=5 dx=32 dy=2 z=7 [x16]
L5280:  .word $D000             ;RTSL
L5282:  .word $43E0, $7100      ;VCTR s=4 dx=8 dy=31 z=7 [x32]
L5286:  .word $5760, $70F0      ;VCTR s=5 dx=15 dy=-54 z=7 [x16]
L528A:  .word $50F0, $7760      ;VCTR s=5 dx=-54 dy=15 z=7 [x16]
L528E:  .word $4100, $73E0      ;VCTR s=4 dx=31 dy=8 z=7 [x32]
L5292:  .word $D000             ;RTSL
L5294:  .word $5200, $7020      ;VCTR s=5 dx=2 dy=32 z=7 [x16]
L5298:  .word $5720, $7190      ;VCTR s=5 dx=25 dy=-50 z=7 [x16]
L529C:  .word $5040, $7780      ;VCTR s=5 dx=-56 dy=4 z=7 [x16]
L52A0:  .word $41C0, $73A0      ;VCTR s=4 dx=29 dy=14 z=7 [x32]
L52A4:  .word $D000             ;RTSL
L52A6:  .word $5200, $7440      ;VCTR s=5 dx=-4 dy=32 z=7 [x16]
L52AA:  .word $56C0, $7220      ;VCTR s=5 dx=34 dy=-44 z=7 [x16]
L52AE:  .word $5480, $7770      ;VCTR s=5 dx=-55 dy=-8 z=7 [x16]
L52B2:  .word $4280, $7320      ;VCTR s=4 dx=25 dy=20 z=7 [x32]
L52B6:  .word $D000             ;RTSL
L52B8:  .word $43E0, $7540      ;VCTR s=4 dx=-10 dy=31 z=7 [x32]
L52BC:  .word $5650, $7290      ;VCTR s=5 dx=41 dy=-37 z=7 [x16]
L52C0:  .word $5520, $7740      ;VCTR s=5 dx=-52 dy=-18 z=7 [x16]
L52C4:  .word $4300, $72A0      ;VCTR s=4 dx=21 dy=24 z=7 [x32]
L52C8:  .word $D000             ;RTSL
L52CA:  .word $F809             ;SVEC u=16 dx=16 dy=0 z=0
L52CC:  .word $C845             ;JSRL L508A ($508A)
L52CE:  .word $F80E             ;SVEC u=16 dx=-32 dy=0 z=0
L52D0:  .word $E8D5             ;JMPL L51AA ($51AA)
L52D2:  .word $4060, $0200      ;VCTR s=4 dx=16 dy=3 z=0 [x32]
L52D6:  .word $C84E             ;JSRL L509C ($509C)
L52D8:  .word $5460, $0600      ;VCTR s=5 dx=-32 dy=-6 z=0 [x16]
L52DC:  .word $E8DE             ;JMPL L51BC ($51BC)
L52DE:  .word $3180, $03C0      ;VCTR s=3 dx=15 dy=6 z=0 [x64]
L52E2:  .word $C857             ;JSRL L50AE ($50AE)
L52E4:  .word $4580, $07C0      ;VCTR s=4 dx=-30 dy=-12 z=0 [x32]
L52E8:  .word $E8E7             ;JMPL L51CE ($51CE)
L52EA:  .word $3240, $0340      ;VCTR s=3 dx=13 dy=9 z=0 [x64]
L52EE:  .word $C860             ;JSRL L50C0 ($50C0)
L52F0:  .word $4640, $0740      ;VCTR s=4 dx=-26 dy=-18 z=0 [x32]
L52F4:  .word $E8F0             ;JMPL L51E0 ($51E0)
L52F6:  .word $32C0, $02C0      ;VCTR s=3 dx=11 dy=11 z=0 [x64]
L52FA:  .word $C869             ;JSRL L50D2 ($50D2)
L52FC:  .word $46C0, $06C0      ;VCTR s=4 dx=-22 dy=-22 z=0 [x32]
L5300:  .word $E8F9             ;JMPL L51F2 ($51F2)
L5302:  .word $3340, $0240      ;VCTR s=3 dx=9 dy=13 z=0 [x64]
L5306:  .word $C872             ;JSRL L50E4 ($50E4)
L5308:  .word $4740, $0640      ;VCTR s=4 dx=-18 dy=-26 z=0 [x32]
L530C:  .word $E902             ;JMPL L5204 ($5204)
L530E:  .word $33C0, $0180      ;VCTR s=3 dx=6 dy=15 z=0 [x64]
L5312:  .word $C87B             ;JSRL L50F6 ($50F6)
L5314:  .word $47C0, $0580      ;VCTR s=4 dx=-12 dy=-30 z=0 [x32]
L5318:  .word $E90B             ;JMPL L5216 ($5216)
L531A:  .word $4200, $0060      ;VCTR s=4 dx=3 dy=16 z=0 [x32]
L531E:  .word $C884             ;JSRL L5108 ($5108)
L5320:  .word $5600, $0460      ;VCTR s=5 dx=-6 dy=-32 z=0 [x16]
L5324:  .word $E914             ;JMPL L5228 ($5228)
L5326:  .word $F908             ;SVEC u=16 dx=0 dy=16 z=0
L5328:  .word $C88D             ;JSRL L511A ($511A)
L532A:  .word $FE08             ;SVEC u=16 dx=0 dy=-32 z=0
L532C:  .word $E91D             ;JMPL L523A ($523A)
L532E:  .word $4200, $0460      ;VCTR s=4 dx=-3 dy=16 z=0 [x32]
L5332:  .word $C896             ;JSRL L512C ($512C)
L5334:  .word $5600, $0060      ;VCTR s=5 dx=6 dy=-32 z=0 [x16]
L5338:  .word $E926             ;JMPL L524C ($524C)
L533A:  .word $33C0, $0580      ;VCTR s=3 dx=-6 dy=15 z=0 [x64]
L533E:  .word $C89F             ;JSRL L513E ($513E)
L5340:  .word $47C0, $0180      ;VCTR s=4 dx=12 dy=-30 z=0 [x32]
L5344:  .word $E92F             ;JMPL L525E ($525E)
L5346:  .word $3340, $0640      ;VCTR s=3 dx=-9 dy=13 z=0 [x64]
L534A:  .word $C8A8             ;JSRL L5150 ($5150)
L534C:  .word $4740, $0240      ;VCTR s=4 dx=18 dy=-26 z=0 [x32]
L5350:  .word $E938             ;JMPL L5270 ($5270)
L5352:  .word $32C0, $06C0      ;VCTR s=3 dx=-11 dy=11 z=0 [x64]
L5356:  .word $C8B1             ;JSRL L5162 ($5162)
L5358:  .word $46C0, $02C0      ;VCTR s=4 dx=22 dy=-22 z=0 [x32]
L535C:  .word $E941             ;JMPL L5282 ($5282)
L535E:  .word $3240, $0740      ;VCTR s=3 dx=-13 dy=9 z=0 [x64]
L5362:  .word $C8BA             ;JSRL L5174 ($5174)
L5364:  .word $4640, $0340      ;VCTR s=4 dx=26 dy=-18 z=0 [x32]
L5368:  .word $E94A             ;JMPL L5294 ($5294)
L536A:  .word $3180, $07C0      ;VCTR s=3 dx=-15 dy=6 z=0 [x64]
L536E:  .word $C8C3             ;JSRL L5186 ($5186)
L5370:  .word $4580, $03C0      ;VCTR s=4 dx=30 dy=-12 z=0 [x32]
L5374:  .word $E953             ;JMPL L52A6 ($52A6)
L5376:  .word $4060, $0600      ;VCTR s=4 dx=-16 dy=3 z=0 [x32]
L537A:  .word $C8CC             ;JSRL L5198 ($5198)
L537C:  .word $5460, $0200      ;VCTR s=5 dx=32 dy=-6 z=0 [x16]
L5380:  .word $E95C             ;JMPL L52B8 ($52B8)
L5382:  .word $A080, $01A0      ;LABS size=0 x=416 y=128
L5386:  .word $7000, $0000      ;WAIT t=7 z=0
L538A:  .word $C9D7             ;JSRL L53AE ($53AE)
L538C:  .word $3180, $0200      ;VCTR s=3 dx=8 dy=6 z=0 [x64]
L5390:  .word $F875             ;SVEC u=4 dx=-4 dy=0 z=7
L5392:  .word $FD70             ;SVEC u=4 dx=0 dy=-4 z=7
L5394:  .word $F871             ;SVEC u=4 dx=4 dy=0 z=7
L5396:  .word $3480, $0200      ;VCTR s=3 dx=8 dy=-2 z=0 [x64]
L539A:  .word $C9D7             ;JSRL L53AE ($53AE)
L539C:  .word $F901             ;SVEC u=4 dx=4 dy=4 z=0
L539E:  .word $F871             ;SVEC u=4 dx=4 dy=0 z=7
L53A0:  .word $1300, $7000      ;VCTR s=1 dx=0 dy=3 z=7 [x256]
L53A4:  .word $F875             ;SVEC u=4 dx=-4 dy=0 z=7
L53A6:  .word $F770             ;SVEC u=2 dx=0 dy=-6 z=7
L53A8:  .word $34C0, $0300      ;VCTR s=3 dx=12 dy=-3 z=0 [x64]
L53AC:  .word $D000             ;RTSL
L53AE:  .word $F573             ;SVEC u=2 dx=6 dy=-2 z=7
L53B0:  .word $F173             ;SVEC u=2 dx=6 dy=2 z=7
L53B2:  .word $F178             ;SVEC u=8 dx=0 dy=8 z=7
L53B4:  .word $F177             ;SVEC u=2 dx=-6 dy=2 z=7
L53B6:  .word $F577             ;SVEC u=2 dx=-6 dy=-2 z=7
L53B8:  .word $F578             ;SVEC u=8 dx=0 dy=-8 z=7
L53BA:  .word $D000             ;RTSL
L53BC:  .word $1200, $3E28      ;VCTR s=1 dx=-552 dy=512 z=3 [raw]
L53C0:  .word $6954, $957F      ;VCTR s=6 dx=-383 dy=340 z=9 [raw]
L53C4:  .word $B4AB             ;HALT
L53C6:  .word $5600, $0580      ;VCTR s=5 dx=-24 dy=-32 z=0 [x16]
L53CA:  .word $5080, $0380      ;VCTR s=5 dx=56 dy=8 z=0 [x16]
L53CE:  .word $F909             ;SVEC u=16 dx=16 dy=16 z=0
L53D0:  .word $5180, $0700      ;VCTR s=5 dx=-48 dy=24 z=0 [x16]
L53D4:  .word $5580, $0700      ;VCTR s=5 dx=-48 dy=-24 z=0 [x16]
L53D8:  .word $FD09             ;SVEC u=16 dx=16 dy=-16 z=0
L53DA:  .word $5480, $0380      ;VCTR s=5 dx=56 dy=-8 z=0 [x16]
L53DE:  .word $6300, $04C0      ;VCTR s=6 dx=-24 dy=96 z=0 [x8]
L53E2:  .word $6700, $04C0      ;VCTR s=6 dx=-24 dy=-96 z=0 [x8]
L53E6:  .word $F60B             ;SVEC u=8 dx=24 dy=-16 z=0
L53E8:  .word $F20B             ;SVEC u=8 dx=24 dy=16 z=0
L53EA:  .word $5620, $0550      ;VCTR s=5 dx=-21 dy=-34 z=0 [x16]
L53EE:  .word $50D0, $0370      ;VCTR s=5 dx=55 dy=13 z=0 [x16]
L53F2:  .word $4240, $01E0      ;VCTR s=4 dx=15 dy=18 z=0 [x32]
L53F6:  .word $5130, $0730      ;VCTR s=5 dx=-51 dy=19 z=0 [x16]
L53FA:  .word $55D0, $06D0      ;VCTR s=5 dx=-45 dy=-29 z=0 [x16]
L53FE:  .word $45C0, $0240      ;VCTR s=4 dx=18 dy=-14 z=0 [x32]
L5402:  .word $5420, $0380      ;VCTR s=5 dx=56 dy=-2 z=0 [x16]
L5406:  .word $62E8, $0508      ;VCTR s=6 dx=-33 dy=93 z=0 [x8]
L540A:  .word $6710, $0478      ;VCTR s=6 dx=-15 dy=-98 z=0 [x8]
L540E:  .word $45C0, $0340      ;VCTR s=4 dx=26 dy=-14 z=0 [x32]
L5412:  .word $4260, $02C0      ;VCTR s=4 dx=22 dy=19 z=0 [x32]
L5416:  .word $5640, $0510      ;VCTR s=5 dx=-17 dy=-36 z=0 [x16]
L541A:  .word $5130, $0350      ;VCTR s=5 dx=53 dy=19 z=0 [x16]
L541E:  .word $4260, $01A0      ;VCTR s=4 dx=13 dy=19 z=0 [x32]
L5422:  .word $50E0, $0740      ;VCTR s=5 dx=-52 dy=14 z=0 [x16]
L5426:  .word $5610, $06B0      ;VCTR s=5 dx=-43 dy=-33 z=0 [x16]
L542A:  .word $45A0, $0260      ;VCTR s=4 dx=19 dy=-13 z=0 [x32]
L542E:  .word $5030, $0390      ;VCTR s=5 dx=57 dy=3 z=0 [x16]
L5432:  .word $62D0, $0550      ;VCTR s=6 dx=-42 dy=90 z=0 [x8]
L5436:  .word $6718, $0428      ;VCTR s=6 dx=-5 dy=-99 z=0 [x8]
L543A:  .word $4560, $0340      ;VCTR s=4 dx=26 dy=-11 z=0 [x32]
L543E:  .word $4280, $02A0      ;VCTR s=4 dx=21 dy=20 z=0 [x32]
L5442:  .word $5660, $04E0      ;VCTR s=5 dx=-14 dy=-38 z=0 [x16]
L5446:  .word $5180, $0340      ;VCTR s=5 dx=52 dy=24 z=0 [x16]
L544A:  .word $4280, $0140      ;VCTR s=4 dx=10 dy=20 z=0 [x32]
L544E:  .word $5090, $0750      ;VCTR s=5 dx=-53 dy=9 z=0 [x16]
L5452:  .word $5650, $0670      ;VCTR s=5 dx=-39 dy=-37 z=0 [x16]
L5456:  .word $4540, $0280      ;VCTR s=4 dx=20 dy=-10 z=0 [x32]
L545A:  .word $5080, $0380      ;VCTR s=5 dx=56 dy=8 z=0 [x16]
L545E:  .word $62A8, $0598      ;VCTR s=6 dx=-51 dy=85 z=0 [x8]
L5462:  .word $6718, $0028      ;VCTR s=6 dx=5 dy=-99 z=0 [x8]
L5466:  .word $4500, $0380      ;VCTR s=4 dx=28 dy=-8 z=0 [x32]
L546A:  .word $42C0, $0240      ;VCTR s=4 dx=18 dy=22 z=0 [x32]
L546E:  .word $5670, $04A0      ;VCTR s=5 dx=-10 dy=-39 z=0 [x16]
L5472:  .word $51D0, $0310      ;VCTR s=5 dx=49 dy=29 z=0 [x16]
L5476:  .word $42A0, $0100      ;VCTR s=4 dx=8 dy=21 z=0 [x32]
L547A:  .word $5040, $0750      ;VCTR s=5 dx=-53 dy=4 z=0 [x16]
L547E:  .word $5690, $0630      ;VCTR s=5 dx=-35 dy=-41 z=0 [x16]
L5482:  .word $4500, $02A0      ;VCTR s=4 dx=21 dy=-8 z=0 [x32]
L5486:  .word $50E0, $0360      ;VCTR s=5 dx=54 dy=14 z=0 [x16]
L548A:  .word $6278, $05D0      ;VCTR s=6 dx=-58 dy=79 z=0 [x8]
L548E:  .word $6710, $0070      ;VCTR s=6 dx=14 dy=-98 z=0 [x8]
L5492:  .word $44A0, $0380      ;VCTR s=4 dx=28 dy=-5 z=0 [x32]
L5496:  .word $F30A             ;SVEC u=8 dx=16 dy=24 z=0
L5498:  .word $5680, $0460      ;VCTR s=5 dx=-6 dy=-40 z=0 [x16]
L549C:  .word $5220, $02E0      ;VCTR s=5 dx=46 dy=34 z=0 [x16]
L54A0:  .word $42C0, $00C0      ;VCTR s=4 dx=6 dy=22 z=0 [x32]
L54A4:  .word $5420, $0760      ;VCTR s=5 dx=-54 dy=-2 z=0 [x16]
L54A8:  .word $56C0, $05F0      ;VCTR s=5 dx=-31 dy=-44 z=0 [x16]
L54AC:  .word $44C0, $02C0      ;VCTR s=4 dx=22 dy=-6 z=0 [x32]
L54B0:  .word $5130, $0350      ;VCTR s=5 dx=53 dy=19 z=0 [x16]
L54B4:  .word $6248, $0610      ;VCTR s=6 dx=-66 dy=73 z=0 [x8]
L54B8:  .word $6700, $00C0      ;VCTR s=6 dx=24 dy=-96 z=0 [x8]
L54BC:  .word $4440, $03A0      ;VCTR s=4 dx=29 dy=-2 z=0 [x32]
L54C0:  .word $4320, $01A0      ;VCTR s=4 dx=13 dy=25 z=0 [x32]
L54C4:  .word $5680, $0420      ;VCTR s=5 dx=-2 dy=-40 z=0 [x16]
L54C8:  .word $5260, $02A0      ;VCTR s=5 dx=42 dy=38 z=0 [x16]
L54CC:  .word $42C0, $0080      ;VCTR s=4 dx=4 dy=22 z=0 [x32]
L54D0:  .word $5470, $0750      ;VCTR s=5 dx=-53 dy=-7 z=0 [x16]
L54D4:  .word $56E0, $05A0      ;VCTR s=5 dx=-26 dy=-46 z=0 [x16]
L54D8:  .word $44A0, $02C0      ;VCTR s=4 dx=22 dy=-5 z=0 [x32]
L54DC:  .word $5190, $0330      ;VCTR s=5 dx=51 dy=25 z=0 [x16]
L54E0:  .word $6210, $0650      ;VCTR s=6 dx=-74 dy=66 z=0 [x8]
L54E4:  .word $66E8, $0110      ;VCTR s=6 dx=34 dy=-93 z=0 [x8]
L54E8:  .word $4000, $03A0      ;VCTR s=4 dx=29 dy=0 z=0 [x32]
L54EC:  .word $4360, $0160      ;VCTR s=4 dx=11 dy=27 z=0 [x32]
L54F0:  .word $5680, $0020      ;VCTR s=5 dx=2 dy=-40 z=0 [x16]
L54F4:  .word $52A0, $0260      ;VCTR s=5 dx=38 dy=42 z=0 [x16]
L54F8:  .word $42C0, $0040      ;VCTR s=4 dx=2 dy=22 z=0 [x32]
L54FC:  .word $54C0, $0740      ;VCTR s=5 dx=-52 dy=-12 z=0 [x16]
L5500:  .word $5710, $0560      ;VCTR s=5 dx=-22 dy=-49 z=0 [x16]
L5504:  .word $4440, $02C0      ;VCTR s=4 dx=22 dy=-2 z=0 [x32]
L5508:  .word $51D0, $0310      ;VCTR s=5 dx=49 dy=29 z=0 [x16]
L550C:  .word $61D8, $0680      ;VCTR s=6 dx=-80 dy=59 z=0 [x8]
L5510:  .word $66C8, $0158      ;VCTR s=6 dx=43 dy=-89 z=0 [x8]
L5514:  .word $4060, $0380      ;VCTR s=4 dx=28 dy=3 z=0 [x32]
L5518:  .word $4360, $0120      ;VCTR s=4 dx=9 dy=27 z=0 [x32]
L551C:  .word $5680, $0060      ;VCTR s=5 dx=6 dy=-40 z=0 [x16]
L5520:  .word $52E0, $0220      ;VCTR s=5 dx=34 dy=46 z=0 [x16]
L5524:  .word $42C0, $0000      ;VCTR s=4 dx=0 dy=22 z=0 [x32]
L5528:  .word $5510, $0730      ;VCTR s=5 dx=-51 dy=-17 z=0 [x16]
L552C:  .word $5730, $0510      ;VCTR s=5 dx=-17 dy=-51 z=0 [x16]
L5530:  .word $4000, $02C0      ;VCTR s=4 dx=22 dy=0 z=0 [x32]
L5534:  .word $5220, $02E0      ;VCTR s=5 dx=46 dy=34 z=0 [x16]
L5538:  .word $6198, $06A8      ;VCTR s=6 dx=-85 dy=51 z=0 [x8]
L553C:  .word $66A8, $0198      ;VCTR s=6 dx=51 dy=-85 z=0 [x8]
L5540:  .word $40C0, $0380      ;VCTR s=4 dx=28 dy=6 z=0 [x32]
L5544:  .word $4380, $00C0      ;VCTR s=4 dx=6 dy=28 z=0 [x32]
L5548:  .word $5600, $0580      ;VCTR s=5 dx=-24 dy=-32 z=0 [x16]
L554C:  .word $5080, $7380      ;VCTR s=5 dx=56 dy=8 z=7 [x16]
L5550:  .word $F979             ;SVEC u=16 dx=16 dy=16 z=7
L5552:  .word $5180, $7700      ;VCTR s=5 dx=-48 dy=24 z=7 [x16]
L5556:  .word $5580, $7700      ;VCTR s=5 dx=-48 dy=-24 z=7 [x16]
L555A:  .word $FD79             ;SVEC u=16 dx=16 dy=-16 z=7
L555C:  .word $5480, $7380      ;VCTR s=5 dx=56 dy=-8 z=7 [x16]
L5560:  .word $6300, $74C0      ;VCTR s=6 dx=-24 dy=96 z=7 [x8]
L5564:  .word $6700, $74C0      ;VCTR s=6 dx=-24 dy=-96 z=7 [x8]
L5568:  .word $7080, $0220      ;VCTR s=7 dx=136 dy=32 z=0 [x4]
L556C:  .word $D000             ;RTSL

CHAR_A:
L556E:  .word $FA70             ;SVEC u=4 dx=0 dy=8 z=7
L5570:  .word $F272             ;SVEC u=2 dx=4 dy=4 z=7
L5572:  .word $F672             ;SVEC u=2 dx=4 dy=-4 z=7
L5574:  .word $FE70             ;SVEC u=4 dx=0 dy=-8 z=7
L5576:  .word $F906             ;SVEC u=4 dx=-8 dy=4 z=0
L5578:  .word $F872             ;SVEC u=4 dx=8 dy=0 z=7
L557A:  .word $F602             ;SVEC u=2 dx=4 dy=-4 z=0
L557C:  .word $D000             ;RTSL

CHAR_B:
L557E:  .word $FB70             ;SVEC u=4 dx=0 dy=12 z=7
L5580:  .word $F073             ;SVEC u=2 dx=6 dy=0 z=7
L5582:  .word $F571             ;SVEC u=2 dx=2 dy=-2 z=7
L5584:  .word $F570             ;SVEC u=2 dx=0 dy=-2 z=7
L5586:  .word $F575             ;SVEC u=2 dx=-2 dy=-2 z=7
L5588:  .word $F077             ;SVEC u=2 dx=-6 dy=0 z=7
L558A:  .word $F003             ;SVEC u=2 dx=6 dy=0 z=0
L558C:  .word $F571             ;SVEC u=2 dx=2 dy=-2 z=7
L558E:  .word $F570             ;SVEC u=2 dx=0 dy=-2 z=7
L5590:  .word $F575             ;SVEC u=2 dx=-2 dy=-2 z=7
L5592:  .word $F077             ;SVEC u=2 dx=-6 dy=0 z=7
L5594:  .word $EB0A             ;JMPL CHAR_SPACE ($5614)

CHAR_C:
L5596:  .word $FB70             ;SVEC u=4 dx=0 dy=12 z=7
L5598:  .word $F872             ;SVEC u=4 dx=8 dy=0 z=7
L559A:  .word $FF06             ;SVEC u=4 dx=-8 dy=-12 z=0
L559C:  .word $EB58             ;JMPL L56B0 ($56B0)

CHAR_D:
L559E:  .word $FB70             ;SVEC u=4 dx=0 dy=12 z=7
L55A0:  .word $F072             ;SVEC u=2 dx=4 dy=0 z=7
L55A2:  .word $F672             ;SVEC u=2 dx=4 dy=-4 z=7
L55A4:  .word $F670             ;SVEC u=2 dx=0 dy=-4 z=7
L55A6:  .word $F676             ;SVEC u=2 dx=-4 dy=-4 z=7
L55A8:  .word $F076             ;SVEC u=2 dx=-4 dy=0 z=7
L55AA:  .word $EB0A             ;JMPL CHAR_SPACE ($5614)

CHAR_E:
L55AC:  .word $F872             ;SVEC u=4 dx=8 dy=0 z=7
L55AE:  .word $F806             ;SVEC u=4 dx=-8 dy=0 z=0

CHAR_F:
L55B0:  .word $FB70             ;SVEC u=4 dx=0 dy=12 z=7
L55B2:  .word $F872             ;SVEC u=4 dx=8 dy=0 z=7
L55B4:  .word $F705             ;SVEC u=2 dx=-2 dy=-6 z=0
L55B6:  .word $F077             ;SVEC u=2 dx=-6 dy=0 z=7
L55B8:  .word $F700             ;SVEC u=2 dx=0 dy=-6 z=0
L55BA:  .word $F803             ;SVEC u=4 dx=12 dy=0 z=0
L55BC:  .word $D000             ;RTSL

CHAR_G:
L55BE:  .word $FB70             ;SVEC u=4 dx=0 dy=12 z=7
L55C0:  .word $F872             ;SVEC u=4 dx=8 dy=0 z=7
L55C2:  .word $F670             ;SVEC u=2 dx=0 dy=-4 z=7
L55C4:  .word $F606             ;SVEC u=2 dx=-4 dy=-4 z=0
L55C6:  .word $F072             ;SVEC u=2 dx=4 dy=0 z=7
L55C8:  .word $F670             ;SVEC u=2 dx=0 dy=-4 z=7
L55CA:  .word $EB09             ;JMPL L5612 ($5612)

CHAR_H:
L55CC:  .word $FB70             ;SVEC u=4 dx=0 dy=12 z=7
L55CE:  .word $F700             ;SVEC u=2 dx=0 dy=-6 z=0
L55D0:  .word $F872             ;SVEC u=4 dx=8 dy=0 z=7
L55D2:  .word $F300             ;SVEC u=2 dx=0 dy=6 z=0
L55D4:  .word $EB71             ;JMPL L56E2 ($56E2)

CHAR_I:
L55D6:  .word $F872             ;SVEC u=4 dx=8 dy=0 z=7
L55D8:  .word $FB06             ;SVEC u=4 dx=-8 dy=12 z=0
L55DA:  .word $F872             ;SVEC u=4 dx=8 dy=0 z=7
L55DC:  .word $F006             ;SVEC u=2 dx=-4 dy=0 z=0
L55DE:  .word $FF70             ;SVEC u=4 dx=0 dy=-12 z=7
L55E0:  .word $F802             ;SVEC u=4 dx=8 dy=0 z=0
L55E2:  .word $D000             ;RTSL

CHAR_J:
L55E4:  .word $F200             ;SVEC u=2 dx=0 dy=4 z=0
L55E6:  .word $F672             ;SVEC u=2 dx=4 dy=-4 z=7
L55E8:  .word $F072             ;SVEC u=2 dx=4 dy=0 z=7
L55EA:  .word $EB36             ;JMPL L566C ($566C)

CHAR_K:
L55EC:  .word $FB70             ;SVEC u=4 dx=0 dy=12 z=7
L55EE:  .word $F003             ;SVEC u=2 dx=6 dy=0 z=0
L55F0:  .word $F777             ;SVEC u=2 dx=-6 dy=-6 z=7
L55F2:  .word $F773             ;SVEC u=2 dx=6 dy=-6 z=7
L55F4:  .word $F003             ;SVEC u=2 dx=6 dy=0 z=0
L55F6:  .word $D000             ;RTSL

CHAR_L:
L55F8:  .word $FB00             ;SVEC u=4 dx=0 dy=12 z=0
L55FA:  .word $FF70             ;SVEC u=4 dx=0 dy=-12 z=7
L55FC:  .word $EB58             ;JMPL L56B0 ($56B0)

CHAR_M:
L55FE:  .word $FB70             ;SVEC u=4 dx=0 dy=12 z=7
L5600:  .word $F672             ;SVEC u=2 dx=4 dy=-4 z=7
L5602:  .word $F272             ;SVEC u=2 dx=4 dy=4 z=7
L5604:  .word $EB71             ;JMPL L56E2 ($56E2)

CHAR_N:
L5606:  .word $FB70             ;SVEC u=4 dx=0 dy=12 z=7
L5608:  .word $FF72             ;SVEC u=4 dx=8 dy=-12 z=7
L560A:  .word $EB36             ;JMPL L566C ($566C)

CHAR_O:
L560C:  .word $FB70             ;SVEC u=4 dx=0 dy=12 z=7
L560E:  .word $F872             ;SVEC u=4 dx=8 dy=0 z=7
L5610:  .word $FF70             ;SVEC u=4 dx=0 dy=-12 z=7
L5612:  .word $F876             ;SVEC u=4 dx=-8 dy=0 z=7

CHAR_SPACE:
L5614:  .word $F803             ;SVEC u=4 dx=12 dy=0 z=0
L5616:  .word $D000             ;RTSL

CHAR_P:
L5618:  .word $FB70             ;SVEC u=4 dx=0 dy=12 z=7
L561A:  .word $F872             ;SVEC u=4 dx=8 dy=0 z=7
L561C:  .word $F770             ;SVEC u=2 dx=0 dy=-6 z=7
L561E:  .word $F876             ;SVEC u=4 dx=-8 dy=0 z=7
L5620:  .word $EADC             ;JMPL L55B8 ($55B8)

CHAR_Q:
L5622:  .word $FB70             ;SVEC u=4 dx=0 dy=12 z=7
L5624:  .word $F872             ;SVEC u=4 dx=8 dy=0 z=7
L5626:  .word $FE70             ;SVEC u=4 dx=0 dy=-8 z=7
L5628:  .word $F676             ;SVEC u=2 dx=-4 dy=-4 z=7
L562A:  .word $F076             ;SVEC u=2 dx=-4 dy=0 z=7
L562C:  .word $F202             ;SVEC u=2 dx=4 dy=4 z=0
L562E:  .word $F672             ;SVEC u=2 dx=4 dy=-4 z=7
L5630:  .word $EB59             ;JMPL L56B2 ($56B2)

CHAR_R:
L5632:  .word $FB70             ;SVEC u=4 dx=0 dy=12 z=7
L5634:  .word $F872             ;SVEC u=4 dx=8 dy=0 z=7
L5636:  .word $F770             ;SVEC u=2 dx=0 dy=-6 z=7
L5638:  .word $F876             ;SVEC u=4 dx=-8 dy=0 z=7
L563A:  .word $F001             ;SVEC u=2 dx=2 dy=0 z=0
L563C:  .word $F773             ;SVEC u=2 dx=6 dy=-6 z=7
L563E:  .word $EB59             ;JMPL L56B2 ($56B2)
L5640:  .word $F200             ;SVEC u=2 dx=0 dy=4 z=0
L5642:  .word $FA73             ;SVEC u=4 dx=12 dy=8 z=7
L5644:  .word $F906             ;SVEC u=4 dx=-8 dy=4 z=0
L5646:  .word $FE70             ;SVEC u=4 dx=0 dy=-8 z=7
L5648:  .word $F601             ;SVEC u=2 dx=2 dy=-4 z=0
L564A:  .word $F072             ;SVEC u=2 dx=4 dy=0 z=7
L564C:  .word $F670             ;SVEC u=2 dx=0 dy=-4 z=7
L564E:  .word $F076             ;SVEC u=2 dx=-4 dy=0 z=7
L5650:  .word $F670             ;SVEC u=2 dx=0 dy=-4 z=7
L5652:  .word $F072             ;SVEC u=2 dx=4 dy=0 z=7
L5654:  .word $D000             ;RTSL

CHAR_S:
L5656:  .word $F872             ;SVEC u=4 dx=8 dy=0 z=7
L5658:  .word $F370             ;SVEC u=2 dx=0 dy=6 z=7
L565A:  .word $F876             ;SVEC u=4 dx=-8 dy=0 z=7
L565C:  .word $F370             ;SVEC u=2 dx=0 dy=6 z=7
L565E:  .word $F872             ;SVEC u=4 dx=8 dy=0 z=7
L5660:  .word $EB37             ;JMPL L566E ($566E)

CHAR_T:
L5662:  .word $FB00             ;SVEC u=4 dx=0 dy=12 z=0
L5664:  .word $EAED             ;JMPL L55DA ($55DA)

CHAR_U:
L5666:  .word $FB00             ;SVEC u=4 dx=0 dy=12 z=0
L5668:  .word $FF70             ;SVEC u=4 dx=0 dy=-12 z=7
L566A:  .word $F872             ;SVEC u=4 dx=8 dy=0 z=7
L566C:  .word $FB70             ;SVEC u=4 dx=0 dy=12 z=7
L566E:  .word $FF01             ;SVEC u=4 dx=4 dy=-12 z=0
L5670:  .word $D000             ;RTSL

CHAR_V:
L5672:  .word $FB00             ;SVEC u=4 dx=0 dy=12 z=0
L5674:  .word $FF71             ;SVEC u=4 dx=4 dy=-12 z=7
L5676:  .word $FB71             ;SVEC u=4 dx=4 dy=12 z=7
L5678:  .word $EB37             ;JMPL L566E ($566E)

CHAR_W:
L567A:  .word $FB00             ;SVEC u=4 dx=0 dy=12 z=0
L567C:  .word $FF70             ;SVEC u=4 dx=0 dy=-12 z=7
L567E:  .word $F272             ;SVEC u=2 dx=4 dy=4 z=7
L5680:  .word $F672             ;SVEC u=2 dx=4 dy=-4 z=7
L5682:  .word $EB36             ;JMPL L566C ($566C)

CHAR_X:
L5684:  .word $FB72             ;SVEC u=4 dx=8 dy=12 z=7
L5686:  .word $F806             ;SVEC u=4 dx=-8 dy=0 z=0
L5688:  .word $FF72             ;SVEC u=4 dx=8 dy=-12 z=7
L568A:  .word $EB72             ;JMPL L56E4 ($56E4)

CHAR_Y:
L568C:  .word $F002             ;SVEC u=2 dx=4 dy=0 z=0
L568E:  .word $FA70             ;SVEC u=4 dx=0 dy=8 z=7
L5690:  .word $F276             ;SVEC u=2 dx=-4 dy=4 z=7
L5692:  .word $F802             ;SVEC u=4 dx=8 dy=0 z=0
L5694:  .word $F676             ;SVEC u=2 dx=-4 dy=-4 z=7
L5696:  .word $FE02             ;SVEC u=4 dx=8 dy=-8 z=0
L5698:  .word $D000             ;RTSL

CHAR_Z:
L569A:  .word $FB00             ;SVEC u=4 dx=0 dy=12 z=0
L569C:  .word $F872             ;SVEC u=4 dx=8 dy=0 z=7
L569E:  .word $FF76             ;SVEC u=4 dx=-8 dy=-12 z=7
L56A0:  .word $EB58             ;JMPL L56B0 ($56B0)

CHAR_1:
L56A2:  .word $FB01             ;SVEC u=4 dx=4 dy=12 z=0
L56A4:  .word $EAEF             ;JMPL L55DE ($55DE)

CHAR_2:
L56A6:  .word $FB00             ;SVEC u=4 dx=0 dy=12 z=0
L56A8:  .word $F872             ;SVEC u=4 dx=8 dy=0 z=7
L56AA:  .word $F770             ;SVEC u=2 dx=0 dy=-6 z=7
L56AC:  .word $F876             ;SVEC u=4 dx=-8 dy=0 z=7
L56AE:  .word $F770             ;SVEC u=2 dx=0 dy=-6 z=7
L56B0:  .word $F872             ;SVEC u=4 dx=8 dy=0 z=7
L56B2:  .word $F002             ;SVEC u=2 dx=4 dy=0 z=0
L56B4:  .word $D000             ;RTSL

CHAR_3:
L56B6:  .word $FB00             ;SVEC u=4 dx=0 dy=12 z=0
L56B8:  .word $F872             ;SVEC u=4 dx=8 dy=0 z=7
L56BA:  .word $FF70             ;SVEC u=4 dx=0 dy=-12 z=7
L56BC:  .word $F876             ;SVEC u=4 dx=-8 dy=0 z=7
L56BE:  .word $F300             ;SVEC u=2 dx=0 dy=6 z=0
L56C0:  .word $F872             ;SVEC u=4 dx=8 dy=0 z=7
L56C2:  .word $F702             ;SVEC u=2 dx=4 dy=-6 z=0
L56C4:  .word $D000             ;RTSL

CHAR_4:
L56C6:  .word $FB00             ;SVEC u=4 dx=0 dy=12 z=0
L56C8:  .word $F770             ;SVEC u=2 dx=0 dy=-6 z=7
L56CA:  .word $F872             ;SVEC u=4 dx=8 dy=0 z=7
L56CC:  .word $F300             ;SVEC u=2 dx=0 dy=6 z=0
L56CE:  .word $EB71             ;JMPL L56E2 ($56E2)

CHAR_6:
L56D0:  .word $F300             ;SVEC u=2 dx=0 dy=6 z=0
L56D2:  .word $F872             ;SVEC u=4 dx=8 dy=0 z=7
L56D4:  .word $F770             ;SVEC u=2 dx=0 dy=-6 z=7
L56D6:  .word $F876             ;SVEC u=4 dx=-8 dy=0 z=7
L56D8:  .word $FB70             ;SVEC u=4 dx=0 dy=12 z=7
L56DA:  .word $FF03             ;SVEC u=4 dx=12 dy=-12 z=0
L56DC:  .word $D000             ;RTSL

CHAR_7:
L56DE:  .word $FB00             ;SVEC u=4 dx=0 dy=12 z=0
L56E0:  .word $F872             ;SVEC u=4 dx=8 dy=0 z=7
L56E2:  .word $FF70             ;SVEC u=4 dx=0 dy=-12 z=7
L56E4:  .word $F002             ;SVEC u=2 dx=4 dy=0 z=0
L56E6:  .word $D000             ;RTSL
L56E8:  .word $CB77             ;JSRL CHAR_9 ($56EE)

CHAR_8:
L56EA:  .word $FB70             ;SVEC u=4 dx=0 dy=12 z=7
L56EC:  .word $EB5C             ;JMPL L56B8 ($56B8)

CHAR_9:
L56EE:  .word $F802             ;SVEC u=4 dx=8 dy=0 z=0
L56F0:  .word $F300             ;SVEC u=2 dx=0 dy=6 z=0
L56F2:  .word $F876             ;SVEC u=4 dx=-8 dy=0 z=7
L56F4:  .word $F370             ;SVEC u=2 dx=0 dy=6 z=7
L56F6:  .byte $70               ;p
L56F7:  .byte $EB               ;.
L56F8:  .byte $0A               ;.
L56F9:  .byte $CB               ;.
L56FA:  .word $CB06             ;JSRL CHAR_O ($560C)
L56FC:  .word $CB51             ;JSRL CHAR_1 ($56A2)
L56FE:  .word $CB53             ;JSRL CHAR_2 ($56A6)
L5700:  .word $CB5B             ;JSRL CHAR_3 ($56B6)
L5702:  .word $CB63             ;JSRL CHAR_4 ($56C6)
L5704:  .word $CB2B             ;JSRL CHAR_S ($5656)
L5706:  .word $CB68             ;JSRL CHAR_6 ($56D0)
L5708:  .word $CB6F             ;JSRL CHAR_7 ($56DE)
L570A:  .word $CB75             ;JSRL CHAR_8 ($56EA)
L570C:  .word $CB77             ;JSRL CHAR_9 ($56EE)
L570E:  .word $CAB7             ;JSRL CHAR_A ($556E)
L5710:  .word $CABF             ;JSRL CHAR_B ($557E)
L5712:  .word $CACB             ;JSRL CHAR_C ($5596)
L5714:  .word $CACF             ;JSRL CHAR_D ($559E)
L5716:  .word $CAD6             ;JSRL CHAR_E ($55AC)
L5718:  .word $CAD8             ;JSRL CHAR_F ($55B0)
L571A:  .word $CADF             ;JSRL CHAR_G ($55BE)
L571C:  .word $CAE6             ;JSRL CHAR_H ($55CC)
L571E:  .word $CAEB             ;JSRL CHAR_I ($55D6)
L5720:  .word $CAF2             ;JSRL CHAR_J ($55E4)
L5722:  .word $CAF6             ;JSRL CHAR_K ($55EC)
L5724:  .word $CAFC             ;JSRL CHAR_L ($55F8)
L5726:  .word $CAFF             ;JSRL CHAR_M ($55FE)
L5728:  .word $CB03             ;JSRL CHAR_N ($5606)
L572A:  .word $CB06             ;JSRL CHAR_O ($560C)
L572C:  .word $CB0C             ;JSRL CHAR_P ($5618)
L572E:  .word $CB11             ;JSRL CHAR_Q ($5622)
L5730:  .word $CB19             ;JSRL CHAR_R ($5632)
L5732:  .word $CB2B             ;JSRL CHAR_S ($5656)
L5734:  .word $CB31             ;JSRL CHAR_T ($5662)
L5736:  .word $CB33             ;JSRL CHAR_U ($5666)
L5738:  .word $CB39             ;JSRL CHAR_V ($5672)
L573A:  .word $CB3D             ;JSRL CHAR_W ($567A)
L573C:  .word $CB42             ;JSRL CHAR_X ($5684)
L573E:  .word $CB46             ;JSRL CHAR_Y ($568C)
L5740:  .word $CB4D             ;JSRL CHAR_Z ($569A)
L5742:  .word $CB74             ;JSRL L56E8 ($56E8)
L5744:  .word $A080, $0000      ;LABS size=0 x=0 y=128
L5748:  .word $7000, $0000      ;WAIT t=7 z=0
L574C:  .word $9000, $73FF      ;VCTR s=9 dx=1023 dy=0 z=7 [x1]
L5750:  .word $92FF, $7000      ;VCTR s=9 dx=0 dy=767 z=7 [x1]
L5754:  .word $9000, $77FF      ;VCTR s=9 dx=-1023 dy=0 z=7 [x1]
L5758:  .word $96FF, $7000      ;VCTR s=9 dx=0 dy=-767 z=7 [x1]
L575C:  .word $92FF, $72FF      ;VCTR s=9 dx=767 dy=767 z=7 [x1]
L5760:  .word $8600, $7200      ;VCTR s=8 dx=256 dy=-256 z=7 [x2]
L5764:  .word $87FE, $77FE      ;VCTR s=8 dx=-511 dy=-511 z=7 [x2]
L5768:  .word $9200, $7600      ;VCTR s=9 dx=-512 dy=512 z=7 [x1]
L576C:  .word $81FE, $7200      ;VCTR s=8 dx=256 dy=255 z=7 [x2]
L5770:  .word $96FF, $72FF      ;VCTR s=9 dx=767 dy=-767 z=7 [x1]
L5774:  .word $A37F, $03FF      ;LABS size=0 x=1023 y=895
L5778:  .word $7000, $0000      ;WAIT t=7 z=0
L577C:  .word $96FF, $76FF      ;VCTR s=9 dx=-767 dy=-767 z=7 [x1]
L5780:  .word $81FE, $7600      ;VCTR s=8 dx=-256 dy=255 z=7 [x2]
L5784:  .word $9200, $7200      ;VCTR s=9 dx=512 dy=512 z=7 [x1]
L5788:  .word $87FE, $73FE      ;VCTR s=8 dx=511 dy=-511 z=7 [x2]
L578C:  .word $8600, $7600      ;VCTR s=8 dx=-256 dy=-256 z=7 [x2]
L5790:  .word $92FF, $76FF      ;VCTR s=9 dx=-767 dy=767 z=7 [x1]
L5794:  .word $A1FC, $01F4      ;LABS size=0 x=500 y=508
L5798:  .word $7000, $0000      ;WAIT t=7 z=0
L579C:  .word $F0DB             ;SVEC u=8 dx=24 dy=0 z=13
L579E:  .word $F900             ;SVEC u=4 dx=0 dy=4 z=0
L57A0:  .word $F0CF             ;SVEC u=8 dx=-24 dy=0 z=12
L57A2:  .word $F900             ;SVEC u=4 dx=0 dy=4 z=0
L57A4:  .word $F0BB             ;SVEC u=8 dx=24 dy=0 z=11
L57A6:  .word $F900             ;SVEC u=4 dx=0 dy=4 z=0
L57A8:  .word $F0AF             ;SVEC u=8 dx=-24 dy=0 z=10
L57AA:  .word $F900             ;SVEC u=4 dx=0 dy=4 z=0
L57AC:  .word $F09B             ;SVEC u=8 dx=24 dy=0 z=9
L57AE:  .word $F900             ;SVEC u=4 dx=0 dy=4 z=0
L57B0:  .word $F08F             ;SVEC u=8 dx=-24 dy=0 z=8
L57B2:  .word $F900             ;SVEC u=4 dx=0 dy=4 z=0
L57B4:  .word $F07B             ;SVEC u=8 dx=24 dy=0 z=7
L57B6:  .word $F900             ;SVEC u=4 dx=0 dy=4 z=0
L57B8:  .word $F06F             ;SVEC u=8 dx=-24 dy=0 z=6
L57BA:  .word $F900             ;SVEC u=4 dx=0 dy=4 z=0
L57BC:  .word $F05B             ;SVEC u=8 dx=24 dy=0 z=5
L57BE:  .word $F900             ;SVEC u=4 dx=0 dy=4 z=0
L57C0:  .word $F04F             ;SVEC u=8 dx=-24 dy=0 z=4
L57C2:  .word $F900             ;SVEC u=4 dx=0 dy=4 z=0
L57C4:  .word $F03B             ;SVEC u=8 dx=24 dy=0 z=3
L57C6:  .word $F900             ;SVEC u=4 dx=0 dy=4 z=0
L57C8:  .word $F02F             ;SVEC u=8 dx=-24 dy=0 z=2
L57CA:  .word $D000             ;RTSL
L57CC:  .word $A0E4, $115E      ;LABS size=1 x=350 y=228
L57D0:  .word $7000, $0000      ;WAIT t=7 z=0
L57D4:  .word $CABF             ;JSRL CHAR_B ($557E)
L57D6:  .word $CAB7             ;JSRL CHAR_A ($556E)
L57D8:  .word $CB03             ;JSRL CHAR_N ($5606)
L57DA:  .word $CAF6             ;JSRL CHAR_K ($55EC)
L57DC:  .word $CB0A             ;JSRL CHAR_SPACE ($5614)
L57DE:  .word $CAD6             ;JSRL CHAR_E ($55AC)
L57E0:  .word $CB19             ;JSRL CHAR_R ($5632)
L57E2:  .word $CB19             ;JSRL CHAR_R ($5632)
L57E4:  .word $CB06             ;JSRL CHAR_O ($560C)
L57E6:  .word $EB19             ;JMPL CHAR_R ($5632)
L57E8:  .word $A0C0, $119A      ;LABS size=1 x=410 y=192
L57EC:  .word $7000, $0000      ;WAIT t=7 z=0
L57F0:  .word $EBEF             ;JMPL L57DE ($57DE)
L57F2:  .word $CAD6             ;JSRL CHAR_E ($55AC)
L57F4:  .word $CB19             ;JSRL CHAR_R ($5632)
L57F6:  .word $CAB7             ;JSRL CHAR_A ($556E)
L57F8:  .word $CB2B             ;JSRL CHAR_S ($5656)
L57FA:  .word $CAEB             ;JSRL CHAR_I ($55D6)
L57FC:  .word $CB03             ;JSRL CHAR_N ($5606)
L57FE:  .word $EADF             ;JMPL CHAR_G ($55BE)
