#!/usr/bin/env python3
"""Export the ROM images the C port reads as data.

The game keeps a lot of its behaviour in tables - SINCOS, ACCEL, the
packed message text, the sound envelopes, every DVG shape - and the
ROM addresses of those tables are what the listing's comments and the
Atari source refer to.  Rather than transcribe each table into C by
hand (which is how transcription errors get in), the port carries the
ROM bytes themselves and reads a table at its ROM address:

    ad_rom(AD_SINCOS + i)

so a translated routine keeps the address the listing shows, and a
wrong index is a wrong address, findable in the listing, not a wrong
copy.  This is the same choice the Omega Race port made
(omega_pagerom.c, omega_vecrom.c).

Three regions are exported, from the traced 64K dump:

    $4800-$57FF   vector-board ROM (036800 @ $4800, 036799 @ $5000):
                  DVG shapes and the TRIROT code that shares the ROM
    $6000-$7FFF   program ROM
    the DVG state PROM (256 bytes), for a host's DVG interpreter

Writes ../c_src/astdelux_rom.c and ../c_src/astdelux_rom.h.

Usage:
    python mkrom.py [--set astdelux2]
"""

import argparse
import os

OUT_C = os.path.join("..", "c_src", "astdelux_rom.c")
OUT_H = os.path.join("..", "c_src", "astdelux_rom.h")

REGIONS = [
    ("ad_vecrom", 0x4800, 0x5800,
     "vector-board ROM, $4800-$57FF: 036800 @ $4800, 036799 @ $5000. "
     "DVG shape data interleaved with TRIROT.MAC's code"),
    ("ad_progrom", 0x6000, 0x8000,
     "program ROM, $6000-$7FFF: 036430 @ $6000, 036431 @ $6800, "
     "036432 @ $7000, 036433 @ $7800"),
]


def c_bytes(data, base, indent="    "):
    lines = []
    for off in range(0, len(data), 16):
        chunk = data[off:off + 16]
        lines.append(indent + ",".join("0x%02X" % b for b in chunk)
                     + ",  /* %04X */" % (base + off))
    return lines


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--set", dest="romset", default="astdelux2")
    args = ap.parse_args()

    dump = "%s_dump.bin" % args.romset
    image = open(dump, "rb").read()
    if len(image) != 0x10000:
        raise SystemExit("%s: expected a 64K image, got %d bytes"
                         % (dump, len(image)))
    prom = open("astdelux_dvgprom.bin", "rb").read()
    if len(prom) != 256:
        raise SystemExit("astdelux_dvgprom.bin: expected 256 bytes, got %d"
                         % len(prom))

    head = [
        "/* Asteroids Deluxe - the ROM images, as data.",
        " *",
        " * GENERATED by disasm/mkrom.py from %s.  Do not hand-edit." % dump,
        " *",
        " * The port reads its tables out of these at their ROM addresses",
        " * (ad_rom(addr) in astdelux_rom.h), so a translated routine keeps",
        " * the address the listing shows and nothing is transcribed by",
        " * hand.  Revision: %s." % args.romset,
        " */",
        "#include \"astdelux_rom.h\"",
        "",
    ]
    body = []
    for name, lo, hi, what in REGIONS:
        body.append("/* %s */" % what)
        body.append("const uint8_t %s[0x%X] = {" % (name, hi - lo))
        body += c_bytes(image[lo:hi], lo)
        body.append("};")
        body.append("")
    body.append("/* The DVG state PROM (034602-01), 256 bytes.  Not read by the")
    body.append(" * 6502; kept for a host that interprets the display list the")
    body.append(" * way the hardware does. */")
    body.append("const uint8_t ad_dvgprom[0x100] = {")
    body += c_bytes(prom, 0)
    body.append("};")

    with open(OUT_C, "w") as f:
        f.write("\n".join(head + body) + "\n")

    hdr = [
        "/* Asteroids Deluxe - the ROM images, as data.",
        " *",
        " * GENERATED by disasm/mkrom.py.  Do not hand-edit.",
        " *",
        " * ad_rom(addr) returns the byte the 6502 would read at a ROM",
        " * address, so a table is read at the address the listing shows:",
        " *",
        " *     ad_rom(0x4B51 + i)      SINCOS,i",
        " *",
        " * Addresses outside the two ROM regions return 0; the game never",
        " * reads a table from anywhere else. */",
        "#ifndef ASTDELUX_ROM_H",
        "#define ASTDELUX_ROM_H",
        "",
        "#include <stdint.h>",
        "",
    ]
    for name, lo, hi, _what in REGIONS:
        hdr.append("#define %s_BASE 0x%04X" % (name.upper(), lo))
        hdr.append("#define %s_SIZE 0x%04X" % (name.upper(), hi - lo))
        hdr.append("extern const uint8_t %s[0x%X];" % (name, hi - lo))
        hdr.append("")
    hdr += [
        "extern const uint8_t ad_dvgprom[0x100];",
        "",
        "static inline uint8_t ad_rom(uint16_t addr)",
        "{",
    ]
    for name, lo, hi, _what in REGIONS:
        hdr.append("    if (addr >= 0x%04Xu && addr < 0x%04Xu)" % (lo, hi))
        hdr.append("        return %s[addr - 0x%04Xu];" % (name, lo))
    hdr += [
        "    return 0;",
        "}",
        "",
        "/* A little-endian word, as `lda T,x / lda T+1,x` pairs read one. */",
        "static inline uint16_t ad_rom16(uint16_t addr)",
        "{",
        "    return (uint16_t)(ad_rom(addr) | (ad_rom((uint16_t)(addr + 1)) << 8));",
        "}",
        "",
        "#endif /* ASTDELUX_ROM_H */",
    ]
    with open(OUT_H, "w") as f:
        f.write("\n".join(hdr) + "\n")

    total = sum(hi - lo for _n, lo, hi, _w in REGIONS)
    print("wrote %s and %s: %d ROM bytes + 256 PROM bytes"
          % (OUT_C, OUT_H, total))


if __name__ == "__main__":
    main()
