#!/usr/bin/env python3
"""Generate the C port's memory model from the verified RAM layout.

`astdelux_defines.py` holds pages 0-3 exactly as `PG0123.MAC` declares
them, cross-checked against the linker map.  Hand-typing that into a C
header would throw the verification away, so it is generated instead -
and every field carries a `_Static_assert` tying its offset back to the
6502 address it must live at.  If the layout ever drifts, the port stops
compiling rather than going quietly wrong.

Two views of each page are emitted, because the ROM uses both:

  - named fields, for ordinary reads and writes
  - a raw byte array plus offset macros, for the parallel-array object
    model.  The index space is load-bearing - `COLIDE` walks `SHPPIX,x`
    for x = 0..7, running off the end of one "array" into the next by
    design - so the arrays cannot become C structs without breaking the
    idiom.  See GAMEPLAY_NOTES.md.

Writes ../c_src/astdelux_state.h

Usage:
    python mkstate.py
"""

import os
import sys

import astdelux_defines as defs

OUT = os.path.join("..", "c_src", "astdelux_state.h")

PAGES = [
    ("zp", 0x0000, 0x0100, "Page 0 - scratch and globals"),
    ("pg1", 0x0100, 0x0200,
     "Page 1 - ship-explosion state. The 6502 stack lives in this page "
     "too, growing down from $01FF; PWRON sets S to $FE and the main "
     "line later moves it to $FC. These cells sit below it."),
    ("player", 0x0200, 0x0300,
     "Pages 2 and 3 - per-player object state. BNKSEL ($3C04) bit 7 "
     "swaps them, so the same addresses always reach whoever is up."),
]


def cname(name):
    """C identifier for a RAM symbol.

    The original assembler allowed `$` inside identifiers; C does not, so
    `$INTCT` becomes `INTCT` and `$$CRDT` becomes `CRDT`.  The original
    spelling is kept in the comment.
    """
    out = name.lstrip("$").replace(".", "_")
    return out


def main():
    ram = defs.RAM
    lines = []
    w = lines.append

    w("/* Asteroids Deluxe - the 6502 memory model, as C.")
    w(" *")
    w(" * GENERATED by disasm/mkstate.py from the RAM layout in")
    w(" * PG0123.MAC.  Do not hand-edit: regenerate.")
    w(" *")
    w(" * Every field is followed by a _Static_assert pinning its offset")
    w(" * to the address the ROM uses.  That is the point of generating")
    w(" * this - the port inherits the verification instead of a copy.")
    w(" *")
    w(" * Layout is rev 2 (MAME astdelux2), the build Atari's source")
    w(" * archive documents.  See disasm/README.md#revisions.")
    w(" */")
    w("#ifndef ASTDELUX_STATE_H")
    w("#define ASTDELUX_STATE_H")
    w("")
    w("#include <stdint.h>")
    w("#include <stddef.h>")
    w("")

    asserts = []
    for tag, lo, hi, blurb in PAGES:
        cells = sorted((a, v) for a, v in ram.items() if lo <= a < hi)
        w("/* %s" % blurb)
        w(" * $%04X-$%04X, %d cells." % (lo, hi - 1, len(cells)))
        w(" */")
        w("typedef union {")
        w("    uint8_t raw[0x%X];" % (hi - lo))
        w("    struct {")
        dot = lo
        pad = 0
        for a, (name, size, comment) in cells:
            if a > dot:
                w("        uint8_t _pad%d[0x%X];   /* $%04X unused */"
                  % (pad, a - dot, dot))
                pad += 1
                dot = a
            elif a < dot:
                sys.exit("overlap at $%04X in %s" % (a, tag))
            n = cname(name)
            note = comment.replace("*/", "* /") if comment else ""
            orig = "" if n == name else "  orig. %s;" % name
            decl = ("uint8_t %s;" % n if size == 1
                    else "uint8_t %s[%d];" % (n, size))
            w("        %-26s /* $%04X%s%s */"
              % (decl, a, ("  " + note) if note else "", orig))
            asserts.append((tag, n, a - lo, a))
            dot += size
        if dot < hi:
            w("        uint8_t _pad%d[0x%X];   /* $%04X-$%04X unused */"
              % (pad, hi - dot, dot, hi - 1))
        w("    } f;")
        w("} ad_%s_t;" % tag)
        w("")

    w("/* The layout is the contract: these are what make it safe to")
    w(" * translate the ROM's pointer arithmetic literally. */")
    for tag, n, off, addr in asserts:
        w('_Static_assert(offsetof(ad_%s_t, f.%s) == 0x%02X,' % (tag, n, off))
        w('               "%s must sit at $%04X");' % (n, addr))
    w("")

    w("/* Offsets for the parallel-array object model.  The ROM indexes")
    w(" * across these deliberately - 0..24 are rocks, 25 the ship, 26")
    w(" * the saucer, 27-28 its torpedoes, 29-32 the ship's - so they are")
    w(" * reached through the raw view, not as separate C arrays. */")
    for name in ("OBJ", "XINC", "YINC", "OBJXH", "OBJYH", "OBJXL", "OBJYL"):
        hit = [a for a, (n, _s, _c) in ram.items() if n == name]
        if hit:
            w("#define AD_%-8s 0x%02X   /* $%04X */"
              % (name, hit[0] - 0x200, hit[0]))
    w("")
    w("#define AD_NOBJ      25   /* rocks; DSTDEC.MAC NOBJ */")
    w("#define AD_NSPCLS     7   /* special rocks; DSTDEC.MAC NSPCLS */")
    w("#define AD_SLOTS     33   /* rocks + ship + saucer + 6 torpedoes */")
    w("#define AD_SHIP      25")
    w("#define AD_SAUCER    26")
    w("#define AD_SAUTP     27   /* .. 28 */")
    w("#define AD_SHPTP     29   /* .. 32 */")
    w("")
    w("#endif /* ASTDELUX_STATE_H */")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w").write("\n".join(lines) + "\n")
    print("wrote %s" % OUT)
    for tag, lo, hi, _b in PAGES:
        n = sum(1 for a in ram if lo <= a < hi)
        print("  ad_%-7s %3d fields, 0x%X bytes" % (tag + "_t", n, hi - lo))
    print("  %d static assertions" % len(asserts))


if __name__ == "__main__":
    main()
