#!/usr/bin/env python3
"""stage.py - stage the game core and the cabinet samples into the Arduino sketch.

Arduino compiles the sketch folder and everything under its src/ tree, and
nothing outside it, so the platform-agnostic game core is copied into
astdelux_teensy/src/core/ (gitignored) rather than referenced in place.  The
file list is the second `cl` line of c_src/build_win_gl.bat minus the Windows
backend (platform/windows/plat_win.c): app_win.c is the platform-agnostic
application loop despite its name, dvg.c the DVG state machine.

The five samples in c_src/samples/astdelux.zip (8-bit unsigned mono 44100 Hz)
become const arrays in src/samples_data.c so the board needs no SD card.

    python stage.py           stage (idempotent; re-copies changed files)
    python stage.py --clean   remove astdelux_teensy/src/
"""
import io
import os
import shutil
import sys
import wave
import zipfile

HERE   = os.path.dirname(os.path.abspath(__file__))
C_SRC  = os.path.normpath(os.path.join(HERE, "..", ".."))
SKETCH = os.path.join(HERE, "astdelux_teensy")
SRC    = os.path.join(SKETCH, "src")
CORE   = os.path.join(SRC, "core")

CORE_C = [
    "app_win.c", "dvg.c", "mainline.c", "vgutil.c", "message.c", "mathrom.c",
    "frame.c", "objects.c", "draw.c", "player.c", "enemy.c", "score.c",
    "sound.c", "nmi.c", "earom.c", "stest.c", "c012294.c", "er2055.c",
    "astdelux_rom.c",
]
CORE_H = ["astdelux.h", "astdelux_state.h", "astdelux_rom.h", "c012294.h", "er2055.h"]
PLATFORM_H = os.path.join("platform", "ad_platform.h")

# ad_platform.h's AD_SMP_* order: explode1..4 then thrust
SAMPLES = ["explode1.wav", "explode2.wav", "explode3.wav", "explode4.wav", "thrust.wav"]
SAMPLE_ZIP = os.path.join(C_SRC, "samples", "astdelux.zip")


def copy_if_changed(src, dst):
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    if os.path.exists(dst):
        with open(src, "rb") as a, open(dst, "rb") as b:
            if a.read() == b.read():
                return False
    shutil.copyfile(src, dst)
    return True


def stage_core():
    n = 0
    for name in CORE_C + CORE_H:
        src = os.path.join(C_SRC, name)
        if not os.path.exists(src):
            sys.exit(f"stage.py: missing core file {src}")
        n += copy_if_changed(src, os.path.join(CORE, name))
    n += copy_if_changed(os.path.join(C_SRC, PLATFORM_H), os.path.join(CORE, PLATFORM_H))
    print(f"core: {len(CORE_C) + len(CORE_H) + 1} files staged, {n} updated")


def read_sample(zf, name):
    with zf.open(name) as f:
        w = wave.open(io.BytesIO(f.read()))
    ch, width, rate = w.getnchannels(), w.getsampwidth(), w.getframerate()
    if (ch, width, rate) != (1, 1, 44100):
        sys.exit(f"stage.py: {name} is {ch} ch {8*width} bit {rate} Hz; "
                 "expected 8-bit unsigned mono 44100 Hz")
    return w.readframes(w.getnframes())


def stage_samples():
    if not os.path.exists(SAMPLE_ZIP):
        sys.exit(f"stage.py: missing {SAMPLE_ZIP}")
    with zipfile.ZipFile(SAMPLE_ZIP) as zf:
        data = [read_sample(zf, n) for n in SAMPLES]

    c = io.StringIO()
    c.write("/* samples_data.c - GENERATED by platform/teensy/stage.py from\n"
            " * samples/astdelux.zip.  Do not hand-edit.  The two discrete circuits,\n"
            " * explosion and thrust, as recorded from a real cabinet: 8-bit unsigned\n"
            " * mono 44100 Hz, indexed by ad_platform.h's AD_SMP_* numbers. */\n"
            "#include \"samples_data.h\"\n\n")
    for name, bytes_ in zip(SAMPLES, data):
        ident = "ad_smp_" + name[:-4]
        c.write(f"static const uint8_t {ident}[{len(bytes_)}] AD_FLASH = {{\n")
        for i in range(0, len(bytes_), 16):
            c.write("    " + ",".join(f"0x{b:02X}" for b in bytes_[i:i+16]) + ",\n")
        c.write("};\n\n")
    c.write("const uint8_t *const ad_smp_data[AD_SMP_COUNT] = {\n")
    for name in SAMPLES:
        c.write(f"    ad_smp_{name[:-4]},\n")
    c.write("};\n\nconst uint32_t ad_smp_len[AD_SMP_COUNT] = {\n")
    for bytes_ in data:
        c.write(f"    {len(bytes_)}u,\n")
    c.write("};\n")

    h = ("/* samples_data.h - GENERATED by platform/teensy/stage.py.  Do not hand-edit. */\n"
         "#ifndef SAMPLES_DATA_H\n#define SAMPLES_DATA_H\n\n#include <stdint.h>\n\n"
         "/* Keep the arrays in flash on the Teensy 4 (cores/teensy4/avr/pgmspace.h's\n"
         " * PROGMEM section); a plain const array anywhere else. */\n"
         "#if defined(__IMXRT1062__)\n"
         "#define AD_FLASH __attribute__((section(\".progmem\")))\n"
         "#else\n#define AD_FLASH\n#endif\n\n"
         f"#define AD_SMP_COUNT {len(SAMPLES)}\n"
         "extern const uint8_t *const ad_smp_data[AD_SMP_COUNT];\n"
         "extern const uint32_t ad_smp_len[AD_SMP_COUNT];\n\n#endif\n")

    os.makedirs(SRC, exist_ok=True)
    for fname, text in (("samples_data.c", c.getvalue()), ("samples_data.h", h)):
        path = os.path.join(SRC, fname)
        if not (os.path.exists(path) and open(path, encoding="utf-8").read() == text):
            with open(path, "w", encoding="utf-8", newline="\n") as f:
                f.write(text)
    total = sum(len(d) for d in data)
    print(f"samples: {len(SAMPLES)} files, {total} bytes -> src/samples_data.c")


def main():
    if "--clean" in sys.argv[1:]:
        shutil.rmtree(SRC, ignore_errors=True)
        print("removed", SRC)
        return
    stage_core()
    stage_samples()


if __name__ == "__main__":
    main()
