/* Asteroids Deluxe - the 6502 memory model, as C.
 *
 * GENERATED by disasm/mkstate.py from the RAM layout in
 * PG0123.MAC.  Do not hand-edit: regenerate.
 *
 * Every field is followed by a _Static_assert pinning its offset
 * to the address the ROM uses.  That is the point of generating
 * this - the port inherits the verification instead of a copy.
 *
 * Layout is rev 2 (MAME astdelux2), the build Atari's source
 * archive documents.  See disasm/README.md#revisions.
 */
#ifndef ASTDELUX_STATE_H
#define ASTDELUX_STATE_H

#include <stdint.h>
#include <stddef.h>

/* Page 0 - scratch and globals
 * $0000-$00FF, 90 cells.
 */
typedef union {
    uint8_t raw[0x100];
    struct {
        uint8_t _pad0[0x1];   /* $0000 unused */
        uint8_t VGSIZE;            /* $0001  SCALING SIZE (0,10,20,...,F0) */
        uint8_t VGBRIT;            /* $0002  VECTOR BRIGHTNESS (0=OFF, F0=MAX, 10INC) */
        uint8_t VGLIST[2];         /* $0003  VECTOR LIST POINTER */
        uint8_t XCOMP[4];          /* $0005  X COMPONENT FOR VECTORS */
        uint8_t TEMP1[3];          /* $0009  SCRATCH-3 BYTES USED BY SELF-TEST */
        uint8_t TEMP2[2];          /* $000C */
        uint8_t TEMP3[2];          /* $000E  8 CKSUMS IN SELF TEST */
        uint8_t R0;                /* $0010 */
        uint8_t R1;                /* $0011 */
        uint8_t R2;                /* $0012 */
        uint8_t R3;                /* $0013 */
        uint8_t R4;                /* $0014 */
        uint8_t R5;                /* $0015 */
        uint8_t R6;                /* $0016 */
        uint8_t R7;                /* $0017 */
        uint8_t R8;                /* $0018 */
        uint8_t R9;                /* $0019 */
        uint8_t XT;                /* $001A  STORAGE FOR X REGISTER */
        uint8_t TEMP4[3];          /* $001B */
        uint8_t PLAYR;             /* $001E  PLAYER NUMBER (0 OR 1) */
        uint8_t PLAYR2;            /* $001F  PLAYER NUMBER *2 (0 OR 2) */
        uint8_t PLAYR3;            /* $0020  PLAYER NUMBER *3 (0 OR 3) */
        uint8_t LPLAYR;            /* $0021  THE VALUE OF NPLAYR FOR LAST GAME */
        uint8_t NPLAYR;            /* $0022  NUMBER OF PLAYERS (1 OR 2)(0=END OF GAME)(-1=UPDATE HIGH SCORES) */
        uint8_t HSCORE[30];        /* $0023  HIGH SCORES (LSB,MSB) */
        uint8_t UPDINT;            /* $0041  0,1, OR 2 TO INDICATE WHICH INITIAL IS BEING SELECTED */
        uint8_t UPDFLG[2];         /* $0042  POSITIVE MEANS THIS PLAYER HAS SET NEW HIGH SCORE */
        uint8_t INITL[30];         /* $0044  INITIALS FOR HIGH SCORE (FIRST,SECOND,THRID) */
        uint8_t SCORE[6];          /* $0062  PLAYER 1 AND 2 SCORES (LSB1,MSB1,LSB2,MSB2) */
        uint8_t PLATEU[6];         /* $0068  BONUS LEVEL ACCUMULATORS */
        uint8_t NHITS;             /* $006E  STARTING NUMBER OF HITS PER PLAYER */
        uint8_t HITS[2];           /* $006F  LIFE COUNTERS (PLAYER 1 / PLAYER 2) */
        uint8_t CHIST[2];          /* $0071  COLLISION HISTORY REGISTERS */
        uint8_t SHDON;             /* $0073 */
        uint8_t GDELAY;            /* $0074  DELAY BEFORE STARTING GAME */
        uint8_t SYNC;              /* $0075  FRAME COUNTER SYNC */
        uint8_t FRAME[2];          /* $0076  FRAME COUNTER */
        uint8_t INTCT;             /* $0078  INTERRUPT COUNTER  orig. $INTCT; */
        uint8_t ANGLE[2];          /* $0079  ANGLE OF ROTATIONS */
        uint8_t LASTSW;            /* $007B  LAST SWITCH READING */
        uint8_t XINCL;             /* $007C  SHIPS LSB FOR X INCREMENT */
        uint8_t YINCL;             /* $007D  SHIPS LSB FOR Y INCREMENT */
        uint8_t SND3;              /* $007E  SOUND FLAGS */
        uint8_t LEXPSND;           /* $007F  LAST VALUE FOR EXPLOSION SOUND (SEE EXPSND) */
        uint8_t LSND1;             /* $0080  LAST VALUE FOR SHIP FIRE SOUND (SEE SHPFIR) */
        uint8_t LSND2;             /* $0081  LAST VALUE FOR SAUCER FIRE SOUND (SEE SCRFIR) */
        uint8_t LTHUMP;            /* $0082  LAST VALUE FOR THUMP SOUND (SEE THUMP) */
        uint8_t THUMP1;            /* $0083  LENGTH OF THUMP SOUNDS */
        uint8_t THUMP2;            /* $0084  LENGTH BETWEEN THUMP SOUNDS */
        uint8_t LOUT1;             /* $0085  LAST VALUE OF OUTPUT LATCH */
        uint8_t ASTERS[4];         /* $0086  ASTERIOD ORIENTATIONS */
        uint8_t PROT[4];           /* $008A */
        uint8_t TWOCM;             /* $008E */
        uint8_t SBTL;              /* $008F  SHIP BACK TO LIFE INTENSITY FLAG */
        uint8_t CPMTST;            /* $0090  COPYRIGHT MESSAGE TEST FLAG */
        uint8_t CRMERR;            /* $0091  COPYRIGHT MESSAGE ERROR */
        uint8_t HOLE;              /* $0092  FLAG FOR COPYRIGHT TEST */
        uint8_t CRDT;              /* $0093  COIN ROUTINE DEFINITION (SEE COIN65.MAC)  orig. $$CRDT; */
        uint8_t CMODE;             /* $0094  orig. $CMODE; */
        uint8_t LMTIM;             /* $0095  orig. $LMTIM; */
        uint8_t CNCT;              /* $0096  orig. $CNCT; */
        uint8_t CCTIM[3];          /* $0097  orig. $CCTIM; */
        uint8_t PSTSL[3];          /* $009A  orig. $PSTSL; */
        uint8_t CNSTT[3];          /* $009D  orig. $CNSTT; */
        uint8_t BCCNT;             /* $00A0  orig. $BCCNT; */
        uint8_t BC;                /* $00A1  orig. $BC; */
        uint8_t POINT[8];          /* $00A2  POINTER OFFSET INTO DATA TABLES */
        uint8_t CURRENT[8];        /* $00AA  OUTPUT VALUE */
        uint8_t FRAMES[8];         /* $00B2  FRAMES UNTIL NEXT CHANGE */
        uint8_t COUNT[8];          /* $00BA  COUNT OF TOTAL CHANGES */
        uint8_t MCOUNT[8];         /* $00C2  BACKGROUND NOISE */
        uint8_t MPNTR[8];          /* $00CA */
        uint8_t EAX;               /* $00D2  EA ACCESS INDEX */
        uint8_t EABC;              /* $00D3  BYTE COUNTER */
        uint8_t EAFLG;             /* $00D4  EA ACTIVITY FLAG */
        uint8_t EAHSX;             /* $00D5  HI-SCORE ENTRY TO WRITE */
        uint8_t EACS;              /* $00D6  CHECKSUM */
        uint8_t EABAD;             /* $00D7  BAD ENTRY FLAG. */
        uint8_t TRILE[2];          /* $00D8  DIAMOND LAUNCH ENABLE */
        uint8_t BINSCR;            /* $00DA  BINARY SCORE */
        uint8_t PERR[5];           /* $00DB  POKEY ERROR(S) */
        uint8_t CKERR;             /* $00E0  SOMEBODY STOLE THIS PGM IF.NE */
        uint8_t RVELP;             /* $00E1  MINIMUM ROCK VELOCITY+ */
        uint8_t RVELM;             /* $00E2  MINIMUM ROCK VELOCITY- */
        uint8_t HSSND;             /* $00E3  HI-SCORE TABLE REACHED FLAG */
        uint8_t SBTLT;             /* $00E4  SHIP BACK TO LIFE TIMER */
        uint8_t EXPDX[8];          /* $00E5  X VEL OF EXPLOSION PIECE */
        uint8_t EXPDY[8];          /* $00ED  Y VEL OF EXPLOSION PIECE */
        uint8_t EXPANG[8];         /* $00F5  ORIENTATION OF PIECE */
        uint8_t BONSCR[3];         /* $00FD  BONUS SCORE @ */
    } f;
} ad_zp_t;

/* Page 1 - ship-explosion state. The 6502 stack lives in this page too, growing down from $01FF; PWRON sets S to $FE and the main line later moves it to $FC. These cells sit below it.
 * $0100-$01FF, 5 cells.
 */
typedef union {
    uint8_t raw[0x100];
    struct {
        uint8_t SXPXL[8];          /* $0100  SHIP EXPLOSION CONTROLS. XL,YL,XH,YH */
        uint8_t SXPYL[8];          /* $0108 */
        uint8_t SXPXH[8];          /* $0110 */
        uint8_t SXPYH[8];          /* $0118 */
        uint8_t EXPTMB[8];         /* $0120  ORIENTATION VELOCITY */
        uint8_t _pad0[0xD8];   /* $0128-$01FF unused */
    } f;
} ad_pg1_t;

/* Pages 2 and 3 - per-player object state. BNKSEL ($3C04) bit 7 swaps them, so the same addresses always reach whoever is up.
 * $0200-$02FF, 48 cells.
 */
typedef union {
    uint8_t raw[0x100];
    struct {
        uint8_t OBJ[25];           /* $0200  ROCK PIX SEL 0=NOT ACTIVE ELSE PIC # */
        uint8_t SHPPIX;            /* $0219  SHIP PIX SEL, BIT 7=1 IF EXPLODING */
        uint8_t SAUPIX;            /* $021A  SAUCER */
        uint8_t SAUTP[2];          /* $021B  SAUCER TORPEDOES(=TIME OF FLIGHT) */
        uint8_t SHPTP[4];          /* $021D  SHIP TORPEDOES(=TIME OF FLIGHT) */
        uint8_t XINC[25];          /* $0221  ROCKS */
        uint8_t SHPXI;             /* $023A  SHIP */
        uint8_t SAUXI;             /* $023B  SAUCER */
        uint8_t SAUTXI[2];         /* $023C  SAUCER TORPEDOES */
        uint8_t SHPTXI[4];         /* $023E  SHIP TORPEDOES */
        uint8_t YINC[25];          /* $0242  ROCKS */
        uint8_t SHPYI;             /* $025B  SHIP */
        uint8_t SAUYI;             /* $025C  SAUCER */
        uint8_t SAUTYI[2];         /* $025D  SAUCER TORPEDOES */
        uint8_t SHPTYI[4];         /* $025F  SHIP TORPEDOES */
        uint8_t OBJXH[25];         /* $0263  ROCKS */
        uint8_t SHPXH;             /* $027C  SHIP */
        uint8_t SAUXH;             /* $027D  SAUCER */
        uint8_t SAUTXH[2];         /* $027E  SAUCER TORPEDOES */
        uint8_t SHPTXH[4];         /* $0280  SHIP TORPEDOES */
        uint8_t OBJYH[25];         /* $0284 */
        uint8_t SHPYH;             /* $029D */
        uint8_t SAUYH;             /* $029E */
        uint8_t SAUTYH[2];         /* $029F */
        uint8_t SHPTYH[4];         /* $02A1 */
        uint8_t OBJXL[25];         /* $02A5  ROCKS */
        uint8_t SHPXL;             /* $02BE  SHIP */
        uint8_t SAUXL;             /* $02BF  SAUCER */
        uint8_t SAUTXL[2];         /* $02C0  SAUCER TORPEDOES */
        uint8_t SHPTXL[4];         /* $02C2  SHIP TORPEDOES */
        uint8_t OBJYL[25];         /* $02C6 */
        uint8_t SHPYL;             /* $02DF */
        uint8_t SAUYL;             /* $02E0 */
        uint8_t SAUTYL[2];         /* $02E1 */
        uint8_t SHPTYL[4];         /* $02E3 */
        uint8_t NROCKS;            /* $02E7  CURRENT NUMBER OF ROCKS */
        uint8_t EDELAY;            /* $02E8  DELAY BEFORE ENEMY ENTRY OR FIRING */
        uint8_t SEDLAY;            /* $02E9  STARTING ENEMY DELAY */
        uint8_t RTIMER;            /* $02EA  ROCK TIME - IF 0 SEND IN SAUCER ANYWAY */
        uint8_t SDELAY;            /* $02EB  DELAY COUNT BEFORE ADDING SHIP (80=SHIP JUST DESTROYED) */
        uint8_t RDELAY;            /* $02EC  DELAY COUNT BEFORE ADDING ROCKS */
        uint8_t THUMP3;            /* $02ED  STARTING VALUE FOR THUMP2 */
        uint8_t DIFCTY;            /* $02EE  DIFFICULTY VALUE FOR STARTING SAUCERS */
        uint8_t SHLDS;             /* $02EF  SHIELDS VALUE */
        uint8_t SROCKS;            /* $02F0 */
        uint8_t SRANG[7];          /* $02F1  ORIENTATIN */
        uint8_t SRTIME[7];         /* $02F8  CONTROL */
        uint8_t SPROCK;            /* $02FF  NUMBER OF SPECIAL ROCKS */
    } f;
} ad_player_t;

/* The layout is the contract: these are what make it safe to
 * translate the ROM's pointer arithmetic literally. */
_Static_assert(offsetof(ad_zp_t, f.VGSIZE) == 0x01,
               "VGSIZE must sit at $0001");
_Static_assert(offsetof(ad_zp_t, f.VGBRIT) == 0x02,
               "VGBRIT must sit at $0002");
_Static_assert(offsetof(ad_zp_t, f.VGLIST) == 0x03,
               "VGLIST must sit at $0003");
_Static_assert(offsetof(ad_zp_t, f.XCOMP) == 0x05,
               "XCOMP must sit at $0005");
_Static_assert(offsetof(ad_zp_t, f.TEMP1) == 0x09,
               "TEMP1 must sit at $0009");
_Static_assert(offsetof(ad_zp_t, f.TEMP2) == 0x0C,
               "TEMP2 must sit at $000C");
_Static_assert(offsetof(ad_zp_t, f.TEMP3) == 0x0E,
               "TEMP3 must sit at $000E");
_Static_assert(offsetof(ad_zp_t, f.R0) == 0x10,
               "R0 must sit at $0010");
_Static_assert(offsetof(ad_zp_t, f.R1) == 0x11,
               "R1 must sit at $0011");
_Static_assert(offsetof(ad_zp_t, f.R2) == 0x12,
               "R2 must sit at $0012");
_Static_assert(offsetof(ad_zp_t, f.R3) == 0x13,
               "R3 must sit at $0013");
_Static_assert(offsetof(ad_zp_t, f.R4) == 0x14,
               "R4 must sit at $0014");
_Static_assert(offsetof(ad_zp_t, f.R5) == 0x15,
               "R5 must sit at $0015");
_Static_assert(offsetof(ad_zp_t, f.R6) == 0x16,
               "R6 must sit at $0016");
_Static_assert(offsetof(ad_zp_t, f.R7) == 0x17,
               "R7 must sit at $0017");
_Static_assert(offsetof(ad_zp_t, f.R8) == 0x18,
               "R8 must sit at $0018");
_Static_assert(offsetof(ad_zp_t, f.R9) == 0x19,
               "R9 must sit at $0019");
_Static_assert(offsetof(ad_zp_t, f.XT) == 0x1A,
               "XT must sit at $001A");
_Static_assert(offsetof(ad_zp_t, f.TEMP4) == 0x1B,
               "TEMP4 must sit at $001B");
_Static_assert(offsetof(ad_zp_t, f.PLAYR) == 0x1E,
               "PLAYR must sit at $001E");
_Static_assert(offsetof(ad_zp_t, f.PLAYR2) == 0x1F,
               "PLAYR2 must sit at $001F");
_Static_assert(offsetof(ad_zp_t, f.PLAYR3) == 0x20,
               "PLAYR3 must sit at $0020");
_Static_assert(offsetof(ad_zp_t, f.LPLAYR) == 0x21,
               "LPLAYR must sit at $0021");
_Static_assert(offsetof(ad_zp_t, f.NPLAYR) == 0x22,
               "NPLAYR must sit at $0022");
_Static_assert(offsetof(ad_zp_t, f.HSCORE) == 0x23,
               "HSCORE must sit at $0023");
_Static_assert(offsetof(ad_zp_t, f.UPDINT) == 0x41,
               "UPDINT must sit at $0041");
_Static_assert(offsetof(ad_zp_t, f.UPDFLG) == 0x42,
               "UPDFLG must sit at $0042");
_Static_assert(offsetof(ad_zp_t, f.INITL) == 0x44,
               "INITL must sit at $0044");
_Static_assert(offsetof(ad_zp_t, f.SCORE) == 0x62,
               "SCORE must sit at $0062");
_Static_assert(offsetof(ad_zp_t, f.PLATEU) == 0x68,
               "PLATEU must sit at $0068");
_Static_assert(offsetof(ad_zp_t, f.NHITS) == 0x6E,
               "NHITS must sit at $006E");
_Static_assert(offsetof(ad_zp_t, f.HITS) == 0x6F,
               "HITS must sit at $006F");
_Static_assert(offsetof(ad_zp_t, f.CHIST) == 0x71,
               "CHIST must sit at $0071");
_Static_assert(offsetof(ad_zp_t, f.SHDON) == 0x73,
               "SHDON must sit at $0073");
_Static_assert(offsetof(ad_zp_t, f.GDELAY) == 0x74,
               "GDELAY must sit at $0074");
_Static_assert(offsetof(ad_zp_t, f.SYNC) == 0x75,
               "SYNC must sit at $0075");
_Static_assert(offsetof(ad_zp_t, f.FRAME) == 0x76,
               "FRAME must sit at $0076");
_Static_assert(offsetof(ad_zp_t, f.INTCT) == 0x78,
               "INTCT must sit at $0078");
_Static_assert(offsetof(ad_zp_t, f.ANGLE) == 0x79,
               "ANGLE must sit at $0079");
_Static_assert(offsetof(ad_zp_t, f.LASTSW) == 0x7B,
               "LASTSW must sit at $007B");
_Static_assert(offsetof(ad_zp_t, f.XINCL) == 0x7C,
               "XINCL must sit at $007C");
_Static_assert(offsetof(ad_zp_t, f.YINCL) == 0x7D,
               "YINCL must sit at $007D");
_Static_assert(offsetof(ad_zp_t, f.SND3) == 0x7E,
               "SND3 must sit at $007E");
_Static_assert(offsetof(ad_zp_t, f.LEXPSND) == 0x7F,
               "LEXPSND must sit at $007F");
_Static_assert(offsetof(ad_zp_t, f.LSND1) == 0x80,
               "LSND1 must sit at $0080");
_Static_assert(offsetof(ad_zp_t, f.LSND2) == 0x81,
               "LSND2 must sit at $0081");
_Static_assert(offsetof(ad_zp_t, f.LTHUMP) == 0x82,
               "LTHUMP must sit at $0082");
_Static_assert(offsetof(ad_zp_t, f.THUMP1) == 0x83,
               "THUMP1 must sit at $0083");
_Static_assert(offsetof(ad_zp_t, f.THUMP2) == 0x84,
               "THUMP2 must sit at $0084");
_Static_assert(offsetof(ad_zp_t, f.LOUT1) == 0x85,
               "LOUT1 must sit at $0085");
_Static_assert(offsetof(ad_zp_t, f.ASTERS) == 0x86,
               "ASTERS must sit at $0086");
_Static_assert(offsetof(ad_zp_t, f.PROT) == 0x8A,
               "PROT must sit at $008A");
_Static_assert(offsetof(ad_zp_t, f.TWOCM) == 0x8E,
               "TWOCM must sit at $008E");
_Static_assert(offsetof(ad_zp_t, f.SBTL) == 0x8F,
               "SBTL must sit at $008F");
_Static_assert(offsetof(ad_zp_t, f.CPMTST) == 0x90,
               "CPMTST must sit at $0090");
_Static_assert(offsetof(ad_zp_t, f.CRMERR) == 0x91,
               "CRMERR must sit at $0091");
_Static_assert(offsetof(ad_zp_t, f.HOLE) == 0x92,
               "HOLE must sit at $0092");
_Static_assert(offsetof(ad_zp_t, f.CRDT) == 0x93,
               "CRDT must sit at $0093");
_Static_assert(offsetof(ad_zp_t, f.CMODE) == 0x94,
               "CMODE must sit at $0094");
_Static_assert(offsetof(ad_zp_t, f.LMTIM) == 0x95,
               "LMTIM must sit at $0095");
_Static_assert(offsetof(ad_zp_t, f.CNCT) == 0x96,
               "CNCT must sit at $0096");
_Static_assert(offsetof(ad_zp_t, f.CCTIM) == 0x97,
               "CCTIM must sit at $0097");
_Static_assert(offsetof(ad_zp_t, f.PSTSL) == 0x9A,
               "PSTSL must sit at $009A");
_Static_assert(offsetof(ad_zp_t, f.CNSTT) == 0x9D,
               "CNSTT must sit at $009D");
_Static_assert(offsetof(ad_zp_t, f.BCCNT) == 0xA0,
               "BCCNT must sit at $00A0");
_Static_assert(offsetof(ad_zp_t, f.BC) == 0xA1,
               "BC must sit at $00A1");
_Static_assert(offsetof(ad_zp_t, f.POINT) == 0xA2,
               "POINT must sit at $00A2");
_Static_assert(offsetof(ad_zp_t, f.CURRENT) == 0xAA,
               "CURRENT must sit at $00AA");
_Static_assert(offsetof(ad_zp_t, f.FRAMES) == 0xB2,
               "FRAMES must sit at $00B2");
_Static_assert(offsetof(ad_zp_t, f.COUNT) == 0xBA,
               "COUNT must sit at $00BA");
_Static_assert(offsetof(ad_zp_t, f.MCOUNT) == 0xC2,
               "MCOUNT must sit at $00C2");
_Static_assert(offsetof(ad_zp_t, f.MPNTR) == 0xCA,
               "MPNTR must sit at $00CA");
_Static_assert(offsetof(ad_zp_t, f.EAX) == 0xD2,
               "EAX must sit at $00D2");
_Static_assert(offsetof(ad_zp_t, f.EABC) == 0xD3,
               "EABC must sit at $00D3");
_Static_assert(offsetof(ad_zp_t, f.EAFLG) == 0xD4,
               "EAFLG must sit at $00D4");
_Static_assert(offsetof(ad_zp_t, f.EAHSX) == 0xD5,
               "EAHSX must sit at $00D5");
_Static_assert(offsetof(ad_zp_t, f.EACS) == 0xD6,
               "EACS must sit at $00D6");
_Static_assert(offsetof(ad_zp_t, f.EABAD) == 0xD7,
               "EABAD must sit at $00D7");
_Static_assert(offsetof(ad_zp_t, f.TRILE) == 0xD8,
               "TRILE must sit at $00D8");
_Static_assert(offsetof(ad_zp_t, f.BINSCR) == 0xDA,
               "BINSCR must sit at $00DA");
_Static_assert(offsetof(ad_zp_t, f.PERR) == 0xDB,
               "PERR must sit at $00DB");
_Static_assert(offsetof(ad_zp_t, f.CKERR) == 0xE0,
               "CKERR must sit at $00E0");
_Static_assert(offsetof(ad_zp_t, f.RVELP) == 0xE1,
               "RVELP must sit at $00E1");
_Static_assert(offsetof(ad_zp_t, f.RVELM) == 0xE2,
               "RVELM must sit at $00E2");
_Static_assert(offsetof(ad_zp_t, f.HSSND) == 0xE3,
               "HSSND must sit at $00E3");
_Static_assert(offsetof(ad_zp_t, f.SBTLT) == 0xE4,
               "SBTLT must sit at $00E4");
_Static_assert(offsetof(ad_zp_t, f.EXPDX) == 0xE5,
               "EXPDX must sit at $00E5");
_Static_assert(offsetof(ad_zp_t, f.EXPDY) == 0xED,
               "EXPDY must sit at $00ED");
_Static_assert(offsetof(ad_zp_t, f.EXPANG) == 0xF5,
               "EXPANG must sit at $00F5");
_Static_assert(offsetof(ad_zp_t, f.BONSCR) == 0xFD,
               "BONSCR must sit at $00FD");
_Static_assert(offsetof(ad_pg1_t, f.SXPXL) == 0x00,
               "SXPXL must sit at $0100");
_Static_assert(offsetof(ad_pg1_t, f.SXPYL) == 0x08,
               "SXPYL must sit at $0108");
_Static_assert(offsetof(ad_pg1_t, f.SXPXH) == 0x10,
               "SXPXH must sit at $0110");
_Static_assert(offsetof(ad_pg1_t, f.SXPYH) == 0x18,
               "SXPYH must sit at $0118");
_Static_assert(offsetof(ad_pg1_t, f.EXPTMB) == 0x20,
               "EXPTMB must sit at $0120");
_Static_assert(offsetof(ad_player_t, f.OBJ) == 0x00,
               "OBJ must sit at $0200");
_Static_assert(offsetof(ad_player_t, f.SHPPIX) == 0x19,
               "SHPPIX must sit at $0219");
_Static_assert(offsetof(ad_player_t, f.SAUPIX) == 0x1A,
               "SAUPIX must sit at $021A");
_Static_assert(offsetof(ad_player_t, f.SAUTP) == 0x1B,
               "SAUTP must sit at $021B");
_Static_assert(offsetof(ad_player_t, f.SHPTP) == 0x1D,
               "SHPTP must sit at $021D");
_Static_assert(offsetof(ad_player_t, f.XINC) == 0x21,
               "XINC must sit at $0221");
_Static_assert(offsetof(ad_player_t, f.SHPXI) == 0x3A,
               "SHPXI must sit at $023A");
_Static_assert(offsetof(ad_player_t, f.SAUXI) == 0x3B,
               "SAUXI must sit at $023B");
_Static_assert(offsetof(ad_player_t, f.SAUTXI) == 0x3C,
               "SAUTXI must sit at $023C");
_Static_assert(offsetof(ad_player_t, f.SHPTXI) == 0x3E,
               "SHPTXI must sit at $023E");
_Static_assert(offsetof(ad_player_t, f.YINC) == 0x42,
               "YINC must sit at $0242");
_Static_assert(offsetof(ad_player_t, f.SHPYI) == 0x5B,
               "SHPYI must sit at $025B");
_Static_assert(offsetof(ad_player_t, f.SAUYI) == 0x5C,
               "SAUYI must sit at $025C");
_Static_assert(offsetof(ad_player_t, f.SAUTYI) == 0x5D,
               "SAUTYI must sit at $025D");
_Static_assert(offsetof(ad_player_t, f.SHPTYI) == 0x5F,
               "SHPTYI must sit at $025F");
_Static_assert(offsetof(ad_player_t, f.OBJXH) == 0x63,
               "OBJXH must sit at $0263");
_Static_assert(offsetof(ad_player_t, f.SHPXH) == 0x7C,
               "SHPXH must sit at $027C");
_Static_assert(offsetof(ad_player_t, f.SAUXH) == 0x7D,
               "SAUXH must sit at $027D");
_Static_assert(offsetof(ad_player_t, f.SAUTXH) == 0x7E,
               "SAUTXH must sit at $027E");
_Static_assert(offsetof(ad_player_t, f.SHPTXH) == 0x80,
               "SHPTXH must sit at $0280");
_Static_assert(offsetof(ad_player_t, f.OBJYH) == 0x84,
               "OBJYH must sit at $0284");
_Static_assert(offsetof(ad_player_t, f.SHPYH) == 0x9D,
               "SHPYH must sit at $029D");
_Static_assert(offsetof(ad_player_t, f.SAUYH) == 0x9E,
               "SAUYH must sit at $029E");
_Static_assert(offsetof(ad_player_t, f.SAUTYH) == 0x9F,
               "SAUTYH must sit at $029F");
_Static_assert(offsetof(ad_player_t, f.SHPTYH) == 0xA1,
               "SHPTYH must sit at $02A1");
_Static_assert(offsetof(ad_player_t, f.OBJXL) == 0xA5,
               "OBJXL must sit at $02A5");
_Static_assert(offsetof(ad_player_t, f.SHPXL) == 0xBE,
               "SHPXL must sit at $02BE");
_Static_assert(offsetof(ad_player_t, f.SAUXL) == 0xBF,
               "SAUXL must sit at $02BF");
_Static_assert(offsetof(ad_player_t, f.SAUTXL) == 0xC0,
               "SAUTXL must sit at $02C0");
_Static_assert(offsetof(ad_player_t, f.SHPTXL) == 0xC2,
               "SHPTXL must sit at $02C2");
_Static_assert(offsetof(ad_player_t, f.OBJYL) == 0xC6,
               "OBJYL must sit at $02C6");
_Static_assert(offsetof(ad_player_t, f.SHPYL) == 0xDF,
               "SHPYL must sit at $02DF");
_Static_assert(offsetof(ad_player_t, f.SAUYL) == 0xE0,
               "SAUYL must sit at $02E0");
_Static_assert(offsetof(ad_player_t, f.SAUTYL) == 0xE1,
               "SAUTYL must sit at $02E1");
_Static_assert(offsetof(ad_player_t, f.SHPTYL) == 0xE3,
               "SHPTYL must sit at $02E3");
_Static_assert(offsetof(ad_player_t, f.NROCKS) == 0xE7,
               "NROCKS must sit at $02E7");
_Static_assert(offsetof(ad_player_t, f.EDELAY) == 0xE8,
               "EDELAY must sit at $02E8");
_Static_assert(offsetof(ad_player_t, f.SEDLAY) == 0xE9,
               "SEDLAY must sit at $02E9");
_Static_assert(offsetof(ad_player_t, f.RTIMER) == 0xEA,
               "RTIMER must sit at $02EA");
_Static_assert(offsetof(ad_player_t, f.SDELAY) == 0xEB,
               "SDELAY must sit at $02EB");
_Static_assert(offsetof(ad_player_t, f.RDELAY) == 0xEC,
               "RDELAY must sit at $02EC");
_Static_assert(offsetof(ad_player_t, f.THUMP3) == 0xED,
               "THUMP3 must sit at $02ED");
_Static_assert(offsetof(ad_player_t, f.DIFCTY) == 0xEE,
               "DIFCTY must sit at $02EE");
_Static_assert(offsetof(ad_player_t, f.SHLDS) == 0xEF,
               "SHLDS must sit at $02EF");
_Static_assert(offsetof(ad_player_t, f.SROCKS) == 0xF0,
               "SROCKS must sit at $02F0");
_Static_assert(offsetof(ad_player_t, f.SRANG) == 0xF1,
               "SRANG must sit at $02F1");
_Static_assert(offsetof(ad_player_t, f.SRTIME) == 0xF8,
               "SRTIME must sit at $02F8");
_Static_assert(offsetof(ad_player_t, f.SPROCK) == 0xFF,
               "SPROCK must sit at $02FF");

/* Offsets for the parallel-array object model.  The ROM indexes
 * across these deliberately - 0..24 are rocks, 25 the ship, 26
 * the saucer, 27-28 its torpedoes, 29-32 the ship's - so they are
 * reached through the raw view, not as separate C arrays. */
#define AD_OBJ      0x00   /* $0200 */
#define AD_XINC     0x21   /* $0221 */
#define AD_YINC     0x42   /* $0242 */
#define AD_OBJXH    0x63   /* $0263 */
#define AD_OBJYH    0x84   /* $0284 */
#define AD_OBJXL    0xA5   /* $02A5 */
#define AD_OBJYL    0xC6   /* $02C6 */

#define AD_NOBJ      25   /* rocks; DSTDEC.MAC NOBJ */
#define AD_NSPCLS     7   /* special rocks; DSTDEC.MAC NSPCLS */
#define AD_SLOTS     33   /* rocks + ship + saucer + 6 torpedoes */
#define AD_SHIP      25
#define AD_SAUCER    26
#define AD_SAUTP     27   /* .. 28 */
#define AD_SHPTP     29   /* .. 32 */

#endif /* ASTDELUX_STATE_H */
