/* Asteroids Deluxe - the ROM images, as data.
 *
 * GENERATED by disasm/mkrom.py.  Do not hand-edit.
 *
 * ad_rom(addr) returns the byte the 6502 would read at a ROM
 * address, so a table is read at the address the listing shows:
 *
 *     ad_rom(0x4B51 + i)      SINCOS,i
 *
 * Addresses outside the two ROM regions return 0; the game never
 * reads a table from anywhere else. */
#ifndef ASTDELUX_ROM_H
#define ASTDELUX_ROM_H

#include <stdint.h>

#define AD_VECROM_BASE 0x4800
#define AD_VECROM_SIZE 0x1000
extern const uint8_t ad_vecrom[0x1000];

#define AD_PROGROM_BASE 0x6000
#define AD_PROGROM_SIZE 0x2000
extern const uint8_t ad_progrom[0x2000];

extern const uint8_t ad_dvgprom[0x100];

static inline uint8_t ad_rom(uint16_t addr)
{
    if (addr >= 0x4800u && addr < 0x5800u)
        return ad_vecrom[addr - 0x4800u];
    if (addr >= 0x6000u && addr < 0x8000u)
        return ad_progrom[addr - 0x6000u];
    return 0;
}

/* A little-endian word, as `lda T,x / lda T+1,x` pairs read one. */
static inline uint16_t ad_rom16(uint16_t addr)
{
    return (uint16_t)(ad_rom(addr) | (ad_rom((uint16_t)(addr + 1)) << 8));
}

#endif /* ASTDELUX_ROM_H */
