[main]
vsync=1
frame_hz=60.000000
;62.500000
[joystick]
deadzone=19
[vector]
linewidth=2.000000
gain=0
line_smoothing=1.000000
corner_strength=0.900000
endcap_strength=0.900000
fire_point_size=10.000000
phosphor=0
phosphor_ms=8.000000
[dips]
language=english
lives=3
min_plays=1
difficulty=hard
bonus_life=10000
coinage=1_coin_1_play
right_coin=x1
center_coin=x1
bonus_coins=2_each_4
[game]
revision=2
